name: LocalAIPlayground
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  RunAnywhere:
    url: https://github.com/RunanywhereAI/runanywhere-sdks
    exactVersion: 0.16.0-test.39

targets:
  LocalAIPlayground:
    type: application
    platform: iOS
    sources:
      - path: LocalAIPlayground
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.LocalAIPlayground
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: LocalAIPlayground/Info.plist
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
    dependencies:
      - package: RunAnywhere
        product: RunAnywhere
      - package: RunAnywhere
        product: RunAnywhereLlamaCPP
      - package: RunAnywhere
        product: RunAnywhereONNX

  LocalAIPlaygroundTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LocalAIPlaygroundTests
    dependencies:
      - target: LocalAIPlayground

  LocalAIPlaygroundUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LocalAIPlaygroundUITests
    dependencies:
      - target: LocalAIPlayground

schemes:
  LocalAIPlayground:
    build:
      targets:
        LocalAIPlayground: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LocalAIPlaygroundTests
        - LocalAIPlaygroundUITests
