/**
 * HTTPAdapter.ts (Web / WASM) — T3.13.
 *
 * Thin TypeScript wrapper around the commons libcurl-backed C ABI
 * declared in:
 *   sdk/runanywhere-commons/include/rac/infrastructure/http/rac_http_client.h
 *   sdk/runanywhere-commons/include/rac/infrastructure/http/rac_http_download.h
 *
 * Why this exists:
 *   Before T3.13 every Web SDK site re-implemented HTTP with browser fetch
 *   + ad-hoc progress loops. Parity with the other SDKs (Swift /
 *   Kotlin / React Native / Flutter) now routes through the commons
 *   HTTP C ABI so redirects, resume, checksum, and progress semantics
 *   are identical across platforms.
 *
 * Module injection:
 *   The Web backend packages (`@runanywhere/web-llamacpp`,
 *   `@runanywhere/web-onnx`) each load an independent Emscripten
 *   module. They call `HTTPAdapter.setDefaultModule(module)` on load,
 *   so the core package (pure TypeScript) can reach into C++ without
 *   a hard dependency on any specific backend. Core callers that want
 *   to issue HTTP requests ask for `HTTPAdapter.tryDefault()`; when
 *   no backend has loaded yet, the helper returns `null` and the
 *   caller may fall back to browser fetch only for the carve-outs
 *   documented in `HTTP_FETCH_CARVE_OUTS`.
 *
 * Threading / blocking:
 *   `_rac_http_request_send` / `_rac_http_request_stream` /
 *   `_rac_http_download_execute` block the calling thread inside
 *   libcurl. Emscripten serves network I/O through the browser's
 *   fetch/XHR under the hood, so on the main thread these calls
 *   must be run via `ccall({ async: true })` (ASYNCIFY / JSPI). The
 *   adapter always uses `{ async: true }` so it works from either a
 *   dedicated worker or the main thread without caller-side changes.
 */

import { SDKLogger } from '../Foundation/SDKLogger';
import { FetchHttpTransport } from './FetchHttpTransport';

const logger = new SDKLogger('HTTPAdapter');

/**
 * The only legitimate direct browser-fetch carve-outs in the Web SDK.
 * Everything else should route through `HTTPAdapter` once a backend
 * Emscripten module with `rac_http_*` exports is available.
 */
export const HTTP_FETCH_CARVE_OUTS = {
  bootstrapOnly: 'bootstrap-only: fetches the WASM/glue asset needed before any HTTPAdapter-capable module exists',
  browserOnlyBlobImport: 'browser-only blob import: fetches JavaScript text that must be patched and imported from a Blob URL',
  noWasmModuleRegisteredFallback: 'fallback when no WASM module registered: preserves pure-core or ONNX-only browser usage before an HTTPAdapter default exists',
} as const;

// ---------------------------------------------------------------------------
// Module shape — the minimum Emscripten surface HTTPAdapter needs.
// Re-declared locally so core stays decoupled from any one backend's
// module typings (`LlamaCppModule`, `SherpaONNXModule`, ...).
// ---------------------------------------------------------------------------

export interface HTTPModule {
  _malloc(size: number): number;
  _free(ptr: number): void;
  setValue(ptr: number, value: number, type: string): void;
  getValue(ptr: number, type: string): number;
  UTF8ToString(ptr: number, maxBytesToRead?: number): string;
  stringToUTF8(str: string, ptr: number, maxBytesToWrite: number): void;
  lengthBytesUTF8(str: string): number;

  addFunction(fn: (...args: number[]) => number | void, signature: string): number;
  removeFunction(ptr: number): void;

  HEAPU8?: Uint8Array;

  ccall: (
    name: string,
    returnType: string | null,
    argTypes: string[],
    args: unknown[],
    opts?: { async?: boolean },
  ) => unknown;

  // HTTP exports — all optional at type level so failure surfaces early
  // with a clear error ("module does not export rac_http_*") rather than
  // a TypeError on undefined().
  _rac_http_client_create?(outPtr: number): number;
  _rac_http_client_destroy?(clientPtr: number): void;
  _rac_http_response_free?(respPtr: number): void;

  // Transport registry (v2 close-out Phase H2 / H7). Present only on
  // the WASM build of commons — registers the emscripten_fetch-backed
  // adapter with the platform HTTP router so the libcurl fallback
  // (compiled out on WASM) is bypassed for every `rac_http_request_*`
  // call. Returns `RAC_SUCCESS` (0) on success.
  _rac_http_transport_register_emscripten?(): number;
  _rac_http_transport_is_registered?(): number;

  // Stage 3d — JS-side transport registration. The JS layer installs
  // function-table indices for the transport vtable directly (see
  // FetchHttpTransport.ts) so requests can be routed through `fetch()`
  // without bouncing through `emscripten_fetch`. Pass 0 for any op you
  // want to fall back on the emscripten_fetch path; all-zero unregisters.
  _rac_http_transport_register_from_js?(
    requestSendPtr: number,
    requestStreamPtr: number,
    requestResumePtr: number,
  ): number;

  // Struct layout helpers — generated by wasm_exports.cpp.
  _rac_wasm_sizeof_http_request?(): number;
  _rac_wasm_sizeof_http_response?(): number;
  _rac_wasm_sizeof_http_download_request?(): number;
  _rac_wasm_sizeof_http_header_kv?(): number;
  _rac_wasm_offsetof_http_request_method?(): number;
  _rac_wasm_offsetof_http_request_url?(): number;
  _rac_wasm_offsetof_http_request_headers?(): number;
  _rac_wasm_offsetof_http_request_header_count?(): number;
  _rac_wasm_offsetof_http_request_body_bytes?(): number;
  _rac_wasm_offsetof_http_request_body_len?(): number;
  _rac_wasm_offsetof_http_request_timeout_ms?(): number;
  _rac_wasm_offsetof_http_request_follow_redirects?(): number;
  _rac_wasm_offsetof_http_request_expected_checksum_hex?(): number;
  _rac_wasm_offsetof_http_response_status?(): number;
  _rac_wasm_offsetof_http_response_headers?(): number;
  _rac_wasm_offsetof_http_response_header_count?(): number;
  _rac_wasm_offsetof_http_response_body_bytes?(): number;
  _rac_wasm_offsetof_http_response_body_len?(): number;
  _rac_wasm_offsetof_http_response_redirected_url?(): number;
  _rac_wasm_offsetof_http_header_kv_name?(): number;
  _rac_wasm_offsetof_http_header_kv_value?(): number;
  _rac_wasm_offsetof_http_download_request_url?(): number;
  _rac_wasm_offsetof_http_download_request_destination_path?(): number;
  _rac_wasm_offsetof_http_download_request_headers?(): number;
  _rac_wasm_offsetof_http_download_request_header_count?(): number;
  _rac_wasm_offsetof_http_download_request_timeout_ms?(): number;
  _rac_wasm_offsetof_http_download_request_follow_redirects?(): number;
  _rac_wasm_offsetof_http_download_request_resume_from_byte?(): number;
  _rac_wasm_offsetof_http_download_request_expected_sha256_hex?(): number;

  // Optional FS handle — used by `download()` since the C ABI writes to
  // a filesystem path and callers usually want bytes back. Not all
  // backend modules configure the same FS shape, hence the loose type.
  FS?: {
    readFile(path: string): Uint8Array;
    unlink(path: string): void;
    writeFile?(path: string, data: Uint8Array): void;
    mkdir?(path: string): void;
    analyzePath?(path: string): { exists: boolean };
  };
  FS_createPath?(parent: string, path: string, canRead: boolean, canWrite: boolean): void;
}

// ---------------------------------------------------------------------------
// Public request/response value types
// ---------------------------------------------------------------------------

export interface HTTPHeader {
  name: string;
  value: string;
}

/** JS-side descriptor for a blocking or streaming HTTP request. */
export interface HTTPRequest {
  method?: string;                 // default: 'GET'
  url: string;
  headers?: HTTPHeader[];
  body?: Uint8Array;
  timeoutMs?: number;              // default: 0 (no timeout)
  followRedirects?: boolean;       // default: true
  expectedChecksumHex?: string;    // advisory only, HTTP client does not verify
}

/** Response from a blocking send. Body is null for streaming calls. */
export interface HTTPResponse {
  status: number;
  body: Uint8Array | null;
  redirectedUrl: string | null;
}

/** Body chunk callback for streaming requests. Return false to cancel. */
export type ChunkHandler = (chunk: Uint8Array, totalWritten: number, contentLength: number) => boolean | void;

/** Progress callback for downloads (`rac_http_download_execute`). */
export type DownloadProgressHandler = (bytesWritten: number, totalBytes: number) => boolean | void;

export interface DownloadRequest {
  url: string;
  destinationPath: string;
  headers?: HTTPHeader[];
  timeoutMs?: number;
  followRedirects?: boolean;
  resumeFromByte?: number;
  expectedSha256Hex?: string;
}

// Mirrors rac_http_download_status_t in rac_http_download.h — keep in sync.
export enum DownloadStatus {
  OK = 0,
  NetworkError = 1,
  FileError = 2,
  InsufficientStorage = 3,
  InvalidUrl = 4,
  ChecksumFailed = 5,
  Cancelled = 6,
  ServerError = 7,
  Timeout = 8,
  NetworkUnavailable = 9,
  DnsError = 10,
  SslError = 11,
  Unknown = 99,
}

// RAC_TRUE / RAC_FALSE from rac_types.h — curl-backed client returns
// these raw ints through the chunk / progress callbacks.
const RAC_TRUE = 1;
const RAC_FALSE = 0;

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

/** Allocator scope — tracks every _malloc so a single release frees them all. */
class AllocScope {
  private readonly ptrs: number[] = [];
  constructor(private readonly m: HTTPModule) {}

  alloc(size: number): number {
    const ptr = this.m._malloc(size);
    this.ptrs.push(ptr);
    return ptr;
  }

  allocString(str: string): number {
    const len = this.m.lengthBytesUTF8(str) + 1;
    const ptr = this.alloc(len);
    this.m.stringToUTF8(str, ptr, len);
    return ptr;
  }

  allocBytes(bytes: Uint8Array): number {
    const ptr = this.alloc(bytes.length);
    writeBytes(this.m, bytes, ptr);
    return ptr;
  }

  free(): void {
    for (const ptr of this.ptrs) {
      try { this.m._free(ptr); } catch { /* noop */ }
    }
    this.ptrs.length = 0;
  }
}

function writeBytes(m: HTTPModule, src: Uint8Array, destPtr: number): void {
  if (m.HEAPU8) {
    m.HEAPU8.set(src, destPtr);
    return;
  }
  for (let i = 0; i < src.length; i++) m.setValue(destPtr + i, src[i], 'i8');
}

function readBytes(m: HTTPModule, srcPtr: number, length: number): Uint8Array {
  if (srcPtr === 0 || length <= 0) return new Uint8Array(0);
  if (m.HEAPU8) return m.HEAPU8.slice(srcPtr, srcPtr + length);
  const out = new Uint8Array(length);
  for (let i = 0; i < length; i++) out[i] = m.getValue(srcPtr + i, 'i8') & 0xff;
  return out;
}

function required<T>(fn: T | undefined, name: string): T {
  if (fn === undefined || fn === null) {
    throw new Error(
      `HTTPAdapter: WASM module is missing export '${name}'. ` +
      `Rebuild the WASM target with the T3.13 HTTP exports enabled.`,
    );
  }
  return fn;
}

function writeHeaders(scope: AllocScope, m: HTTPModule, headers: HTTPHeader[] | undefined): { ptr: number; count: number } {
  if (!headers || headers.length === 0) return { ptr: 0, count: 0 };
  const kvSize = required(m._rac_wasm_sizeof_http_header_kv, 'rac_wasm_sizeof_http_header_kv')();
  const offName = required(m._rac_wasm_offsetof_http_header_kv_name, 'rac_wasm_offsetof_http_header_kv_name')();
  const offValue = required(m._rac_wasm_offsetof_http_header_kv_value, 'rac_wasm_offsetof_http_header_kv_value')();
  const arrayPtr = scope.alloc(kvSize * headers.length);
  for (let i = 0; i < headers.length; i++) {
    const itemPtr = arrayPtr + i * kvSize;
    m.setValue(itemPtr + offName, scope.allocString(headers[i].name), '*');
    m.setValue(itemPtr + offValue, scope.allocString(headers[i].value), '*');
  }
  return { ptr: arrayPtr, count: headers.length };
}

function writeRequestStruct(scope: AllocScope, m: HTTPModule, req: HTTPRequest): number {
  const size = required(m._rac_wasm_sizeof_http_request, 'rac_wasm_sizeof_http_request')();
  const ptr = scope.alloc(size);
  for (let i = 0; i < size; i++) m.setValue(ptr + i, 0, 'i8');

  const { ptr: headersPtr, count: headerCount } = writeHeaders(scope, m, req.headers);

  m.setValue(ptr + required(m._rac_wasm_offsetof_http_request_method, 'rac_wasm_offsetof_http_request_method')(),
    scope.allocString(req.method ?? 'GET'), '*');
  m.setValue(ptr + required(m._rac_wasm_offsetof_http_request_url, 'rac_wasm_offsetof_http_request_url')(),
    scope.allocString(req.url), '*');
  m.setValue(ptr + required(m._rac_wasm_offsetof_http_request_headers, 'rac_wasm_offsetof_http_request_headers')(),
    headersPtr, '*');
  m.setValue(ptr + required(m._rac_wasm_offsetof_http_request_header_count, 'rac_wasm_offsetof_http_request_header_count')(),
    headerCount, 'i32');

  if (req.body && req.body.length > 0) {
    m.setValue(ptr + required(m._rac_wasm_offsetof_http_request_body_bytes, 'rac_wasm_offsetof_http_request_body_bytes')(),
      scope.allocBytes(req.body), '*');
    m.setValue(ptr + required(m._rac_wasm_offsetof_http_request_body_len, 'rac_wasm_offsetof_http_request_body_len')(),
      req.body.length, 'i32');
  }

  m.setValue(ptr + required(m._rac_wasm_offsetof_http_request_timeout_ms, 'rac_wasm_offsetof_http_request_timeout_ms')(),
    req.timeoutMs ?? 0, 'i32');
  m.setValue(ptr + required(m._rac_wasm_offsetof_http_request_follow_redirects, 'rac_wasm_offsetof_http_request_follow_redirects')(),
    req.followRedirects === false ? RAC_FALSE : RAC_TRUE, 'i32');

  if (req.expectedChecksumHex) {
    m.setValue(ptr + required(m._rac_wasm_offsetof_http_request_expected_checksum_hex, 'rac_wasm_offsetof_http_request_expected_checksum_hex')(),
      scope.allocString(req.expectedChecksumHex), '*');
  }

  return ptr;
}

function readResponseStruct(m: HTTPModule, respPtr: number): HTTPResponse {
  const offStatus = required(m._rac_wasm_offsetof_http_response_status, 'rac_wasm_offsetof_http_response_status')();
  const offBody = required(m._rac_wasm_offsetof_http_response_body_bytes, 'rac_wasm_offsetof_http_response_body_bytes')();
  const offBodyLen = required(m._rac_wasm_offsetof_http_response_body_len, 'rac_wasm_offsetof_http_response_body_len')();
  const offRedirected = required(m._rac_wasm_offsetof_http_response_redirected_url, 'rac_wasm_offsetof_http_response_redirected_url')();

  const status = m.getValue(respPtr + offStatus, 'i32');
  const bodyPtr = m.getValue(respPtr + offBody, '*');
  const bodyLen = m.getValue(respPtr + offBodyLen, 'i32');
  const redirectedPtr = m.getValue(respPtr + offRedirected, '*');

  // Copy bytes out of WASM heap — the buffer is freed by
  // rac_http_response_free and would otherwise become a dangling view.
  const body = bodyPtr !== 0 && bodyLen > 0 ? readBytes(m, bodyPtr, bodyLen) : null;
  const redirectedUrl = redirectedPtr !== 0 ? m.UTF8ToString(redirectedPtr) : null;

  return { status, body, redirectedUrl };
}

// ---------------------------------------------------------------------------
// Public adapter
// ---------------------------------------------------------------------------

/**
 * Thin OO wrapper over `rac_http_client_*` / `rac_http_download_execute`.
 * Each instance binds to a single Emscripten module. Stateless beyond
 * that — a fresh C client handle is created/destroyed per call so
 * requests can safely be issued concurrently from JS (libcurl easy
 * handles are not thread-safe, so sharing one across overlapping
 * awaits would be incorrect).
 */
export class HTTPAdapter {
  constructor(private readonly m: HTTPModule) {}

  /** Blocking request — buffers the full body into memory. */
  async request(req: HTTPRequest): Promise<HTTPResponse> {
    const clientPtr = await this.createClient();
    const scope = new AllocScope(this.m);
    const respSize = required(this.m._rac_wasm_sizeof_http_response, 'rac_wasm_sizeof_http_response')();
    const respPtr = scope.alloc(respSize);
    for (let i = 0; i < respSize; i++) this.m.setValue(respPtr + i, 0, 'i8');

    try {
      const reqPtr = writeRequestStruct(scope, this.m, req);
      const rc = await this.ccall('rac_http_request_send', 'number', ['number', 'number', 'number'], [clientPtr, reqPtr, respPtr]);
      if (rc !== 0) {
        throw new Error(`rac_http_request_send failed: rc=${rc} url=${req.url}`);
      }
      const response = readResponseStruct(this.m, respPtr);
      required(this.m._rac_http_response_free, 'rac_http_response_free')(respPtr);
      return response;
    } finally {
      scope.free();
      this.destroyClient(clientPtr);
    }
  }

  /**
   * Streaming request — body chunks are delivered via `onChunk`. The
   * body is NEVER buffered in memory by the adapter, so this is the
   * right call for model-sized payloads.
   *
   * The chunk handler can return `false` to abort the transfer; the
   * underlying curl connection is torn down immediately and the
   * returned promise rejects with a cancellation error.
   */
  async stream(req: HTTPRequest, onChunk: ChunkHandler): Promise<HTTPResponse> {
    const clientPtr = await this.createClient();
    const scope = new AllocScope(this.m);
    const respSize = required(this.m._rac_wasm_sizeof_http_response, 'rac_wasm_sizeof_http_response')();
    const respPtr = scope.alloc(respSize);
    for (let i = 0; i < respSize; i++) this.m.setValue(respPtr + i, 0, 'i8');

    // Function-table trampoline for the C body-chunk callback. Must
    // match rac_http_body_chunk_fn: rac_bool_t (const uint8_t*, size_t,
    // uint64_t total_written, uint64_t content_length, void* user_data)
    // → signature 'iiijji' (i=int, j=int64).
    let cancelled = false;
    const cbPtr = this.m.addFunction(
      (chunkPtr: number, chunkLen: number, totalWritten: number, _totalWrittenHi: number, contentLength: number /* and hi + user_data further args */) => {
        try {
          const bytes = readBytes(this.m, chunkPtr, chunkLen);
          const keep = onChunk(bytes, totalWritten, contentLength);
          if (keep === false) {
            cancelled = true;
            return RAC_FALSE;
          }
          return RAC_TRUE;
        } catch (err) {
          cancelled = true;
          logger.warning(`HTTPAdapter.stream chunk handler threw: ${err instanceof Error ? err.message : String(err)}`);
          return RAC_FALSE;
        }
      },
      'iiiijji',
    );

    try {
      const reqPtr = writeRequestStruct(scope, this.m, req);
      const rc = await this.ccall('rac_http_request_stream', 'number',
        ['number', 'number', 'number', 'number', 'number'],
        [clientPtr, reqPtr, cbPtr, 0, respPtr]);
      if (rc !== 0) {
        const reason = cancelled ? 'cancelled by chunk handler' : `rc=${rc}`;
        throw new Error(`rac_http_request_stream failed: ${reason} url=${req.url}`);
      }
      const response = readResponseStruct(this.m, respPtr);
      required(this.m._rac_http_response_free, 'rac_http_response_free')(respPtr);
      return response;
    } finally {
      this.m.removeFunction(cbPtr);
      scope.free();
      this.destroyClient(clientPtr);
    }
  }

  /**
   * File download via `rac_http_download_execute`. Writes bytes to the
   * Emscripten virtual filesystem at `destinationPath`. The optional
   * progress callback fires on every chunk libcurl delivers.
   *
   * Callers that want the bytes back in JS should read the file from
   * the module's FS after the promise resolves. This matches the
   * native behaviour (iOS / Android / RN all hand the caller a file
   * path, not a buffer).
   */
  async download(req: DownloadRequest, onProgress?: DownloadProgressHandler): Promise<DownloadStatus> {
    const scope = new AllocScope(this.m);

    // Function-table trampoline for rac_http_download_progress_fn:
    //   rac_bool_t (uint64_t bytes_written, uint64_t total_bytes,
    //               void* user_data)
    // → signature 'ijji' (i=return int, j=int64, i=int).
    let cancelled = false;
    const progressPtr = onProgress
      ? this.m.addFunction(
          (bytesWritten: number, _bytesWrittenHi: number, totalBytes: number /* and hi + user_data */) => {
            try {
              const keep = onProgress(bytesWritten, totalBytes);
              if (keep === false) {
                cancelled = true;
                return RAC_FALSE;
              }
              return RAC_TRUE;
            } catch (err) {
              cancelled = true;
              logger.warning(`HTTPAdapter.download progress handler threw: ${err instanceof Error ? err.message : String(err)}`);
              return RAC_FALSE;
            }
          },
          'ijji',
        )
      : 0;

    const outHttpStatusPtr = scope.alloc(4);
    this.m.setValue(outHttpStatusPtr, 0, 'i32');

    try {
      const reqPtr = writeDownloadRequestStruct(scope, this.m, req);
      const status = await this.ccall('rac_http_download_execute', 'number',
        ['number', 'number', 'number', 'number'],
        [reqPtr, progressPtr, 0, outHttpStatusPtr]) as number;
      if (status !== DownloadStatus.OK && cancelled) {
        return DownloadStatus.Cancelled;
      }
      return status as DownloadStatus;
    } finally {
      if (progressPtr !== 0) this.m.removeFunction(progressPtr);
      scope.free();
    }
  }

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  private async createClient(): Promise<number> {
    const outPtrPtr = this.m._malloc(4);
    try {
      this.m.setValue(outPtrPtr, 0, '*');
      const rc = await this.ccall('rac_http_client_create', 'number', ['number'], [outPtrPtr]) as number;
      if (rc !== 0) throw new Error(`rac_http_client_create failed: rc=${rc}`);
      const clientPtr = this.m.getValue(outPtrPtr, '*');
      if (clientPtr === 0) throw new Error('rac_http_client_create returned NULL');
      return clientPtr;
    } finally {
      this.m._free(outPtrPtr);
    }
  }

  private destroyClient(clientPtr: number): void {
    if (clientPtr === 0) return;
    try {
      required(this.m._rac_http_client_destroy, 'rac_http_client_destroy')(clientPtr);
    } catch (err) {
      logger.warning(`rac_http_client_destroy threw: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  private async ccall(name: string, returnType: string | null, argTypes: string[], args: unknown[]): Promise<number> {
    // `async: true` wraps the invocation in ASYNCIFY/JSPI so libcurl
    // can suspend inside Emscripten's fetch-backed socket layer without
    // blocking the JS event loop.
    const result = this.m.ccall(name, returnType, argTypes, args, { async: true });
    if (result && typeof (result as { then?: unknown }).then === 'function') {
      return (await (result as Promise<number>));
    }
    return result as number;
  }

  // =========================================================================
  // Default-module registry
  //
  // Backend packages (`@runanywhere/web-llamacpp`, `@runanywhere/web-onnx`)
  // install their Emscripten module here after WASM load. Core callers
  // that don't have direct access to a backend module use
  // `HTTPAdapter.tryDefault()` to reach the first one that registered.
  // =========================================================================

  private static defaultInstance: HTTPAdapter | null = null;

  static setDefaultModule(module: HTTPModule): void {
    HTTPAdapter.defaultInstance = new HTTPAdapter(module);

    // v2 close-out Phase H7: on the WASM commons build the
    // emscripten_fetch-backed adapter registers itself via the platform
    // HTTP transport vtable so the router in rac_http_client_curl.cpp
    // short-circuits to it. The symbol is only exported from the WASM
    // build (see sdk/runanywhere-web/wasm/CMakeLists.txt
    // RAC_EXPORTED_FUNCTIONS list); on any other module it's missing and
    // we skip registration silently (the curl fallback handles requests).
    const register = module._rac_http_transport_register_emscripten;
    if (typeof register === 'function') {
      try {
        const rc = register();
        if (rc !== 0) {
          logger.warning(`rac_http_transport_register_emscripten returned rc=${rc}`);
        } else {
          logger.debug('Emscripten fetch HTTP transport registered via vtable');
        }
      } catch (err) {
        logger.warning(
          `rac_http_transport_register_emscripten threw: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    }

    // Stage 3d — JS-side adapter registration. Installed AFTER the
    // emscripten_fetch registration above so any subsequent HTTP request
    // goes through the JS trampolines when the module supports them. When
    // the build lacks the Stage 3d export (`_rac_http_transport_register_from_js`)
    // the install() call is a silent no-op and the emscripten_fetch
    // adapter above remains active.
    //
    // No circular import: FetchHttpTransport only imports `HTTPModule`
    // as a type from this file, so the TS side erases it at compile time.
    try {
      FetchHttpTransport.install(module);
    } catch (err) {
      logger.warning(
        `FetchHttpTransport.install threw: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  static clearDefaultModule(): void {
    HTTPAdapter.defaultInstance = null;
  }

  static tryDefault(): HTTPAdapter | null {
    return HTTPAdapter.defaultInstance;
  }
}

function writeDownloadRequestStruct(scope: AllocScope, m: HTTPModule, req: DownloadRequest): number {
  const size = required(m._rac_wasm_sizeof_http_download_request, 'rac_wasm_sizeof_http_download_request')();
  const ptr = scope.alloc(size);
  for (let i = 0; i < size; i++) m.setValue(ptr + i, 0, 'i8');

  const { ptr: headersPtr, count: headerCount } = writeHeaders(scope, m, req.headers);

  m.setValue(ptr + required(m._rac_wasm_offsetof_http_download_request_url, 'rac_wasm_offsetof_http_download_request_url')(),
    scope.allocString(req.url), '*');
  m.setValue(ptr + required(m._rac_wasm_offsetof_http_download_request_destination_path, 'rac_wasm_offsetof_http_download_request_destination_path')(),
    scope.allocString(req.destinationPath), '*');
  m.setValue(ptr + required(m._rac_wasm_offsetof_http_download_request_headers, 'rac_wasm_offsetof_http_download_request_headers')(),
    headersPtr, '*');
  m.setValue(ptr + required(m._rac_wasm_offsetof_http_download_request_header_count, 'rac_wasm_offsetof_http_download_request_header_count')(),
    headerCount, 'i32');
  m.setValue(ptr + required(m._rac_wasm_offsetof_http_download_request_timeout_ms, 'rac_wasm_offsetof_http_download_request_timeout_ms')(),
    req.timeoutMs ?? 0, 'i32');
  m.setValue(ptr + required(m._rac_wasm_offsetof_http_download_request_follow_redirects, 'rac_wasm_offsetof_http_download_request_follow_redirects')(),
    req.followRedirects === false ? RAC_FALSE : RAC_TRUE, 'i32');
  // resume_from_byte is uint64_t — write low 32 bits, zero high half.
  // JS numbers beyond 2^32 aren't supported here; callers that need
  // multi-TB resume would hit Number.MAX_SAFE_INTEGER long before.
  const offResume = required(m._rac_wasm_offsetof_http_download_request_resume_from_byte, 'rac_wasm_offsetof_http_download_request_resume_from_byte')();
  m.setValue(ptr + offResume, (req.resumeFromByte ?? 0) & 0xffffffff, 'i32');
  m.setValue(ptr + offResume + 4, 0, 'i32');

  if (req.expectedSha256Hex) {
    m.setValue(ptr + required(m._rac_wasm_offsetof_http_download_request_expected_sha256_hex, 'rac_wasm_offsetof_http_download_request_expected_sha256_hex')(),
      scope.allocString(req.expectedSha256Hex), '*');
  }

  return ptr;
}
