/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_runanywhere_sdk_components_stt_WhisperJNI */

#ifndef _Included_com_runanywhere_sdk_components_stt_WhisperJNI
#define _Included_com_runanywhere_sdk_components_stt_WhisperJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    whisperInit
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_whisperInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    whisperInitFromBuffer
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_whisperInitFromBuffer
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    whisperFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_whisperFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    whisperGetModelInfo
 * Signature: (J)Lcom/runanywhere/sdk/components/stt/WhisperModelInfo;
 */
JNIEXPORT jobject JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_whisperGetModelInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    whisperTranscribe
 * Signature: (J[FLjava/lang/String;ZZ)Lcom/runanywhere/sdk/components/stt/WhisperResult;
 */
JNIEXPORT jobject JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_whisperTranscribe
  (JNIEnv *, jclass, jlong, jfloatArray, jstring, jboolean, jboolean);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    whisperTranscribeWithParams
 * Signature: (J[FLcom/runanywhere/sdk/components/stt/WhisperParams;)Lcom/runanywhere/sdk/components/stt/WhisperResult;
 */
JNIEXPORT jobject JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_whisperTranscribeWithParams
  (JNIEnv *, jclass, jlong, jfloatArray, jobject);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    whisperGetLanguageCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_whisperGetLanguageCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    whisperGetLanguageProbs
 * Signature: (J)[Lcom/runanywhere/sdk/components/stt/WhisperLanguageProb;
 */
JNIEXPORT jobjectArray JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_whisperGetLanguageProbs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    convertPcmToFloat
 * Signature: ([BII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_convertPcmToFloat
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    isGpuAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_isGpuAvailable
  (JNIEnv *, jclass);

/*
 * Class:     com_runanywhere_sdk_components_stt_WhisperJNI
 * Method:    setGpuAcceleration
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_runanywhere_sdk_components_stt_WhisperJNI_setGpuAcceleration
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
