/**
 * HybridRunAnywhereCore.hpp
 *
 * Nitrogen HybridObject implementation for RunAnywhere Core SDK.
 * This single C++ file works on both iOS and Android.
 *
 * Core-only implementation - includes:
 * - SDK Lifecycle (init, destroy)
 * - Authentication
 * - Device Registration
 * - Model Registry
 * - Download Service
 * - Storage
 * - Events
 * - HTTP Client
 * - Utilities
 *
 * NO LLM/STT/TTS/VAD/VoiceAgent methods - those are in separate packages:
 * - @runanywhere/llamacpp for text generation
 * - @runanywhere/onnx for speech processing
 *
 * The HybridRunAnywhereCoreSpec base class is auto-generated by Nitrogen
 * from src/specs/RunAnywhereCore.nitro.ts
 */

#pragma once

// Include the generated spec header (created by nitrogen)
#if __has_include(<NitroModules/HybridObject.hpp>)
#include "HybridRunAnywhereCoreSpec.hpp"
#else
// Fallback include path during development
#include "../nitrogen/generated/shared/c++/HybridRunAnywhereCoreSpec.hpp"
#endif

#include <mutex>
#include <string>

namespace margelo::nitro::runanywhere {

/**
 * HybridRunAnywhereCore - Core SDK native implementation
 *
 * Implements the RunAnywhereCore interface defined in RunAnywhereCore.nitro.ts
 * Delegates to modular bridges that call runanywhere-commons rac_* API.
 */
class HybridRunAnywhereCore : public HybridRunAnywhereCoreSpec {
public:
  HybridRunAnywhereCore();
  ~HybridRunAnywhereCore();

  // ============================================================================
  // SDK Lifecycle
  // ============================================================================

  std::shared_ptr<Promise<bool>> initialize(const std::string& configJson) override;
  std::shared_ptr<Promise<void>> destroy() override;
  std::shared_ptr<Promise<bool>> isInitialized() override;
  std::shared_ptr<Promise<std::string>> getBackendInfo() override;

  // ============================================================================
  // Authentication - Delegates to AuthBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> authenticate(const std::string& apiKey) override;
  std::shared_ptr<Promise<bool>> isAuthenticated() override;
  std::shared_ptr<Promise<std::string>> getUserId() override;
  std::shared_ptr<Promise<std::string>> getOrganizationId() override;

  // ============================================================================
  // Device Registration - Delegates to DeviceBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> registerDevice(const std::string& environmentJson) override;
  std::shared_ptr<Promise<bool>> isDeviceRegistered() override;
  std::shared_ptr<Promise<std::string>> getDeviceId() override;

  // ============================================================================
  // Model Registry - Delegates to ModelRegistryBridge
  // ============================================================================

  std::shared_ptr<Promise<std::string>> getAvailableModels() override;
  std::shared_ptr<Promise<std::string>> getModelInfo(const std::string& modelId) override;
  std::shared_ptr<Promise<bool>> isModelDownloaded(const std::string& modelId) override;
  std::shared_ptr<Promise<std::string>> getModelPath(const std::string& modelId) override;
  std::shared_ptr<Promise<bool>> registerModel(const std::string& modelJson) override;

  // ============================================================================
  // Download Service - Delegates to DownloadBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> downloadModel(
    const std::string& modelId,
    const std::string& url,
    const std::string& destPath) override;
  std::shared_ptr<Promise<bool>> cancelDownload(const std::string& modelId) override;
  std::shared_ptr<Promise<std::string>> getDownloadProgress(const std::string& modelId) override;

  // ============================================================================
  // Storage - Delegates to StorageBridge
  // ============================================================================

  std::shared_ptr<Promise<std::string>> getStorageInfo() override;
  std::shared_ptr<Promise<bool>> clearCache() override;
  std::shared_ptr<Promise<bool>> deleteModel(const std::string& modelId) override;

  // ============================================================================
  // Events - Delegates to EventBridge
  // ============================================================================

  std::shared_ptr<Promise<void>> emitEvent(const std::string& eventJson) override;
  std::shared_ptr<Promise<std::string>> pollEvents() override;

  // ============================================================================
  // HTTP Client - Delegates to HTTPBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> configureHttp(
    const std::string& baseUrl,
    const std::string& apiKey) override;
  std::shared_ptr<Promise<std::string>> httpPost(
    const std::string& path,
    const std::string& bodyJson) override;
  std::shared_ptr<Promise<std::string>> httpGet(const std::string& path) override;

  // ============================================================================
  // Utility Functions
  // ============================================================================

  std::shared_ptr<Promise<std::string>> getLastError() override;
  std::shared_ptr<Promise<bool>> extractArchive(
    const std::string& archivePath,
    const std::string& destPath) override;
  std::shared_ptr<Promise<std::string>> getDeviceCapabilities() override;
  std::shared_ptr<Promise<double>> getMemoryUsage() override;

private:
  // Thread safety
  std::mutex initMutex_;

  // State tracking
  std::string lastError_;

  // Helper methods
  void setLastError(const std::string& error);
};

} // namespace margelo::nitro::runanywhere
