// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: device_info.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "runanywhere.v1";

/**
 * Host OS family. Closed set — a producer that cannot classify itself sends
 * PLATFORM_UNSPECIFIED rather than inventing a spelling.
 */
export enum Platform {
  PLATFORM_UNSPECIFIED = 0,
  PLATFORM_IOS = 1,
  PLATFORM_ANDROID = 2,
  PLATFORM_MACOS = 3,
  PLATFORM_WEB = 4,
  PLATFORM_LINUX = 5,
  PLATFORM_WINDOWS = 6,
  PLATFORM_TVOS = 7,
  PLATFORM_WATCHOS = 8,
  PLATFORM_VISIONOS = 9,
  UNRECOGNIZED = -1,
}

export function platformFromJSON(object: any): Platform {
  switch (object) {
    case 0:
    case "PLATFORM_UNSPECIFIED":
      return Platform.PLATFORM_UNSPECIFIED;
    case 1:
    case "PLATFORM_IOS":
      return Platform.PLATFORM_IOS;
    case 2:
    case "PLATFORM_ANDROID":
      return Platform.PLATFORM_ANDROID;
    case 3:
    case "PLATFORM_MACOS":
      return Platform.PLATFORM_MACOS;
    case 4:
    case "PLATFORM_WEB":
      return Platform.PLATFORM_WEB;
    case 5:
    case "PLATFORM_LINUX":
      return Platform.PLATFORM_LINUX;
    case 6:
    case "PLATFORM_WINDOWS":
      return Platform.PLATFORM_WINDOWS;
    case 7:
    case "PLATFORM_TVOS":
      return Platform.PLATFORM_TVOS;
    case 8:
    case "PLATFORM_WATCHOS":
      return Platform.PLATFORM_WATCHOS;
    case 9:
    case "PLATFORM_VISIONOS":
      return Platform.PLATFORM_VISIONOS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Platform.UNRECOGNIZED;
  }
}

export function platformToJSON(object: Platform): string {
  switch (object) {
    case Platform.PLATFORM_UNSPECIFIED:
      return "PLATFORM_UNSPECIFIED";
    case Platform.PLATFORM_IOS:
      return "PLATFORM_IOS";
    case Platform.PLATFORM_ANDROID:
      return "PLATFORM_ANDROID";
    case Platform.PLATFORM_MACOS:
      return "PLATFORM_MACOS";
    case Platform.PLATFORM_WEB:
      return "PLATFORM_WEB";
    case Platform.PLATFORM_LINUX:
      return "PLATFORM_LINUX";
    case Platform.PLATFORM_WINDOWS:
      return "PLATFORM_WINDOWS";
    case Platform.PLATFORM_TVOS:
      return "PLATFORM_TVOS";
    case Platform.PLATFORM_WATCHOS:
      return "PLATFORM_WATCHOS";
    case Platform.PLATFORM_VISIONOS:
      return "PLATFORM_VISIONOS";
    case Platform.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Physical device class. */
export enum FormFactor {
  /** FORM_FACTOR_UNSPECIFIED - replaces the hand-written "unknown" token */
  FORM_FACTOR_UNSPECIFIED = 0,
  FORM_FACTOR_PHONE = 1,
  FORM_FACTOR_TABLET = 2,
  FORM_FACTOR_DESKTOP = 3,
  FORM_FACTOR_LAPTOP = 4,
  FORM_FACTOR_TV = 5,
  FORM_FACTOR_WATCH = 6,
  FORM_FACTOR_HEADSET = 7,
  UNRECOGNIZED = -1,
}

export function formFactorFromJSON(object: any): FormFactor {
  switch (object) {
    case 0:
    case "FORM_FACTOR_UNSPECIFIED":
      return FormFactor.FORM_FACTOR_UNSPECIFIED;
    case 1:
    case "FORM_FACTOR_PHONE":
      return FormFactor.FORM_FACTOR_PHONE;
    case 2:
    case "FORM_FACTOR_TABLET":
      return FormFactor.FORM_FACTOR_TABLET;
    case 3:
    case "FORM_FACTOR_DESKTOP":
      return FormFactor.FORM_FACTOR_DESKTOP;
    case 4:
    case "FORM_FACTOR_LAPTOP":
      return FormFactor.FORM_FACTOR_LAPTOP;
    case 5:
    case "FORM_FACTOR_TV":
      return FormFactor.FORM_FACTOR_TV;
    case 6:
    case "FORM_FACTOR_WATCH":
      return FormFactor.FORM_FACTOR_WATCH;
    case 7:
    case "FORM_FACTOR_HEADSET":
      return FormFactor.FORM_FACTOR_HEADSET;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FormFactor.UNRECOGNIZED;
  }
}

export function formFactorToJSON(object: FormFactor): string {
  switch (object) {
    case FormFactor.FORM_FACTOR_UNSPECIFIED:
      return "FORM_FACTOR_UNSPECIFIED";
    case FormFactor.FORM_FACTOR_PHONE:
      return "FORM_FACTOR_PHONE";
    case FormFactor.FORM_FACTOR_TABLET:
      return "FORM_FACTOR_TABLET";
    case FormFactor.FORM_FACTOR_DESKTOP:
      return "FORM_FACTOR_DESKTOP";
    case FormFactor.FORM_FACTOR_LAPTOP:
      return "FORM_FACTOR_LAPTOP";
    case FormFactor.FORM_FACTOR_TV:
      return "FORM_FACTOR_TV";
    case FormFactor.FORM_FACTOR_WATCH:
      return "FORM_FACTOR_WATCH";
    case FormFactor.FORM_FACTOR_HEADSET:
      return "FORM_FACTOR_HEADSET";
    case FormFactor.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Charging state of the main battery. */
export enum BatteryState {
  /** BATTERY_STATE_UNSPECIFIED - unreadable (desktop, tvOS, browser) */
  BATTERY_STATE_UNSPECIFIED = 0,
  BATTERY_STATE_CHARGING = 1,
  BATTERY_STATE_UNPLUGGED = 2,
  BATTERY_STATE_FULL = 3,
  UNRECOGNIZED = -1,
}

export function batteryStateFromJSON(object: any): BatteryState {
  switch (object) {
    case 0:
    case "BATTERY_STATE_UNSPECIFIED":
      return BatteryState.BATTERY_STATE_UNSPECIFIED;
    case 1:
    case "BATTERY_STATE_CHARGING":
      return BatteryState.BATTERY_STATE_CHARGING;
    case 2:
    case "BATTERY_STATE_UNPLUGGED":
      return BatteryState.BATTERY_STATE_UNPLUGGED;
    case 3:
    case "BATTERY_STATE_FULL":
      return BatteryState.BATTERY_STATE_FULL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BatteryState.UNRECOGNIZED;
  }
}

export function batteryStateToJSON(object: BatteryState): string {
  switch (object) {
    case BatteryState.BATTERY_STATE_UNSPECIFIED:
      return "BATTERY_STATE_UNSPECIFIED";
    case BatteryState.BATTERY_STATE_CHARGING:
      return "BATTERY_STATE_CHARGING";
    case BatteryState.BATTERY_STATE_UNPLUGGED:
      return "BATTERY_STATE_UNPLUGGED";
    case BatteryState.BATTERY_STATE_FULL:
      return "BATTERY_STATE_FULL";
    case BatteryState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface DeviceInfo {
  /** e.g. "iPhone16,2", "Pixel 8 Pro". */
  deviceModel: string;
  platform: Platform;
  osVersion: string;
  formFactor: FormFactor;
  /**
   * ABI name as the OS reports it: Android sends Build.SUPPORTED_ABIS[0]
   * ("arm64-v8a"), Apple "arm64", Web "wasm32". Kept a string because no
   * industry API enumerates ABIs — but the spelling is the OS's, not ours.
   */
  architecture: string;
  /** e.g. "Apple A17 Pro". */
  chipName: string;
  /**
   * Physical RAM installed, in BYTES. Never the JVM heap cap — Android must
   * read ActivityManager.MemoryInfo.totalMem, not Runtime.maxMemory().
   */
  totalMemoryBytes: number;
  /**
   * Free + reclaimable system RAM at snapshot time, in BYTES.
   * 0 = UNKNOWN (the Web producer cannot read it). A consumer MUST NOT read
   * 0 as "no memory left" and refuse to load.
   */
  availableMemoryBytes: number;
  /** Dedicated neural accelerator present (ANE, Hexagon, APU, ...). */
  hasNpu: boolean;
  /** 0 = none OR present-but-unreported. */
  npuCores: number;
  gpuFamily: string;
  /**
   * Remaining charge as a fraction of full. ABSENT is the ONLY encoding of
   * "unknown" — 0.0 means a flat battery, not an unreadable one. Producers
   * bridging through rac_device_registration_info_t (which uses a negative
   * sentinel) MUST map negative -> absent, never negative -> 0.
   */
  batteryLevel?:
    | number
    | undefined;
  /**
   * ABSENT when the platform reports no battery at all; UNSPECIFIED when a
   * battery exists but its state could not be read. The C ABI member is
   * documented NULL-if-unavailable, which is why this stays `optional`.
   */
  batteryState?: BatteryState | undefined;
  isLowPowerMode: boolean;
  coreCount: number;
  performanceCores: number;
  deviceFingerprint?:
    | string
    | undefined;
  /**
   * Vendor escape hatch, CLOSED key set:
   *   android: "manufacturer", "device_id", "os_build_id", "sdk_version",
   *            "android_api_level", "locale", "timezone"
   *   web:     "has_webgpu", "has_shared_array_buffer"
   *
   * "manufacturer" and "device_id" are the only two the native parser reads
   * ("device_id" arrives as a promoted top-level JSON key). Keys not listed
   * here are NOT dropped: the Kotlin serializer flattens them into the
   * outbound registration body verbatim, where no client code reads them.
   *
   * A key that restates a typed field above MUST NOT be sent — "device_type",
   * "os_name", "processor_count" and "is_simulator" were removed for exactly
   * that reason, and "device_id" duplicates device_fingerprint and should
   * follow once the native parser reads the typed field instead.
   *
   * Values are always strings. This map does not cross the C ABI on Apple
   * platforms, so nothing load-bearing may live here.
   */
  platformExtras: { [key: string]: string };
}

export interface DeviceInfo_PlatformExtrasEntry {
  key: string;
  value: string;
}

function createBaseDeviceInfo(): DeviceInfo {
  return {
    deviceModel: "",
    platform: 0,
    osVersion: "",
    formFactor: 0,
    architecture: "",
    chipName: "",
    totalMemoryBytes: 0,
    availableMemoryBytes: 0,
    hasNpu: false,
    npuCores: 0,
    gpuFamily: "",
    batteryLevel: undefined,
    batteryState: undefined,
    isLowPowerMode: false,
    coreCount: 0,
    performanceCores: 0,
    deviceFingerprint: undefined,
    platformExtras: {},
  };
}

export const DeviceInfo: MessageFns<DeviceInfo> = {
  encode(message: DeviceInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deviceModel !== "") {
      writer.uint32(10).string(message.deviceModel);
    }
    if (message.platform !== 0) {
      writer.uint32(16).int32(message.platform);
    }
    if (message.osVersion !== "") {
      writer.uint32(26).string(message.osVersion);
    }
    if (message.formFactor !== 0) {
      writer.uint32(32).int32(message.formFactor);
    }
    if (message.architecture !== "") {
      writer.uint32(42).string(message.architecture);
    }
    if (message.chipName !== "") {
      writer.uint32(50).string(message.chipName);
    }
    if (message.totalMemoryBytes !== 0) {
      writer.uint32(56).int64(message.totalMemoryBytes);
    }
    if (message.availableMemoryBytes !== 0) {
      writer.uint32(64).int64(message.availableMemoryBytes);
    }
    if (message.hasNpu !== false) {
      writer.uint32(72).bool(message.hasNpu);
    }
    if (message.npuCores !== 0) {
      writer.uint32(80).int32(message.npuCores);
    }
    if (message.gpuFamily !== "") {
      writer.uint32(90).string(message.gpuFamily);
    }
    if (message.batteryLevel !== undefined) {
      writer.uint32(101).float(message.batteryLevel);
    }
    if (message.batteryState !== undefined) {
      writer.uint32(104).int32(message.batteryState);
    }
    if (message.isLowPowerMode !== false) {
      writer.uint32(112).bool(message.isLowPowerMode);
    }
    if (message.coreCount !== 0) {
      writer.uint32(120).int32(message.coreCount);
    }
    if (message.performanceCores !== 0) {
      writer.uint32(128).int32(message.performanceCores);
    }
    if (message.deviceFingerprint !== undefined) {
      writer.uint32(138).string(message.deviceFingerprint);
    }
    globalThis.Object.entries(message.platformExtras).forEach(([key, value]: [string, string]) => {
      DeviceInfo_PlatformExtrasEntry.encode({ key: key as any, value }, writer.uint32(146).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deviceModel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.platform = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.osVersion = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.formFactor = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.architecture = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.chipName = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalMemoryBytes = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.availableMemoryBytes = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.hasNpu = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.npuCores = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.gpuFamily = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 101) {
            break;
          }

          message.batteryLevel = reader.float();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.batteryState = reader.int32() as any;
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.isLowPowerMode = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.coreCount = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.performanceCores = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.deviceFingerprint = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          const entry18 = DeviceInfo_PlatformExtrasEntry.decode(reader, reader.uint32());
          if (entry18.value !== undefined) {
            message.platformExtras[entry18.key] = entry18.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceInfo {
    return {
      deviceModel: isSet(object.deviceModel)
        ? globalThis.String(object.deviceModel)
        : isSet(object.device_model)
        ? globalThis.String(object.device_model)
        : "",
      platform: isSet(object.platform) ? platformFromJSON(object.platform) : 0,
      osVersion: isSet(object.osVersion)
        ? globalThis.String(object.osVersion)
        : isSet(object.os_version)
        ? globalThis.String(object.os_version)
        : "",
      formFactor: isSet(object.formFactor)
        ? formFactorFromJSON(object.formFactor)
        : isSet(object.form_factor)
        ? formFactorFromJSON(object.form_factor)
        : 0,
      architecture: isSet(object.architecture) ? globalThis.String(object.architecture) : "",
      chipName: isSet(object.chipName)
        ? globalThis.String(object.chipName)
        : isSet(object.chip_name)
        ? globalThis.String(object.chip_name)
        : "",
      totalMemoryBytes: isSet(object.totalMemoryBytes)
        ? globalThis.Number(object.totalMemoryBytes)
        : isSet(object.total_memory_bytes)
        ? globalThis.Number(object.total_memory_bytes)
        : 0,
      availableMemoryBytes: isSet(object.availableMemoryBytes)
        ? globalThis.Number(object.availableMemoryBytes)
        : isSet(object.available_memory_bytes)
        ? globalThis.Number(object.available_memory_bytes)
        : 0,
      hasNpu: isSet(object.hasNpu)
        ? globalThis.Boolean(object.hasNpu)
        : isSet(object.has_npu)
        ? globalThis.Boolean(object.has_npu)
        : false,
      npuCores: isSet(object.npuCores)
        ? globalThis.Number(object.npuCores)
        : isSet(object.npu_cores)
        ? globalThis.Number(object.npu_cores)
        : 0,
      gpuFamily: isSet(object.gpuFamily)
        ? globalThis.String(object.gpuFamily)
        : isSet(object.gpu_family)
        ? globalThis.String(object.gpu_family)
        : "",
      batteryLevel: isSet(object.batteryLevel)
        ? globalThis.Number(object.batteryLevel)
        : isSet(object.battery_level)
        ? globalThis.Number(object.battery_level)
        : undefined,
      batteryState: isSet(object.batteryState)
        ? batteryStateFromJSON(object.batteryState)
        : isSet(object.battery_state)
        ? batteryStateFromJSON(object.battery_state)
        : undefined,
      isLowPowerMode: isSet(object.isLowPowerMode)
        ? globalThis.Boolean(object.isLowPowerMode)
        : isSet(object.is_low_power_mode)
        ? globalThis.Boolean(object.is_low_power_mode)
        : false,
      coreCount: isSet(object.coreCount)
        ? globalThis.Number(object.coreCount)
        : isSet(object.core_count)
        ? globalThis.Number(object.core_count)
        : 0,
      performanceCores: isSet(object.performanceCores)
        ? globalThis.Number(object.performanceCores)
        : isSet(object.performance_cores)
        ? globalThis.Number(object.performance_cores)
        : 0,
      deviceFingerprint: isSet(object.deviceFingerprint)
        ? globalThis.String(object.deviceFingerprint)
        : isSet(object.device_fingerprint)
        ? globalThis.String(object.device_fingerprint)
        : undefined,
      platformExtras: isObject(object.platformExtras)
        ? (globalThis.Object.entries(object.platformExtras) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.platform_extras)
        ? (globalThis.Object.entries(object.platform_extras) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: DeviceInfo): unknown {
    const obj: any = {};
    if (message.deviceModel !== "") {
      obj.deviceModel = message.deviceModel;
    }
    if (message.platform !== 0) {
      obj.platform = platformToJSON(message.platform);
    }
    if (message.osVersion !== "") {
      obj.osVersion = message.osVersion;
    }
    if (message.formFactor !== 0) {
      obj.formFactor = formFactorToJSON(message.formFactor);
    }
    if (message.architecture !== "") {
      obj.architecture = message.architecture;
    }
    if (message.chipName !== "") {
      obj.chipName = message.chipName;
    }
    if (message.totalMemoryBytes !== 0) {
      obj.totalMemoryBytes = Math.round(message.totalMemoryBytes);
    }
    if (message.availableMemoryBytes !== 0) {
      obj.availableMemoryBytes = Math.round(message.availableMemoryBytes);
    }
    if (message.hasNpu !== false) {
      obj.hasNpu = message.hasNpu;
    }
    if (message.npuCores !== 0) {
      obj.npuCores = Math.round(message.npuCores);
    }
    if (message.gpuFamily !== "") {
      obj.gpuFamily = message.gpuFamily;
    }
    if (message.batteryLevel !== undefined) {
      obj.batteryLevel = message.batteryLevel;
    }
    if (message.batteryState !== undefined) {
      obj.batteryState = batteryStateToJSON(message.batteryState);
    }
    if (message.isLowPowerMode !== false) {
      obj.isLowPowerMode = message.isLowPowerMode;
    }
    if (message.coreCount !== 0) {
      obj.coreCount = Math.round(message.coreCount);
    }
    if (message.performanceCores !== 0) {
      obj.performanceCores = Math.round(message.performanceCores);
    }
    if (message.deviceFingerprint !== undefined) {
      obj.deviceFingerprint = message.deviceFingerprint;
    }
    if (message.platformExtras) {
      const entries = globalThis.Object.entries(message.platformExtras) as [string, string][];
      if (entries.length > 0) {
        obj.platformExtras = {};
        entries.forEach(([k, v]) => {
          obj.platformExtras[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceInfo>, I>>(base?: I): DeviceInfo {
    return DeviceInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceInfo>, I>>(object: I): DeviceInfo {
    const message = createBaseDeviceInfo();
    message.deviceModel = object.deviceModel ?? "";
    message.platform = object.platform ?? 0;
    message.osVersion = object.osVersion ?? "";
    message.formFactor = object.formFactor ?? 0;
    message.architecture = object.architecture ?? "";
    message.chipName = object.chipName ?? "";
    message.totalMemoryBytes = object.totalMemoryBytes ?? 0;
    message.availableMemoryBytes = object.availableMemoryBytes ?? 0;
    message.hasNpu = object.hasNpu ?? false;
    message.npuCores = object.npuCores ?? 0;
    message.gpuFamily = object.gpuFamily ?? "";
    message.batteryLevel = object.batteryLevel ?? undefined;
    message.batteryState = object.batteryState ?? undefined;
    message.isLowPowerMode = object.isLowPowerMode ?? false;
    message.coreCount = object.coreCount ?? 0;
    message.performanceCores = object.performanceCores ?? 0;
    message.deviceFingerprint = object.deviceFingerprint ?? undefined;
    message.platformExtras = (globalThis.Object.entries(object.platformExtras ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDeviceInfo_PlatformExtrasEntry(): DeviceInfo_PlatformExtrasEntry {
  return { key: "", value: "" };
}

export const DeviceInfo_PlatformExtrasEntry: MessageFns<DeviceInfo_PlatformExtrasEntry> = {
  encode(message: DeviceInfo_PlatformExtrasEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceInfo_PlatformExtrasEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceInfo_PlatformExtrasEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceInfo_PlatformExtrasEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: DeviceInfo_PlatformExtrasEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceInfo_PlatformExtrasEntry>, I>>(base?: I): DeviceInfo_PlatformExtrasEntry {
    return DeviceInfo_PlatformExtrasEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceInfo_PlatformExtrasEntry>, I>>(
    object: I,
  ): DeviceInfo_PlatformExtrasEntry {
    const message = createBaseDeviceInfo_PlatformExtrasEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
