// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: diffusion_options.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SDKError } from "./errors";

export const protobufPackage = "runanywhere.v1";

/**
 * Only values with a C carrier are listed. UNSPECIFIED = the model's
 * configured scheduler, which is what every engine does.
 */
export enum DiffusionScheduler {
  DIFFUSION_SCHEDULER_UNSPECIFIED = 0,
  DIFFUSION_SCHEDULER_DPMPP_2M = 1,
  /** DIFFUSION_SCHEDULER_DPMPP_2M_KARRAS - recommended default */
  DIFFUSION_SCHEDULER_DPMPP_2M_KARRAS = 2,
  DIFFUSION_SCHEDULER_DDIM = 3,
  DIFFUSION_SCHEDULER_EULER = 4,
  /** DIFFUSION_SCHEDULER_EULER_A - Euler Ancestral */
  DIFFUSION_SCHEDULER_EULER_A = 5,
  DIFFUSION_SCHEDULER_PNDM = 6,
  DIFFUSION_SCHEDULER_LMS = 7,
  DIFFUSION_SCHEDULER_DPMPP_2M_SDE = 8,
  UNRECOGNIZED = -1,
}

export function diffusionSchedulerFromJSON(object: any): DiffusionScheduler {
  switch (object) {
    case 0:
    case "DIFFUSION_SCHEDULER_UNSPECIFIED":
      return DiffusionScheduler.DIFFUSION_SCHEDULER_UNSPECIFIED;
    case 1:
    case "DIFFUSION_SCHEDULER_DPMPP_2M":
      return DiffusionScheduler.DIFFUSION_SCHEDULER_DPMPP_2M;
    case 2:
    case "DIFFUSION_SCHEDULER_DPMPP_2M_KARRAS":
      return DiffusionScheduler.DIFFUSION_SCHEDULER_DPMPP_2M_KARRAS;
    case 3:
    case "DIFFUSION_SCHEDULER_DDIM":
      return DiffusionScheduler.DIFFUSION_SCHEDULER_DDIM;
    case 4:
    case "DIFFUSION_SCHEDULER_EULER":
      return DiffusionScheduler.DIFFUSION_SCHEDULER_EULER;
    case 5:
    case "DIFFUSION_SCHEDULER_EULER_A":
      return DiffusionScheduler.DIFFUSION_SCHEDULER_EULER_A;
    case 6:
    case "DIFFUSION_SCHEDULER_PNDM":
      return DiffusionScheduler.DIFFUSION_SCHEDULER_PNDM;
    case 7:
    case "DIFFUSION_SCHEDULER_LMS":
      return DiffusionScheduler.DIFFUSION_SCHEDULER_LMS;
    case 8:
    case "DIFFUSION_SCHEDULER_DPMPP_2M_SDE":
      return DiffusionScheduler.DIFFUSION_SCHEDULER_DPMPP_2M_SDE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DiffusionScheduler.UNRECOGNIZED;
  }
}

export function diffusionSchedulerToJSON(object: DiffusionScheduler): string {
  switch (object) {
    case DiffusionScheduler.DIFFUSION_SCHEDULER_UNSPECIFIED:
      return "DIFFUSION_SCHEDULER_UNSPECIFIED";
    case DiffusionScheduler.DIFFUSION_SCHEDULER_DPMPP_2M:
      return "DIFFUSION_SCHEDULER_DPMPP_2M";
    case DiffusionScheduler.DIFFUSION_SCHEDULER_DPMPP_2M_KARRAS:
      return "DIFFUSION_SCHEDULER_DPMPP_2M_KARRAS";
    case DiffusionScheduler.DIFFUSION_SCHEDULER_DDIM:
      return "DIFFUSION_SCHEDULER_DDIM";
    case DiffusionScheduler.DIFFUSION_SCHEDULER_EULER:
      return "DIFFUSION_SCHEDULER_EULER";
    case DiffusionScheduler.DIFFUSION_SCHEDULER_EULER_A:
      return "DIFFUSION_SCHEDULER_EULER_A";
    case DiffusionScheduler.DIFFUSION_SCHEDULER_PNDM:
      return "DIFFUSION_SCHEDULER_PNDM";
    case DiffusionScheduler.DIFFUSION_SCHEDULER_LMS:
      return "DIFFUSION_SCHEDULER_LMS";
    case DiffusionScheduler.DIFFUSION_SCHEDULER_DPMPP_2M_SDE:
      return "DIFFUSION_SCHEDULER_DPMPP_2M_SDE";
    case DiffusionScheduler.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Encoding of the returned image bytes. */
export enum DiffusionOutputFormat {
  /** DIFFUSION_OUTPUT_FORMAT_UNSPECIFIED - = PNG */
  DIFFUSION_OUTPUT_FORMAT_UNSPECIFIED = 0,
  DIFFUSION_OUTPUT_FORMAT_PNG = 1,
  /**
   * DIFFUSION_OUTPUT_FORMAT_JPEG - No JPEG or WEBP encoder exists in this tree yet. Requesting one is
   * rejected outright; it is never silently answered with PNG.
   */
  DIFFUSION_OUTPUT_FORMAT_JPEG = 2,
  DIFFUSION_OUTPUT_FORMAT_WEBP = 3,
  /** DIFFUSION_OUTPUT_FORMAT_RAW_RGBA - Escape hatch: no encode, 4 bytes per pixel, "image/raw-rgba". */
  DIFFUSION_OUTPUT_FORMAT_RAW_RGBA = 4,
  UNRECOGNIZED = -1,
}

export function diffusionOutputFormatFromJSON(object: any): DiffusionOutputFormat {
  switch (object) {
    case 0:
    case "DIFFUSION_OUTPUT_FORMAT_UNSPECIFIED":
      return DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_UNSPECIFIED;
    case 1:
    case "DIFFUSION_OUTPUT_FORMAT_PNG":
      return DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_PNG;
    case 2:
    case "DIFFUSION_OUTPUT_FORMAT_JPEG":
      return DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_JPEG;
    case 3:
    case "DIFFUSION_OUTPUT_FORMAT_WEBP":
      return DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_WEBP;
    case 4:
    case "DIFFUSION_OUTPUT_FORMAT_RAW_RGBA":
      return DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_RAW_RGBA;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DiffusionOutputFormat.UNRECOGNIZED;
  }
}

export function diffusionOutputFormatToJSON(object: DiffusionOutputFormat): string {
  switch (object) {
    case DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_UNSPECIFIED:
      return "DIFFUSION_OUTPUT_FORMAT_UNSPECIFIED";
    case DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_PNG:
      return "DIFFUSION_OUTPUT_FORMAT_PNG";
    case DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_JPEG:
      return "DIFFUSION_OUTPUT_FORMAT_JPEG";
    case DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_WEBP:
      return "DIFFUSION_OUTPUT_FORMAT_WEBP";
    case DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_RAW_RGBA:
      return "DIFFUSION_OUTPUT_FORMAT_RAW_RGBA";
    case DiffusionOutputFormat.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum DiffusionStreamEventKind {
  DIFFUSION_STREAM_EVENT_KIND_UNSPECIFIED = 0,
  DIFFUSION_STREAM_EVENT_KIND_STARTED = 1,
  DIFFUSION_STREAM_EVENT_KIND_PROGRESS = 2,
  DIFFUSION_STREAM_EVENT_KIND_INTERMEDIATE_IMAGE = 3,
  DIFFUSION_STREAM_EVENT_KIND_COMPLETED = 4,
  DIFFUSION_STREAM_EVENT_KIND_ERROR = 5,
  UNRECOGNIZED = -1,
}

export function diffusionStreamEventKindFromJSON(object: any): DiffusionStreamEventKind {
  switch (object) {
    case 0:
    case "DIFFUSION_STREAM_EVENT_KIND_UNSPECIFIED":
      return DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_UNSPECIFIED;
    case 1:
    case "DIFFUSION_STREAM_EVENT_KIND_STARTED":
      return DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_STARTED;
    case 2:
    case "DIFFUSION_STREAM_EVENT_KIND_PROGRESS":
      return DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_PROGRESS;
    case 3:
    case "DIFFUSION_STREAM_EVENT_KIND_INTERMEDIATE_IMAGE":
      return DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_INTERMEDIATE_IMAGE;
    case 4:
    case "DIFFUSION_STREAM_EVENT_KIND_COMPLETED":
      return DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_COMPLETED;
    case 5:
    case "DIFFUSION_STREAM_EVENT_KIND_ERROR":
      return DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DiffusionStreamEventKind.UNRECOGNIZED;
  }
}

export function diffusionStreamEventKindToJSON(object: DiffusionStreamEventKind): string {
  switch (object) {
    case DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_UNSPECIFIED:
      return "DIFFUSION_STREAM_EVENT_KIND_UNSPECIFIED";
    case DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_STARTED:
      return "DIFFUSION_STREAM_EVENT_KIND_STARTED";
    case DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_PROGRESS:
      return "DIFFUSION_STREAM_EVENT_KIND_PROGRESS";
    case DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_INTERMEDIATE_IMAGE:
      return "DIFFUSION_STREAM_EVENT_KIND_INTERMEDIATE_IMAGE";
    case DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_COMPLETED:
      return "DIFFUSION_STREAM_EVENT_KIND_COMPLETED";
    case DiffusionStreamEventKind.DIFFUSION_STREAM_EVENT_KIND_ERROR:
      return "DIFFUSION_STREAM_EVENT_KIND_ERROR";
    case DiffusionStreamEventKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface DiffusionGenerationOptions {
  prompt: string;
  negativePrompt: string;
  /** 0 = backend default, for width, height, steps, and guidance_scale. */
  width: number;
  height: number;
  steps: number;
  guidanceScale: number;
  /**
   * Absent = pick a fresh random seed. Any present value is literal,
   * including 0. The seed actually used comes back on each result image.
   */
  seed?: number | undefined;
  scheduler: DiffusionScheduler;
  /**
   * Source picture. Its presence promotes the request to image-to-image;
   * adding `mask_image` promotes it to inpainting. Must be an encoded
   * PNG or JPEG container.
   */
  image?:
    | Uint8Array
    | undefined;
  /** White = repaint. Same dimensions as `image`. */
  maskImage?:
    | Uint8Array
    | undefined;
  /**
   * How far from the source image to travel. Only meaningful with `image`.
   * Effective steps = ceil(steps * strength), so a low value is
   * proportionally cheaper -- on device that is battery.
   */
  strength: number;
  /**
   * Container of the bytes above, as supplied by the caller. Request-side;
   * the result carries its own media type per image.
   */
  imageMediaType?: string | undefined;
  maskImageMediaType?:
    | string
    | undefined;
  /** How many images to generate for this prompt. Absent = 1. */
  n?:
    | number
    | undefined;
  /** Encoding of the returned image bytes. */
  outputFormat: DiffusionOutputFormat;
}

export interface DiffusionGenerationRequest {
  options?: DiffusionGenerationOptions | undefined;
  modelId?: string | undefined;
}

export interface DiffusionProgress {
  currentStep: number;
  /** as resolved by the backend */
  totalSteps: number;
  intermediateImageData?: Uint8Array | undefined;
}

/**
 * One generated image. Per-image, because with n > 1 each image has its
 * own seed and its own safety verdict (Stability `seeds`/`finish_reasons`,
 * Diffusers `nsfw_content_detected`).
 */
export interface DiffusionImage {
  data: Uint8Array;
  /** resolved, echoed back */
  width: number;
  height: number;
  /** so "make more like that one" works */
  seedUsed: number;
  /** advisory, in-band, never an error */
  safetyFlag: boolean;
  /** resolved output_format, e.g. "image/png" */
  mediaType: string;
}

export interface DiffusionResult {
  /**
   * One entry per requested image, in request order. commons emits exactly
   * one entry until the C ABI grows a list: rac_diffusion_result_t is a
   * single-image struct with one image_data/image_size pair.
   */
  images: DiffusionImage[];
  totalTimeMs: number;
}

export interface DiffusionStreamEvent {
  /** Generation is single-flight, so the stream itself is the correlation. */
  timestampUs: number;
  kind: DiffusionStreamEventKind;
  progress?: DiffusionProgress | undefined;
  result?: DiffusionResult | undefined;
  error?: SDKError | undefined;
}

function createBaseDiffusionGenerationOptions(): DiffusionGenerationOptions {
  return {
    prompt: "",
    negativePrompt: "",
    width: 0,
    height: 0,
    steps: 0,
    guidanceScale: 0,
    seed: undefined,
    scheduler: 0,
    image: undefined,
    maskImage: undefined,
    strength: 0,
    imageMediaType: undefined,
    maskImageMediaType: undefined,
    n: undefined,
    outputFormat: 0,
  };
}

export const DiffusionGenerationOptions: MessageFns<DiffusionGenerationOptions> = {
  encode(message: DiffusionGenerationOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.prompt !== "") {
      writer.uint32(10).string(message.prompt);
    }
    if (message.negativePrompt !== "") {
      writer.uint32(18).string(message.negativePrompt);
    }
    if (message.width !== 0) {
      writer.uint32(24).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(32).int32(message.height);
    }
    if (message.steps !== 0) {
      writer.uint32(40).int32(message.steps);
    }
    if (message.guidanceScale !== 0) {
      writer.uint32(53).float(message.guidanceScale);
    }
    if (message.seed !== undefined) {
      writer.uint32(56).int64(message.seed);
    }
    if (message.scheduler !== 0) {
      writer.uint32(64).int32(message.scheduler);
    }
    if (message.image !== undefined) {
      writer.uint32(74).bytes(message.image);
    }
    if (message.maskImage !== undefined) {
      writer.uint32(82).bytes(message.maskImage);
    }
    if (message.strength !== 0) {
      writer.uint32(93).float(message.strength);
    }
    if (message.imageMediaType !== undefined) {
      writer.uint32(98).string(message.imageMediaType);
    }
    if (message.maskImageMediaType !== undefined) {
      writer.uint32(106).string(message.maskImageMediaType);
    }
    if (message.n !== undefined) {
      writer.uint32(112).int32(message.n);
    }
    if (message.outputFormat !== 0) {
      writer.uint32(120).int32(message.outputFormat);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DiffusionGenerationOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiffusionGenerationOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.prompt = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.negativePrompt = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.steps = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.guidanceScale = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.seed = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.scheduler = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.image = reader.bytes();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.maskImage = reader.bytes();
          continue;
        }
        case 11: {
          if (tag !== 93) {
            break;
          }

          message.strength = reader.float();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.imageMediaType = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.maskImageMediaType = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.n = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.outputFormat = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiffusionGenerationOptions {
    return {
      prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
      negativePrompt: isSet(object.negativePrompt)
        ? globalThis.String(object.negativePrompt)
        : isSet(object.negative_prompt)
        ? globalThis.String(object.negative_prompt)
        : "",
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      steps: isSet(object.steps) ? globalThis.Number(object.steps) : 0,
      guidanceScale: isSet(object.guidanceScale)
        ? globalThis.Number(object.guidanceScale)
        : isSet(object.guidance_scale)
        ? globalThis.Number(object.guidance_scale)
        : 0,
      seed: isSet(object.seed) ? globalThis.Number(object.seed) : undefined,
      scheduler: isSet(object.scheduler) ? diffusionSchedulerFromJSON(object.scheduler) : 0,
      image: isSet(object.image) ? bytesFromBase64(object.image) : undefined,
      maskImage: isSet(object.maskImage)
        ? bytesFromBase64(object.maskImage)
        : isSet(object.mask_image)
        ? bytesFromBase64(object.mask_image)
        : undefined,
      strength: isSet(object.strength) ? globalThis.Number(object.strength) : 0,
      imageMediaType: isSet(object.imageMediaType)
        ? globalThis.String(object.imageMediaType)
        : isSet(object.image_media_type)
        ? globalThis.String(object.image_media_type)
        : undefined,
      maskImageMediaType: isSet(object.maskImageMediaType)
        ? globalThis.String(object.maskImageMediaType)
        : isSet(object.mask_image_media_type)
        ? globalThis.String(object.mask_image_media_type)
        : undefined,
      n: isSet(object.n) ? globalThis.Number(object.n) : undefined,
      outputFormat: isSet(object.outputFormat)
        ? diffusionOutputFormatFromJSON(object.outputFormat)
        : isSet(object.output_format)
        ? diffusionOutputFormatFromJSON(object.output_format)
        : 0,
    };
  },

  toJSON(message: DiffusionGenerationOptions): unknown {
    const obj: any = {};
    if (message.prompt !== "") {
      obj.prompt = message.prompt;
    }
    if (message.negativePrompt !== "") {
      obj.negativePrompt = message.negativePrompt;
    }
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.steps !== 0) {
      obj.steps = Math.round(message.steps);
    }
    if (message.guidanceScale !== 0) {
      obj.guidanceScale = message.guidanceScale;
    }
    if (message.seed !== undefined) {
      obj.seed = Math.round(message.seed);
    }
    if (message.scheduler !== 0) {
      obj.scheduler = diffusionSchedulerToJSON(message.scheduler);
    }
    if (message.image !== undefined) {
      obj.image = base64FromBytes(message.image);
    }
    if (message.maskImage !== undefined) {
      obj.maskImage = base64FromBytes(message.maskImage);
    }
    if (message.strength !== 0) {
      obj.strength = message.strength;
    }
    if (message.imageMediaType !== undefined) {
      obj.imageMediaType = message.imageMediaType;
    }
    if (message.maskImageMediaType !== undefined) {
      obj.maskImageMediaType = message.maskImageMediaType;
    }
    if (message.n !== undefined) {
      obj.n = Math.round(message.n);
    }
    if (message.outputFormat !== 0) {
      obj.outputFormat = diffusionOutputFormatToJSON(message.outputFormat);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiffusionGenerationOptions>, I>>(base?: I): DiffusionGenerationOptions {
    return DiffusionGenerationOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiffusionGenerationOptions>, I>>(object: I): DiffusionGenerationOptions {
    const message = createBaseDiffusionGenerationOptions();
    message.prompt = object.prompt ?? "";
    message.negativePrompt = object.negativePrompt ?? "";
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.steps = object.steps ?? 0;
    message.guidanceScale = object.guidanceScale ?? 0;
    message.seed = object.seed ?? undefined;
    message.scheduler = object.scheduler ?? 0;
    message.image = object.image ?? undefined;
    message.maskImage = object.maskImage ?? undefined;
    message.strength = object.strength ?? 0;
    message.imageMediaType = object.imageMediaType ?? undefined;
    message.maskImageMediaType = object.maskImageMediaType ?? undefined;
    message.n = object.n ?? undefined;
    message.outputFormat = object.outputFormat ?? 0;
    return message;
  },
};

function createBaseDiffusionGenerationRequest(): DiffusionGenerationRequest {
  return { options: undefined, modelId: undefined };
}

export const DiffusionGenerationRequest: MessageFns<DiffusionGenerationRequest> = {
  encode(message: DiffusionGenerationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.options !== undefined) {
      DiffusionGenerationOptions.encode(message.options, writer.uint32(10).fork()).join();
    }
    if (message.modelId !== undefined) {
      writer.uint32(18).string(message.modelId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DiffusionGenerationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiffusionGenerationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.options = DiffusionGenerationOptions.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiffusionGenerationRequest {
    return {
      options: isSet(object.options) ? DiffusionGenerationOptions.fromJSON(object.options) : undefined,
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : undefined,
    };
  },

  toJSON(message: DiffusionGenerationRequest): unknown {
    const obj: any = {};
    if (message.options !== undefined) {
      obj.options = DiffusionGenerationOptions.toJSON(message.options);
    }
    if (message.modelId !== undefined) {
      obj.modelId = message.modelId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiffusionGenerationRequest>, I>>(base?: I): DiffusionGenerationRequest {
    return DiffusionGenerationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiffusionGenerationRequest>, I>>(object: I): DiffusionGenerationRequest {
    const message = createBaseDiffusionGenerationRequest();
    message.options = (object.options !== undefined && object.options !== null)
      ? DiffusionGenerationOptions.fromPartial(object.options)
      : undefined;
    message.modelId = object.modelId ?? undefined;
    return message;
  },
};

function createBaseDiffusionProgress(): DiffusionProgress {
  return { currentStep: 0, totalSteps: 0, intermediateImageData: undefined };
}

export const DiffusionProgress: MessageFns<DiffusionProgress> = {
  encode(message: DiffusionProgress, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currentStep !== 0) {
      writer.uint32(8).int32(message.currentStep);
    }
    if (message.totalSteps !== 0) {
      writer.uint32(16).int32(message.totalSteps);
    }
    if (message.intermediateImageData !== undefined) {
      writer.uint32(26).bytes(message.intermediateImageData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DiffusionProgress {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiffusionProgress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.currentStep = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalSteps = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.intermediateImageData = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiffusionProgress {
    return {
      currentStep: isSet(object.currentStep)
        ? globalThis.Number(object.currentStep)
        : isSet(object.current_step)
        ? globalThis.Number(object.current_step)
        : 0,
      totalSteps: isSet(object.totalSteps)
        ? globalThis.Number(object.totalSteps)
        : isSet(object.total_steps)
        ? globalThis.Number(object.total_steps)
        : 0,
      intermediateImageData: isSet(object.intermediateImageData)
        ? bytesFromBase64(object.intermediateImageData)
        : isSet(object.intermediate_image_data)
        ? bytesFromBase64(object.intermediate_image_data)
        : undefined,
    };
  },

  toJSON(message: DiffusionProgress): unknown {
    const obj: any = {};
    if (message.currentStep !== 0) {
      obj.currentStep = Math.round(message.currentStep);
    }
    if (message.totalSteps !== 0) {
      obj.totalSteps = Math.round(message.totalSteps);
    }
    if (message.intermediateImageData !== undefined) {
      obj.intermediateImageData = base64FromBytes(message.intermediateImageData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiffusionProgress>, I>>(base?: I): DiffusionProgress {
    return DiffusionProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiffusionProgress>, I>>(object: I): DiffusionProgress {
    const message = createBaseDiffusionProgress();
    message.currentStep = object.currentStep ?? 0;
    message.totalSteps = object.totalSteps ?? 0;
    message.intermediateImageData = object.intermediateImageData ?? undefined;
    return message;
  },
};

function createBaseDiffusionImage(): DiffusionImage {
  return { data: new Uint8Array(0), width: 0, height: 0, seedUsed: 0, safetyFlag: false, mediaType: "" };
}

export const DiffusionImage: MessageFns<DiffusionImage> = {
  encode(message: DiffusionImage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data.length !== 0) {
      writer.uint32(10).bytes(message.data);
    }
    if (message.width !== 0) {
      writer.uint32(16).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(24).int32(message.height);
    }
    if (message.seedUsed !== 0) {
      writer.uint32(32).int64(message.seedUsed);
    }
    if (message.safetyFlag !== false) {
      writer.uint32(40).bool(message.safetyFlag);
    }
    if (message.mediaType !== "") {
      writer.uint32(50).string(message.mediaType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DiffusionImage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiffusionImage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.seedUsed = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.safetyFlag = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.mediaType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiffusionImage {
    return {
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      seedUsed: isSet(object.seedUsed)
        ? globalThis.Number(object.seedUsed)
        : isSet(object.seed_used)
        ? globalThis.Number(object.seed_used)
        : 0,
      safetyFlag: isSet(object.safetyFlag)
        ? globalThis.Boolean(object.safetyFlag)
        : isSet(object.safety_flag)
        ? globalThis.Boolean(object.safety_flag)
        : false,
      mediaType: isSet(object.mediaType)
        ? globalThis.String(object.mediaType)
        : isSet(object.media_type)
        ? globalThis.String(object.media_type)
        : "",
    };
  },

  toJSON(message: DiffusionImage): unknown {
    const obj: any = {};
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.seedUsed !== 0) {
      obj.seedUsed = Math.round(message.seedUsed);
    }
    if (message.safetyFlag !== false) {
      obj.safetyFlag = message.safetyFlag;
    }
    if (message.mediaType !== "") {
      obj.mediaType = message.mediaType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiffusionImage>, I>>(base?: I): DiffusionImage {
    return DiffusionImage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiffusionImage>, I>>(object: I): DiffusionImage {
    const message = createBaseDiffusionImage();
    message.data = object.data ?? new Uint8Array(0);
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.seedUsed = object.seedUsed ?? 0;
    message.safetyFlag = object.safetyFlag ?? false;
    message.mediaType = object.mediaType ?? "";
    return message;
  },
};

function createBaseDiffusionResult(): DiffusionResult {
  return { images: [], totalTimeMs: 0 };
}

export const DiffusionResult: MessageFns<DiffusionResult> = {
  encode(message: DiffusionResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.images) {
      DiffusionImage.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.totalTimeMs !== 0) {
      writer.uint32(16).int64(message.totalTimeMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DiffusionResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiffusionResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.images.push(DiffusionImage.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalTimeMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiffusionResult {
    return {
      images: globalThis.Array.isArray(object?.images) ? object.images.map((e: any) => DiffusionImage.fromJSON(e)) : [],
      totalTimeMs: isSet(object.totalTimeMs)
        ? globalThis.Number(object.totalTimeMs)
        : isSet(object.total_time_ms)
        ? globalThis.Number(object.total_time_ms)
        : 0,
    };
  },

  toJSON(message: DiffusionResult): unknown {
    const obj: any = {};
    if (message.images?.length) {
      obj.images = message.images.map((e) => DiffusionImage.toJSON(e));
    }
    if (message.totalTimeMs !== 0) {
      obj.totalTimeMs = Math.round(message.totalTimeMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiffusionResult>, I>>(base?: I): DiffusionResult {
    return DiffusionResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiffusionResult>, I>>(object: I): DiffusionResult {
    const message = createBaseDiffusionResult();
    message.images = object.images?.map((e) => DiffusionImage.fromPartial(e)) || [];
    message.totalTimeMs = object.totalTimeMs ?? 0;
    return message;
  },
};

function createBaseDiffusionStreamEvent(): DiffusionStreamEvent {
  return { timestampUs: 0, kind: 0, progress: undefined, result: undefined, error: undefined };
}

export const DiffusionStreamEvent: MessageFns<DiffusionStreamEvent> = {
  encode(message: DiffusionStreamEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestampUs !== 0) {
      writer.uint32(8).int64(message.timestampUs);
    }
    if (message.kind !== 0) {
      writer.uint32(16).int32(message.kind);
    }
    if (message.progress !== undefined) {
      DiffusionProgress.encode(message.progress, writer.uint32(26).fork()).join();
    }
    if (message.result !== undefined) {
      DiffusionResult.encode(message.result, writer.uint32(34).fork()).join();
    }
    if (message.error !== undefined) {
      SDKError.encode(message.error, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DiffusionStreamEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiffusionStreamEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestampUs = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.kind = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.progress = DiffusionProgress.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.result = DiffusionResult.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.error = SDKError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiffusionStreamEvent {
    return {
      timestampUs: isSet(object.timestampUs)
        ? globalThis.Number(object.timestampUs)
        : isSet(object.timestamp_us)
        ? globalThis.Number(object.timestamp_us)
        : 0,
      kind: isSet(object.kind) ? diffusionStreamEventKindFromJSON(object.kind) : 0,
      progress: isSet(object.progress) ? DiffusionProgress.fromJSON(object.progress) : undefined,
      result: isSet(object.result) ? DiffusionResult.fromJSON(object.result) : undefined,
      error: isSet(object.error) ? SDKError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: DiffusionStreamEvent): unknown {
    const obj: any = {};
    if (message.timestampUs !== 0) {
      obj.timestampUs = Math.round(message.timestampUs);
    }
    if (message.kind !== 0) {
      obj.kind = diffusionStreamEventKindToJSON(message.kind);
    }
    if (message.progress !== undefined) {
      obj.progress = DiffusionProgress.toJSON(message.progress);
    }
    if (message.result !== undefined) {
      obj.result = DiffusionResult.toJSON(message.result);
    }
    if (message.error !== undefined) {
      obj.error = SDKError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiffusionStreamEvent>, I>>(base?: I): DiffusionStreamEvent {
    return DiffusionStreamEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiffusionStreamEvent>, I>>(object: I): DiffusionStreamEvent {
    const message = createBaseDiffusionStreamEvent();
    message.timestampUs = object.timestampUs ?? 0;
    message.kind = object.kind ?? 0;
    message.progress = (object.progress !== undefined && object.progress !== null)
      ? DiffusionProgress.fromPartial(object.progress)
      : undefined;
    message.result = (object.result !== undefined && object.result !== null)
      ? DiffusionResult.fromPartial(object.result)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? SDKError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
