// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: llm_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ChatMessage } from "./chat";
import { LLMGenerationOptions } from "./llm_options";
import { ToolCall, ToolCallingResult, ToolResult } from "./tool_calling";
import { TokenKind, tokenKindFromJSON, tokenKindToJSON } from "./voice_events";

export const protobufPackage = "runanywhere.v1";

export enum LLMStreamEventKind {
  LLM_STREAM_EVENT_KIND_UNSPECIFIED = 0,
  LLM_STREAM_EVENT_KIND_STARTED = 1,
  LLM_STREAM_EVENT_KIND_TOKEN = 2,
  LLM_STREAM_EVENT_KIND_THINKING = 3,
  LLM_STREAM_EVENT_KIND_TOOL_CALL = 4,
  LLM_STREAM_EVENT_KIND_PROGRESS = 5,
  LLM_STREAM_EVENT_KIND_COMPLETED = 6,
  LLM_STREAM_EVENT_KIND_ERROR = 7,
  UNRECOGNIZED = -1,
}

export function lLMStreamEventKindFromJSON(object: any): LLMStreamEventKind {
  switch (object) {
    case 0:
    case "LLM_STREAM_EVENT_KIND_UNSPECIFIED":
      return LLMStreamEventKind.LLM_STREAM_EVENT_KIND_UNSPECIFIED;
    case 1:
    case "LLM_STREAM_EVENT_KIND_STARTED":
      return LLMStreamEventKind.LLM_STREAM_EVENT_KIND_STARTED;
    case 2:
    case "LLM_STREAM_EVENT_KIND_TOKEN":
      return LLMStreamEventKind.LLM_STREAM_EVENT_KIND_TOKEN;
    case 3:
    case "LLM_STREAM_EVENT_KIND_THINKING":
      return LLMStreamEventKind.LLM_STREAM_EVENT_KIND_THINKING;
    case 4:
    case "LLM_STREAM_EVENT_KIND_TOOL_CALL":
      return LLMStreamEventKind.LLM_STREAM_EVENT_KIND_TOOL_CALL;
    case 5:
    case "LLM_STREAM_EVENT_KIND_PROGRESS":
      return LLMStreamEventKind.LLM_STREAM_EVENT_KIND_PROGRESS;
    case 6:
    case "LLM_STREAM_EVENT_KIND_COMPLETED":
      return LLMStreamEventKind.LLM_STREAM_EVENT_KIND_COMPLETED;
    case 7:
    case "LLM_STREAM_EVENT_KIND_ERROR":
      return LLMStreamEventKind.LLM_STREAM_EVENT_KIND_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return LLMStreamEventKind.UNRECOGNIZED;
  }
}

export function lLMStreamEventKindToJSON(object: LLMStreamEventKind): string {
  switch (object) {
    case LLMStreamEventKind.LLM_STREAM_EVENT_KIND_UNSPECIFIED:
      return "LLM_STREAM_EVENT_KIND_UNSPECIFIED";
    case LLMStreamEventKind.LLM_STREAM_EVENT_KIND_STARTED:
      return "LLM_STREAM_EVENT_KIND_STARTED";
    case LLMStreamEventKind.LLM_STREAM_EVENT_KIND_TOKEN:
      return "LLM_STREAM_EVENT_KIND_TOKEN";
    case LLMStreamEventKind.LLM_STREAM_EVENT_KIND_THINKING:
      return "LLM_STREAM_EVENT_KIND_THINKING";
    case LLMStreamEventKind.LLM_STREAM_EVENT_KIND_TOOL_CALL:
      return "LLM_STREAM_EVENT_KIND_TOOL_CALL";
    case LLMStreamEventKind.LLM_STREAM_EVENT_KIND_PROGRESS:
      return "LLM_STREAM_EVENT_KIND_PROGRESS";
    case LLMStreamEventKind.LLM_STREAM_EVENT_KIND_COMPLETED:
      return "LLM_STREAM_EVENT_KIND_COMPLETED";
    case LLMStreamEventKind.LLM_STREAM_EVENT_KIND_ERROR:
      return "LLM_STREAM_EVENT_KIND_ERROR";
    case LLMStreamEventKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Generation settings live exclusively in `options`. Reserved field numbers
 * prevent unsafe wire reuse.
 */
export interface LLMGenerateRequest {
  prompt: string;
  requestId: string;
  modelId: string;
  conversationId: string;
  metadata: { [key: string]: string };
  /**
   * Canonical generation settings. When absent, commons applies its SDK
   * defaults; callers that need explicit controls populate this message.
   */
  options?:
    | LLMGenerationOptions
    | undefined;
  /**
   * Prior conversation turns (excludes the current `prompt`, which
   * stays the live user turn, and `options.system_prompt`, which stays
   * separate).
   * Alternating user/assistant ChatMessages in chronological order. An engine
   * that owns its chat template renders {system_prompt, history, prompt} from
   * its model's markers; engines that don't simply ignore this field.
   */
  history: ChatMessage[];
}

export interface LLMGenerateRequest_MetadataEntry {
  key: string;
  value: string;
}

/**
 * Aggregate terminal payload emitted by LLMStreamEvent. It intentionally keeps
 * stream-native token, timing, and error fields distinct from the unary
 * LLMGenerationResult shape.
 */
export interface LLMStreamFinalResult {
  text: string;
  thinkingContent?: string | undefined;
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  totalTimeMs: number;
  timeToFirstTokenMs: number;
  tokensPerSecond: number;
  finishReason: string;
  errorCode: number;
  errorMessage: string;
  promptEvalTimeMs: number;
  decodeTimeMs: number;
  /**
   * Tool calls actually executed during the streaming session (mirrors
   * LLMGenerationResult.tool_calls / .tool_results in llm_options.proto).
   * Populated only on terminal events when the backend completed at least
   * one tool call.
   */
  toolCalls: ToolCall[];
  toolResults: ToolResult[];
}

/**
 * Unified per-token streaming event. Replaces
 * LLMToken (deleted) and the per-SDK hand-rolled AsyncThrowingStream /
 * callbackFlow / StreamController / tokenQueue. One serialized event
 * per generated token. Mirrors VoiceEvent's seq + timestamp_us pattern
 * from voice_events.proto so frontends can reuse gap-detection logic.
 */
export interface LLMStreamEvent {
  /**
   * Monotonic per-process sequence number. Useful for frontends that
   * need to detect gaps or out-of-order delivery.
   */
  seq: number;
  /**
   * Wall-clock timestamp captured at the C++ edge, in microseconds
   * since Unix epoch. Frontends may re-timestamp for UI display.
   */
  timestampUs: number;
  /**
   * Generated token text. Empty on terminal events where only
   * finish_reason or error_message is populated.
   */
  token: string;
  /** True on the last event of a generation. */
  isFinal: boolean;
  /**
   * Token semantic category (answer / thought / tool-call).
   * Canonical TokenKind from voice_events.proto.
   */
  kind: TokenKind;
  /**
   * Backend-provided token id when the engine exposes it; 0 = unset
   * (proto3 scalar default).
   */
  tokenId: number;
  /** Per-token log-probability when supported; 0.0 = unset. */
  logprob: number;
  /**
   * Reason the stream stopped: "stop", "length", "cancelled", "error",
   * "" = unset (proto3 scalar default). Only populated when is_final.
   */
  finishReason: string;
  /**
   * Error message on failure events (kind may be unset, is_final true).
   * Empty on success.
   */
  errorMessage: string;
  /**
   * Final aggregate result. Only populated on terminal events
   * (is_final=true) when the backend can report result metrics.
   */
  result?:
    | LLMStreamFinalResult
    | undefined;
  /**
   * Numeric backend status code when the terminal event represents a
   * failure. 0 = unset/success.
   */
  errorCode: number;
  /** Event classification distinct from token semantic kind. */
  eventKind: LLMStreamEventKind;
  /** Request/session correlation fields. */
  requestId: string;
  conversationId: string;
  /** Running counters for progress UIs. */
  promptTokensProcessed: number;
  completionTokensGenerated: number;
  elapsedMs: number;
  /**
   * Structured tool-call payload emitted when event_kind is
   * LLM_STREAM_EVENT_KIND_TOOL_CALL.
   */
  toolCall?: ToolCall | undefined;
}

/**
 * ---------------------------------------------------------------------------
 * Tool-calling session / run-loop envelopes. They live here (not in
 * tool_calling.proto) because they carry an LLMGenerationOptions and
 * llm_options.proto already imports tool_calling.proto — the reverse import
 * would be a cycle. Moving them ended the inline re-declaration of sampling
 * knobs the old ToolCallingSessionCreateRequest carried.
 * ---------------------------------------------------------------------------
 */
export interface ToolCallingSessionCreateRequest {
  /** The live user turn. */
  prompt: string;
  /**
   * Sampling, reasoning, system prompt — the same canonical knobs as any
   * other generation. tools/tool_choice policy travels in
   * generation.tool_calling.
   */
  generation?:
    | LLMGenerationOptions
    | undefined;
  /**
   * proto3 `optional` enables presence detection. When unset, commons
   * defaults to validate_calls=true so unknown tool calls short-circuit
   * before host execution. Callers that delegate validation to their
   * executor must explicitly set false.
   */
  validateCalls?:
    | boolean
    | undefined;
  /**
   * Prior conversation turns (excluding `prompt`), same contract as
   * LLMGenerateRequest.history.
   */
  history: ChatMessage[];
}

export interface ToolCallingSessionCreateResult {
  sessionHandle: number;
}

export interface ToolCallingSessionEvent {
  /** serialized LLMStreamEvent proto */
  llmStreamEventBytes?: Uint8Array | undefined;
  toolCall?: ToolCall | undefined;
  finalResult?:
    | ToolCallingResult
    | undefined;
  /** serialized SDKError proto */
  errorBytes?: Uint8Array | undefined;
  seq: number;
}

export interface ToolCallingSessionStepWithResultRequest {
  sessionHandle: number;
  toolCallId: string;
  resultJson: string;
  error?: string | undefined;
}

export interface ToolCallingSessionDestroyRequest {
  sessionHandle: number;
}

function createBaseLLMGenerateRequest(): LLMGenerateRequest {
  return { prompt: "", requestId: "", modelId: "", conversationId: "", metadata: {}, options: undefined, history: [] };
}

export const LLMGenerateRequest: MessageFns<LLMGenerateRequest> = {
  encode(message: LLMGenerateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.prompt !== "") {
      writer.uint32(10).string(message.prompt);
    }
    if (message.requestId !== "") {
      writer.uint32(114).string(message.requestId);
    }
    if (message.modelId !== "") {
      writer.uint32(122).string(message.modelId);
    }
    if (message.conversationId !== "") {
      writer.uint32(130).string(message.conversationId);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      LLMGenerateRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(202).fork()).join();
    });
    if (message.options !== undefined) {
      LLMGenerationOptions.encode(message.options, writer.uint32(210).fork()).join();
    }
    for (const v of message.history) {
      ChatMessage.encode(v!, writer.uint32(218).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LLMGenerateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLLMGenerateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.prompt = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
        case 25: {
          if (tag !== 202) {
            break;
          }

          const entry25 = LLMGenerateRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry25.value !== undefined) {
            message.metadata[entry25.key] = entry25.value;
          }
          continue;
        }
        case 26: {
          if (tag !== 210) {
            break;
          }

          message.options = LLMGenerationOptions.decode(reader, reader.uint32());
          continue;
        }
        case 27: {
          if (tag !== 218) {
            break;
          }

          message.history.push(ChatMessage.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LLMGenerateRequest {
    return {
      prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      options: isSet(object.options) ? LLMGenerationOptions.fromJSON(object.options) : undefined,
      history: globalThis.Array.isArray(object?.history)
        ? object.history.map((e: any) => ChatMessage.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LLMGenerateRequest): unknown {
    const obj: any = {};
    if (message.prompt !== "") {
      obj.prompt = message.prompt;
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    if (message.options !== undefined) {
      obj.options = LLMGenerationOptions.toJSON(message.options);
    }
    if (message.history?.length) {
      obj.history = message.history.map((e) => ChatMessage.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LLMGenerateRequest>, I>>(base?: I): LLMGenerateRequest {
    return LLMGenerateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LLMGenerateRequest>, I>>(object: I): LLMGenerateRequest {
    const message = createBaseLLMGenerateRequest();
    message.prompt = object.prompt ?? "";
    message.requestId = object.requestId ?? "";
    message.modelId = object.modelId ?? "";
    message.conversationId = object.conversationId ?? "";
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.options = (object.options !== undefined && object.options !== null)
      ? LLMGenerationOptions.fromPartial(object.options)
      : undefined;
    message.history = object.history?.map((e) => ChatMessage.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLLMGenerateRequest_MetadataEntry(): LLMGenerateRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const LLMGenerateRequest_MetadataEntry: MessageFns<LLMGenerateRequest_MetadataEntry> = {
  encode(message: LLMGenerateRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LLMGenerateRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLLMGenerateRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LLMGenerateRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: LLMGenerateRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LLMGenerateRequest_MetadataEntry>, I>>(
    base?: I,
  ): LLMGenerateRequest_MetadataEntry {
    return LLMGenerateRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LLMGenerateRequest_MetadataEntry>, I>>(
    object: I,
  ): LLMGenerateRequest_MetadataEntry {
    const message = createBaseLLMGenerateRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseLLMStreamFinalResult(): LLMStreamFinalResult {
  return {
    text: "",
    thinkingContent: undefined,
    inputTokens: 0,
    outputTokens: 0,
    totalTokens: 0,
    totalTimeMs: 0,
    timeToFirstTokenMs: 0,
    tokensPerSecond: 0,
    finishReason: "",
    errorCode: 0,
    errorMessage: "",
    promptEvalTimeMs: 0,
    decodeTimeMs: 0,
    toolCalls: [],
    toolResults: [],
  };
}

export const LLMStreamFinalResult: MessageFns<LLMStreamFinalResult> = {
  encode(message: LLMStreamFinalResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.thinkingContent !== undefined) {
      writer.uint32(18).string(message.thinkingContent);
    }
    if (message.inputTokens !== 0) {
      writer.uint32(24).int32(message.inputTokens);
    }
    if (message.outputTokens !== 0) {
      writer.uint32(32).int32(message.outputTokens);
    }
    if (message.totalTokens !== 0) {
      writer.uint32(40).int32(message.totalTokens);
    }
    if (message.totalTimeMs !== 0) {
      writer.uint32(48).int64(message.totalTimeMs);
    }
    if (message.timeToFirstTokenMs !== 0) {
      writer.uint32(56).int64(message.timeToFirstTokenMs);
    }
    if (message.tokensPerSecond !== 0) {
      writer.uint32(69).float(message.tokensPerSecond);
    }
    if (message.finishReason !== "") {
      writer.uint32(74).string(message.finishReason);
    }
    if (message.errorCode !== 0) {
      writer.uint32(80).int32(message.errorCode);
    }
    if (message.errorMessage !== "") {
      writer.uint32(90).string(message.errorMessage);
    }
    if (message.promptEvalTimeMs !== 0) {
      writer.uint32(96).int64(message.promptEvalTimeMs);
    }
    if (message.decodeTimeMs !== 0) {
      writer.uint32(104).int64(message.decodeTimeMs);
    }
    for (const v of message.toolCalls) {
      ToolCall.encode(v!, writer.uint32(114).fork()).join();
    }
    for (const v of message.toolResults) {
      ToolResult.encode(v!, writer.uint32(122).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LLMStreamFinalResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLLMStreamFinalResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.thinkingContent = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.inputTokens = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.outputTokens = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.totalTokens = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.timeToFirstTokenMs = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.tokensPerSecond = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.finishReason = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.promptEvalTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.decodeTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.toolCalls.push(ToolCall.decode(reader, reader.uint32()));
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.toolResults.push(ToolResult.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LLMStreamFinalResult {
    return {
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      thinkingContent: isSet(object.thinkingContent)
        ? globalThis.String(object.thinkingContent)
        : isSet(object.thinking_content)
        ? globalThis.String(object.thinking_content)
        : undefined,
      inputTokens: isSet(object.inputTokens)
        ? globalThis.Number(object.inputTokens)
        : isSet(object.input_tokens)
        ? globalThis.Number(object.input_tokens)
        : 0,
      outputTokens: isSet(object.outputTokens)
        ? globalThis.Number(object.outputTokens)
        : isSet(object.output_tokens)
        ? globalThis.Number(object.output_tokens)
        : 0,
      totalTokens: isSet(object.totalTokens)
        ? globalThis.Number(object.totalTokens)
        : isSet(object.total_tokens)
        ? globalThis.Number(object.total_tokens)
        : 0,
      totalTimeMs: isSet(object.totalTimeMs)
        ? globalThis.Number(object.totalTimeMs)
        : isSet(object.total_time_ms)
        ? globalThis.Number(object.total_time_ms)
        : 0,
      timeToFirstTokenMs: isSet(object.timeToFirstTokenMs)
        ? globalThis.Number(object.timeToFirstTokenMs)
        : isSet(object.time_to_first_token_ms)
        ? globalThis.Number(object.time_to_first_token_ms)
        : 0,
      tokensPerSecond: isSet(object.tokensPerSecond)
        ? globalThis.Number(object.tokensPerSecond)
        : isSet(object.tokens_per_second)
        ? globalThis.Number(object.tokens_per_second)
        : 0,
      finishReason: isSet(object.finishReason)
        ? globalThis.String(object.finishReason)
        : isSet(object.finish_reason)
        ? globalThis.String(object.finish_reason)
        : "",
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
      promptEvalTimeMs: isSet(object.promptEvalTimeMs)
        ? globalThis.Number(object.promptEvalTimeMs)
        : isSet(object.prompt_eval_time_ms)
        ? globalThis.Number(object.prompt_eval_time_ms)
        : 0,
      decodeTimeMs: isSet(object.decodeTimeMs)
        ? globalThis.Number(object.decodeTimeMs)
        : isSet(object.decode_time_ms)
        ? globalThis.Number(object.decode_time_ms)
        : 0,
      toolCalls: globalThis.Array.isArray(object?.toolCalls)
        ? object.toolCalls.map((e: any) => ToolCall.fromJSON(e))
        : globalThis.Array.isArray(object?.tool_calls)
        ? object.tool_calls.map((e: any) => ToolCall.fromJSON(e))
        : [],
      toolResults: globalThis.Array.isArray(object?.toolResults)
        ? object.toolResults.map((e: any) => ToolResult.fromJSON(e))
        : globalThis.Array.isArray(object?.tool_results)
        ? object.tool_results.map((e: any) => ToolResult.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LLMStreamFinalResult): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.thinkingContent !== undefined) {
      obj.thinkingContent = message.thinkingContent;
    }
    if (message.inputTokens !== 0) {
      obj.inputTokens = Math.round(message.inputTokens);
    }
    if (message.outputTokens !== 0) {
      obj.outputTokens = Math.round(message.outputTokens);
    }
    if (message.totalTokens !== 0) {
      obj.totalTokens = Math.round(message.totalTokens);
    }
    if (message.totalTimeMs !== 0) {
      obj.totalTimeMs = Math.round(message.totalTimeMs);
    }
    if (message.timeToFirstTokenMs !== 0) {
      obj.timeToFirstTokenMs = Math.round(message.timeToFirstTokenMs);
    }
    if (message.tokensPerSecond !== 0) {
      obj.tokensPerSecond = message.tokensPerSecond;
    }
    if (message.finishReason !== "") {
      obj.finishReason = message.finishReason;
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.promptEvalTimeMs !== 0) {
      obj.promptEvalTimeMs = Math.round(message.promptEvalTimeMs);
    }
    if (message.decodeTimeMs !== 0) {
      obj.decodeTimeMs = Math.round(message.decodeTimeMs);
    }
    if (message.toolCalls?.length) {
      obj.toolCalls = message.toolCalls.map((e) => ToolCall.toJSON(e));
    }
    if (message.toolResults?.length) {
      obj.toolResults = message.toolResults.map((e) => ToolResult.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LLMStreamFinalResult>, I>>(base?: I): LLMStreamFinalResult {
    return LLMStreamFinalResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LLMStreamFinalResult>, I>>(object: I): LLMStreamFinalResult {
    const message = createBaseLLMStreamFinalResult();
    message.text = object.text ?? "";
    message.thinkingContent = object.thinkingContent ?? undefined;
    message.inputTokens = object.inputTokens ?? 0;
    message.outputTokens = object.outputTokens ?? 0;
    message.totalTokens = object.totalTokens ?? 0;
    message.totalTimeMs = object.totalTimeMs ?? 0;
    message.timeToFirstTokenMs = object.timeToFirstTokenMs ?? 0;
    message.tokensPerSecond = object.tokensPerSecond ?? 0;
    message.finishReason = object.finishReason ?? "";
    message.errorCode = object.errorCode ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    message.promptEvalTimeMs = object.promptEvalTimeMs ?? 0;
    message.decodeTimeMs = object.decodeTimeMs ?? 0;
    message.toolCalls = object.toolCalls?.map((e) => ToolCall.fromPartial(e)) || [];
    message.toolResults = object.toolResults?.map((e) => ToolResult.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLLMStreamEvent(): LLMStreamEvent {
  return {
    seq: 0,
    timestampUs: 0,
    token: "",
    isFinal: false,
    kind: 0,
    tokenId: 0,
    logprob: 0,
    finishReason: "",
    errorMessage: "",
    result: undefined,
    errorCode: 0,
    eventKind: 0,
    requestId: "",
    conversationId: "",
    promptTokensProcessed: 0,
    completionTokensGenerated: 0,
    elapsedMs: 0,
    toolCall: undefined,
  };
}

export const LLMStreamEvent: MessageFns<LLMStreamEvent> = {
  encode(message: LLMStreamEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seq !== 0) {
      writer.uint32(8).uint64(message.seq);
    }
    if (message.timestampUs !== 0) {
      writer.uint32(16).int64(message.timestampUs);
    }
    if (message.token !== "") {
      writer.uint32(26).string(message.token);
    }
    if (message.isFinal !== false) {
      writer.uint32(32).bool(message.isFinal);
    }
    if (message.kind !== 0) {
      writer.uint32(40).int32(message.kind);
    }
    if (message.tokenId !== 0) {
      writer.uint32(48).uint32(message.tokenId);
    }
    if (message.logprob !== 0) {
      writer.uint32(61).float(message.logprob);
    }
    if (message.finishReason !== "") {
      writer.uint32(66).string(message.finishReason);
    }
    if (message.errorMessage !== "") {
      writer.uint32(74).string(message.errorMessage);
    }
    if (message.result !== undefined) {
      LLMStreamFinalResult.encode(message.result, writer.uint32(82).fork()).join();
    }
    if (message.errorCode !== 0) {
      writer.uint32(88).int32(message.errorCode);
    }
    if (message.eventKind !== 0) {
      writer.uint32(96).int32(message.eventKind);
    }
    if (message.requestId !== "") {
      writer.uint32(106).string(message.requestId);
    }
    if (message.conversationId !== "") {
      writer.uint32(114).string(message.conversationId);
    }
    if (message.promptTokensProcessed !== 0) {
      writer.uint32(120).int32(message.promptTokensProcessed);
    }
    if (message.completionTokensGenerated !== 0) {
      writer.uint32(128).int32(message.completionTokensGenerated);
    }
    if (message.elapsedMs !== 0) {
      writer.uint32(136).int64(message.elapsedMs);
    }
    if (message.toolCall !== undefined) {
      ToolCall.encode(message.toolCall, writer.uint32(146).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LLMStreamEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLLMStreamEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seq = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestampUs = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isFinal = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.kind = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.tokenId = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.logprob = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.finishReason = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.result = LLMStreamFinalResult.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.eventKind = reader.int32() as any;
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.promptTokensProcessed = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.completionTokensGenerated = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.elapsedMs = longToNumber(reader.int64());
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.toolCall = ToolCall.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LLMStreamEvent {
    return {
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
      timestampUs: isSet(object.timestampUs)
        ? globalThis.Number(object.timestampUs)
        : isSet(object.timestamp_us)
        ? globalThis.Number(object.timestamp_us)
        : 0,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      isFinal: isSet(object.isFinal)
        ? globalThis.Boolean(object.isFinal)
        : isSet(object.is_final)
        ? globalThis.Boolean(object.is_final)
        : false,
      kind: isSet(object.kind) ? tokenKindFromJSON(object.kind) : 0,
      tokenId: isSet(object.tokenId)
        ? globalThis.Number(object.tokenId)
        : isSet(object.token_id)
        ? globalThis.Number(object.token_id)
        : 0,
      logprob: isSet(object.logprob) ? globalThis.Number(object.logprob) : 0,
      finishReason: isSet(object.finishReason)
        ? globalThis.String(object.finishReason)
        : isSet(object.finish_reason)
        ? globalThis.String(object.finish_reason)
        : "",
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
      result: isSet(object.result) ? LLMStreamFinalResult.fromJSON(object.result) : undefined,
      errorCode: isSet(object.errorCode)
        ? globalThis.Number(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.Number(object.error_code)
        : 0,
      eventKind: isSet(object.eventKind)
        ? lLMStreamEventKindFromJSON(object.eventKind)
        : isSet(object.event_kind)
        ? lLMStreamEventKindFromJSON(object.event_kind)
        : 0,
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      promptTokensProcessed: isSet(object.promptTokensProcessed)
        ? globalThis.Number(object.promptTokensProcessed)
        : isSet(object.prompt_tokens_processed)
        ? globalThis.Number(object.prompt_tokens_processed)
        : 0,
      completionTokensGenerated: isSet(object.completionTokensGenerated)
        ? globalThis.Number(object.completionTokensGenerated)
        : isSet(object.completion_tokens_generated)
        ? globalThis.Number(object.completion_tokens_generated)
        : 0,
      elapsedMs: isSet(object.elapsedMs)
        ? globalThis.Number(object.elapsedMs)
        : isSet(object.elapsed_ms)
        ? globalThis.Number(object.elapsed_ms)
        : 0,
      toolCall: isSet(object.toolCall)
        ? ToolCall.fromJSON(object.toolCall)
        : isSet(object.tool_call)
        ? ToolCall.fromJSON(object.tool_call)
        : undefined,
    };
  },

  toJSON(message: LLMStreamEvent): unknown {
    const obj: any = {};
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    if (message.timestampUs !== 0) {
      obj.timestampUs = Math.round(message.timestampUs);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.isFinal !== false) {
      obj.isFinal = message.isFinal;
    }
    if (message.kind !== 0) {
      obj.kind = tokenKindToJSON(message.kind);
    }
    if (message.tokenId !== 0) {
      obj.tokenId = Math.round(message.tokenId);
    }
    if (message.logprob !== 0) {
      obj.logprob = message.logprob;
    }
    if (message.finishReason !== "") {
      obj.finishReason = message.finishReason;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.result !== undefined) {
      obj.result = LLMStreamFinalResult.toJSON(message.result);
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    if (message.eventKind !== 0) {
      obj.eventKind = lLMStreamEventKindToJSON(message.eventKind);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    if (message.promptTokensProcessed !== 0) {
      obj.promptTokensProcessed = Math.round(message.promptTokensProcessed);
    }
    if (message.completionTokensGenerated !== 0) {
      obj.completionTokensGenerated = Math.round(message.completionTokensGenerated);
    }
    if (message.elapsedMs !== 0) {
      obj.elapsedMs = Math.round(message.elapsedMs);
    }
    if (message.toolCall !== undefined) {
      obj.toolCall = ToolCall.toJSON(message.toolCall);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LLMStreamEvent>, I>>(base?: I): LLMStreamEvent {
    return LLMStreamEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LLMStreamEvent>, I>>(object: I): LLMStreamEvent {
    const message = createBaseLLMStreamEvent();
    message.seq = object.seq ?? 0;
    message.timestampUs = object.timestampUs ?? 0;
    message.token = object.token ?? "";
    message.isFinal = object.isFinal ?? false;
    message.kind = object.kind ?? 0;
    message.tokenId = object.tokenId ?? 0;
    message.logprob = object.logprob ?? 0;
    message.finishReason = object.finishReason ?? "";
    message.errorMessage = object.errorMessage ?? "";
    message.result = (object.result !== undefined && object.result !== null)
      ? LLMStreamFinalResult.fromPartial(object.result)
      : undefined;
    message.errorCode = object.errorCode ?? 0;
    message.eventKind = object.eventKind ?? 0;
    message.requestId = object.requestId ?? "";
    message.conversationId = object.conversationId ?? "";
    message.promptTokensProcessed = object.promptTokensProcessed ?? 0;
    message.completionTokensGenerated = object.completionTokensGenerated ?? 0;
    message.elapsedMs = object.elapsedMs ?? 0;
    message.toolCall = (object.toolCall !== undefined && object.toolCall !== null)
      ? ToolCall.fromPartial(object.toolCall)
      : undefined;
    return message;
  },
};

function createBaseToolCallingSessionCreateRequest(): ToolCallingSessionCreateRequest {
  return { prompt: "", generation: undefined, validateCalls: undefined, history: [] };
}

export const ToolCallingSessionCreateRequest: MessageFns<ToolCallingSessionCreateRequest> = {
  encode(message: ToolCallingSessionCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.prompt !== "") {
      writer.uint32(10).string(message.prompt);
    }
    if (message.generation !== undefined) {
      LLMGenerationOptions.encode(message.generation, writer.uint32(18).fork()).join();
    }
    if (message.validateCalls !== undefined) {
      writer.uint32(24).bool(message.validateCalls);
    }
    for (const v of message.history) {
      ChatMessage.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCallingSessionCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCallingSessionCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.prompt = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.generation = LLMGenerationOptions.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.validateCalls = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.history.push(ChatMessage.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCallingSessionCreateRequest {
    return {
      prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
      generation: isSet(object.generation) ? LLMGenerationOptions.fromJSON(object.generation) : undefined,
      validateCalls: isSet(object.validateCalls)
        ? globalThis.Boolean(object.validateCalls)
        : isSet(object.validate_calls)
        ? globalThis.Boolean(object.validate_calls)
        : undefined,
      history: globalThis.Array.isArray(object?.history) ? object.history.map((e: any) => ChatMessage.fromJSON(e)) : [],
    };
  },

  toJSON(message: ToolCallingSessionCreateRequest): unknown {
    const obj: any = {};
    if (message.prompt !== "") {
      obj.prompt = message.prompt;
    }
    if (message.generation !== undefined) {
      obj.generation = LLMGenerationOptions.toJSON(message.generation);
    }
    if (message.validateCalls !== undefined) {
      obj.validateCalls = message.validateCalls;
    }
    if (message.history?.length) {
      obj.history = message.history.map((e) => ChatMessage.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolCallingSessionCreateRequest>, I>>(base?: I): ToolCallingSessionCreateRequest {
    return ToolCallingSessionCreateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolCallingSessionCreateRequest>, I>>(
    object: I,
  ): ToolCallingSessionCreateRequest {
    const message = createBaseToolCallingSessionCreateRequest();
    message.prompt = object.prompt ?? "";
    message.generation = (object.generation !== undefined && object.generation !== null)
      ? LLMGenerationOptions.fromPartial(object.generation)
      : undefined;
    message.validateCalls = object.validateCalls ?? undefined;
    message.history = object.history?.map((e) => ChatMessage.fromPartial(e)) || [];
    return message;
  },
};

function createBaseToolCallingSessionCreateResult(): ToolCallingSessionCreateResult {
  return { sessionHandle: 0 };
}

export const ToolCallingSessionCreateResult: MessageFns<ToolCallingSessionCreateResult> = {
  encode(message: ToolCallingSessionCreateResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionHandle !== 0) {
      writer.uint32(8).uint64(message.sessionHandle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCallingSessionCreateResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCallingSessionCreateResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sessionHandle = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCallingSessionCreateResult {
    return {
      sessionHandle: isSet(object.sessionHandle)
        ? globalThis.Number(object.sessionHandle)
        : isSet(object.session_handle)
        ? globalThis.Number(object.session_handle)
        : 0,
    };
  },

  toJSON(message: ToolCallingSessionCreateResult): unknown {
    const obj: any = {};
    if (message.sessionHandle !== 0) {
      obj.sessionHandle = Math.round(message.sessionHandle);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolCallingSessionCreateResult>, I>>(base?: I): ToolCallingSessionCreateResult {
    return ToolCallingSessionCreateResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolCallingSessionCreateResult>, I>>(
    object: I,
  ): ToolCallingSessionCreateResult {
    const message = createBaseToolCallingSessionCreateResult();
    message.sessionHandle = object.sessionHandle ?? 0;
    return message;
  },
};

function createBaseToolCallingSessionEvent(): ToolCallingSessionEvent {
  return { llmStreamEventBytes: undefined, toolCall: undefined, finalResult: undefined, errorBytes: undefined, seq: 0 };
}

export const ToolCallingSessionEvent: MessageFns<ToolCallingSessionEvent> = {
  encode(message: ToolCallingSessionEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.llmStreamEventBytes !== undefined) {
      writer.uint32(10).bytes(message.llmStreamEventBytes);
    }
    if (message.toolCall !== undefined) {
      ToolCall.encode(message.toolCall, writer.uint32(18).fork()).join();
    }
    if (message.finalResult !== undefined) {
      ToolCallingResult.encode(message.finalResult, writer.uint32(26).fork()).join();
    }
    if (message.errorBytes !== undefined) {
      writer.uint32(34).bytes(message.errorBytes);
    }
    if (message.seq !== 0) {
      writer.uint32(40).uint64(message.seq);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCallingSessionEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCallingSessionEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.llmStreamEventBytes = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.toolCall = ToolCall.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.finalResult = ToolCallingResult.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.errorBytes = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.seq = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCallingSessionEvent {
    return {
      llmStreamEventBytes: isSet(object.llmStreamEventBytes)
        ? bytesFromBase64(object.llmStreamEventBytes)
        : isSet(object.llm_stream_event_bytes)
        ? bytesFromBase64(object.llm_stream_event_bytes)
        : undefined,
      toolCall: isSet(object.toolCall)
        ? ToolCall.fromJSON(object.toolCall)
        : isSet(object.tool_call)
        ? ToolCall.fromJSON(object.tool_call)
        : undefined,
      finalResult: isSet(object.finalResult)
        ? ToolCallingResult.fromJSON(object.finalResult)
        : isSet(object.final_result)
        ? ToolCallingResult.fromJSON(object.final_result)
        : undefined,
      errorBytes: isSet(object.errorBytes)
        ? bytesFromBase64(object.errorBytes)
        : isSet(object.error_bytes)
        ? bytesFromBase64(object.error_bytes)
        : undefined,
      seq: isSet(object.seq) ? globalThis.Number(object.seq) : 0,
    };
  },

  toJSON(message: ToolCallingSessionEvent): unknown {
    const obj: any = {};
    if (message.llmStreamEventBytes !== undefined) {
      obj.llmStreamEventBytes = base64FromBytes(message.llmStreamEventBytes);
    }
    if (message.toolCall !== undefined) {
      obj.toolCall = ToolCall.toJSON(message.toolCall);
    }
    if (message.finalResult !== undefined) {
      obj.finalResult = ToolCallingResult.toJSON(message.finalResult);
    }
    if (message.errorBytes !== undefined) {
      obj.errorBytes = base64FromBytes(message.errorBytes);
    }
    if (message.seq !== 0) {
      obj.seq = Math.round(message.seq);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolCallingSessionEvent>, I>>(base?: I): ToolCallingSessionEvent {
    return ToolCallingSessionEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolCallingSessionEvent>, I>>(object: I): ToolCallingSessionEvent {
    const message = createBaseToolCallingSessionEvent();
    message.llmStreamEventBytes = object.llmStreamEventBytes ?? undefined;
    message.toolCall = (object.toolCall !== undefined && object.toolCall !== null)
      ? ToolCall.fromPartial(object.toolCall)
      : undefined;
    message.finalResult = (object.finalResult !== undefined && object.finalResult !== null)
      ? ToolCallingResult.fromPartial(object.finalResult)
      : undefined;
    message.errorBytes = object.errorBytes ?? undefined;
    message.seq = object.seq ?? 0;
    return message;
  },
};

function createBaseToolCallingSessionStepWithResultRequest(): ToolCallingSessionStepWithResultRequest {
  return { sessionHandle: 0, toolCallId: "", resultJson: "", error: undefined };
}

export const ToolCallingSessionStepWithResultRequest: MessageFns<ToolCallingSessionStepWithResultRequest> = {
  encode(message: ToolCallingSessionStepWithResultRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionHandle !== 0) {
      writer.uint32(8).uint64(message.sessionHandle);
    }
    if (message.toolCallId !== "") {
      writer.uint32(18).string(message.toolCallId);
    }
    if (message.resultJson !== "") {
      writer.uint32(26).string(message.resultJson);
    }
    if (message.error !== undefined) {
      writer.uint32(34).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCallingSessionStepWithResultRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCallingSessionStepWithResultRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sessionHandle = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.toolCallId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.resultJson = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCallingSessionStepWithResultRequest {
    return {
      sessionHandle: isSet(object.sessionHandle)
        ? globalThis.Number(object.sessionHandle)
        : isSet(object.session_handle)
        ? globalThis.Number(object.session_handle)
        : 0,
      toolCallId: isSet(object.toolCallId)
        ? globalThis.String(object.toolCallId)
        : isSet(object.tool_call_id)
        ? globalThis.String(object.tool_call_id)
        : "",
      resultJson: isSet(object.resultJson)
        ? globalThis.String(object.resultJson)
        : isSet(object.result_json)
        ? globalThis.String(object.result_json)
        : "",
      error: isSet(object.error) ? globalThis.String(object.error) : undefined,
    };
  },

  toJSON(message: ToolCallingSessionStepWithResultRequest): unknown {
    const obj: any = {};
    if (message.sessionHandle !== 0) {
      obj.sessionHandle = Math.round(message.sessionHandle);
    }
    if (message.toolCallId !== "") {
      obj.toolCallId = message.toolCallId;
    }
    if (message.resultJson !== "") {
      obj.resultJson = message.resultJson;
    }
    if (message.error !== undefined) {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolCallingSessionStepWithResultRequest>, I>>(
    base?: I,
  ): ToolCallingSessionStepWithResultRequest {
    return ToolCallingSessionStepWithResultRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolCallingSessionStepWithResultRequest>, I>>(
    object: I,
  ): ToolCallingSessionStepWithResultRequest {
    const message = createBaseToolCallingSessionStepWithResultRequest();
    message.sessionHandle = object.sessionHandle ?? 0;
    message.toolCallId = object.toolCallId ?? "";
    message.resultJson = object.resultJson ?? "";
    message.error = object.error ?? undefined;
    return message;
  },
};

function createBaseToolCallingSessionDestroyRequest(): ToolCallingSessionDestroyRequest {
  return { sessionHandle: 0 };
}

export const ToolCallingSessionDestroyRequest: MessageFns<ToolCallingSessionDestroyRequest> = {
  encode(message: ToolCallingSessionDestroyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionHandle !== 0) {
      writer.uint32(8).uint64(message.sessionHandle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCallingSessionDestroyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCallingSessionDestroyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sessionHandle = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCallingSessionDestroyRequest {
    return {
      sessionHandle: isSet(object.sessionHandle)
        ? globalThis.Number(object.sessionHandle)
        : isSet(object.session_handle)
        ? globalThis.Number(object.session_handle)
        : 0,
    };
  },

  toJSON(message: ToolCallingSessionDestroyRequest): unknown {
    const obj: any = {};
    if (message.sessionHandle !== 0) {
      obj.sessionHandle = Math.round(message.sessionHandle);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolCallingSessionDestroyRequest>, I>>(
    base?: I,
  ): ToolCallingSessionDestroyRequest {
    return ToolCallingSessionDestroyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolCallingSessionDestroyRequest>, I>>(
    object: I,
  ): ToolCallingSessionDestroyRequest {
    const message = createBaseToolCallingSessionDestroyRequest();
    message.sessionHandle = object.sessionHandle ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
