// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: structured_output.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SDKError } from "./errors";

export const protobufPackage = "runanywhere.v1";

export interface StructuredOutputOptions {
  /**
   * Also render the schema into the system prompt, not just constrain
   * decoding. Costs input tokens and invalidates the thread's prompt cache.
   * Default true (matches Apple FoundationModels includeSchemaInPrompt).
   */
  includeSchemaInPrompt?:
    | boolean
    | undefined;
  /** A JSON Schema document, verbatim. Unsupported keywords are rejected. */
  schema?:
    | string
    | undefined;
  /** GBNF/EBNF grammar text. On-device only. */
  grammar?:
    | string
    | undefined;
  /** Regular expression the whole output must match. On-device only. */
  regex?: string | undefined;
}

export interface StructuredOutputValidation {
  isValid: boolean;
  containsJson: boolean;
  rawOutput?: string | undefined;
  extractedJson?: string | undefined;
  validationErrors: string[];
  validationTimeMs: number;
  error?: SDKError | undefined;
}

export interface StructuredOutputResult {
  /** The extracted JSON document, as UTF-8 text. Parse it client-side. */
  json: string;
  validation?: StructuredOutputValidation | undefined;
  rawText?: string | undefined;
  error?: SDKError | undefined;
}

export interface StructuredOutputParseRequest {
  requestId: string;
  text: string;
  options?: StructuredOutputOptions | undefined;
  metadata: { [key: string]: string };
}

export interface StructuredOutputParseRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface StructuredOutputPromptResult {
  preparedPrompt: string;
  systemPrompt?: string | undefined;
  jsonSchema?: string | undefined;
  regexPattern?: string | undefined;
  grammar?: string | undefined;
  error?: SDKError | undefined;
}

function createBaseStructuredOutputOptions(): StructuredOutputOptions {
  return { includeSchemaInPrompt: undefined, schema: undefined, grammar: undefined, regex: undefined };
}

export const StructuredOutputOptions: MessageFns<StructuredOutputOptions> = {
  encode(message: StructuredOutputOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.includeSchemaInPrompt !== undefined) {
      writer.uint32(8).bool(message.includeSchemaInPrompt);
    }
    if (message.schema !== undefined) {
      writer.uint32(18).string(message.schema);
    }
    if (message.grammar !== undefined) {
      writer.uint32(26).string(message.grammar);
    }
    if (message.regex !== undefined) {
      writer.uint32(34).string(message.regex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StructuredOutputOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStructuredOutputOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.includeSchemaInPrompt = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.schema = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.grammar = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.regex = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StructuredOutputOptions {
    return {
      includeSchemaInPrompt: isSet(object.includeSchemaInPrompt)
        ? globalThis.Boolean(object.includeSchemaInPrompt)
        : isSet(object.include_schema_in_prompt)
        ? globalThis.Boolean(object.include_schema_in_prompt)
        : undefined,
      schema: isSet(object.schema) ? globalThis.String(object.schema) : undefined,
      grammar: isSet(object.grammar) ? globalThis.String(object.grammar) : undefined,
      regex: isSet(object.regex) ? globalThis.String(object.regex) : undefined,
    };
  },

  toJSON(message: StructuredOutputOptions): unknown {
    const obj: any = {};
    if (message.includeSchemaInPrompt !== undefined) {
      obj.includeSchemaInPrompt = message.includeSchemaInPrompt;
    }
    if (message.schema !== undefined) {
      obj.schema = message.schema;
    }
    if (message.grammar !== undefined) {
      obj.grammar = message.grammar;
    }
    if (message.regex !== undefined) {
      obj.regex = message.regex;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StructuredOutputOptions>, I>>(base?: I): StructuredOutputOptions {
    return StructuredOutputOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StructuredOutputOptions>, I>>(object: I): StructuredOutputOptions {
    const message = createBaseStructuredOutputOptions();
    message.includeSchemaInPrompt = object.includeSchemaInPrompt ?? undefined;
    message.schema = object.schema ?? undefined;
    message.grammar = object.grammar ?? undefined;
    message.regex = object.regex ?? undefined;
    return message;
  },
};

function createBaseStructuredOutputValidation(): StructuredOutputValidation {
  return {
    isValid: false,
    containsJson: false,
    rawOutput: undefined,
    extractedJson: undefined,
    validationErrors: [],
    validationTimeMs: 0,
    error: undefined,
  };
}

export const StructuredOutputValidation: MessageFns<StructuredOutputValidation> = {
  encode(message: StructuredOutputValidation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isValid !== false) {
      writer.uint32(8).bool(message.isValid);
    }
    if (message.containsJson !== false) {
      writer.uint32(16).bool(message.containsJson);
    }
    if (message.rawOutput !== undefined) {
      writer.uint32(26).string(message.rawOutput);
    }
    if (message.extractedJson !== undefined) {
      writer.uint32(34).string(message.extractedJson);
    }
    for (const v of message.validationErrors) {
      writer.uint32(42).string(v!);
    }
    if (message.validationTimeMs !== 0) {
      writer.uint32(48).int64(message.validationTimeMs);
    }
    if (message.error !== undefined) {
      SDKError.encode(message.error, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StructuredOutputValidation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStructuredOutputValidation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isValid = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.containsJson = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.rawOutput = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.extractedJson = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.validationErrors.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.validationTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.error = SDKError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StructuredOutputValidation {
    return {
      isValid: isSet(object.isValid)
        ? globalThis.Boolean(object.isValid)
        : isSet(object.is_valid)
        ? globalThis.Boolean(object.is_valid)
        : false,
      containsJson: isSet(object.containsJson)
        ? globalThis.Boolean(object.containsJson)
        : isSet(object.contains_json)
        ? globalThis.Boolean(object.contains_json)
        : false,
      rawOutput: isSet(object.rawOutput)
        ? globalThis.String(object.rawOutput)
        : isSet(object.raw_output)
        ? globalThis.String(object.raw_output)
        : undefined,
      extractedJson: isSet(object.extractedJson)
        ? globalThis.String(object.extractedJson)
        : isSet(object.extracted_json)
        ? globalThis.String(object.extracted_json)
        : undefined,
      validationErrors: globalThis.Array.isArray(object?.validationErrors)
        ? object.validationErrors.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.validation_errors)
        ? object.validation_errors.map((e: any) => globalThis.String(e))
        : [],
      validationTimeMs: isSet(object.validationTimeMs)
        ? globalThis.Number(object.validationTimeMs)
        : isSet(object.validation_time_ms)
        ? globalThis.Number(object.validation_time_ms)
        : 0,
      error: isSet(object.error) ? SDKError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: StructuredOutputValidation): unknown {
    const obj: any = {};
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    if (message.containsJson !== false) {
      obj.containsJson = message.containsJson;
    }
    if (message.rawOutput !== undefined) {
      obj.rawOutput = message.rawOutput;
    }
    if (message.extractedJson !== undefined) {
      obj.extractedJson = message.extractedJson;
    }
    if (message.validationErrors?.length) {
      obj.validationErrors = message.validationErrors;
    }
    if (message.validationTimeMs !== 0) {
      obj.validationTimeMs = Math.round(message.validationTimeMs);
    }
    if (message.error !== undefined) {
      obj.error = SDKError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StructuredOutputValidation>, I>>(base?: I): StructuredOutputValidation {
    return StructuredOutputValidation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StructuredOutputValidation>, I>>(object: I): StructuredOutputValidation {
    const message = createBaseStructuredOutputValidation();
    message.isValid = object.isValid ?? false;
    message.containsJson = object.containsJson ?? false;
    message.rawOutput = object.rawOutput ?? undefined;
    message.extractedJson = object.extractedJson ?? undefined;
    message.validationErrors = object.validationErrors?.map((e) => e) || [];
    message.validationTimeMs = object.validationTimeMs ?? 0;
    message.error = (object.error !== undefined && object.error !== null)
      ? SDKError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseStructuredOutputResult(): StructuredOutputResult {
  return { json: "", validation: undefined, rawText: undefined, error: undefined };
}

export const StructuredOutputResult: MessageFns<StructuredOutputResult> = {
  encode(message: StructuredOutputResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.json !== "") {
      writer.uint32(10).string(message.json);
    }
    if (message.validation !== undefined) {
      StructuredOutputValidation.encode(message.validation, writer.uint32(18).fork()).join();
    }
    if (message.rawText !== undefined) {
      writer.uint32(26).string(message.rawText);
    }
    if (message.error !== undefined) {
      SDKError.encode(message.error, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StructuredOutputResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStructuredOutputResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.json = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.validation = StructuredOutputValidation.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.rawText = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = SDKError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StructuredOutputResult {
    return {
      json: isSet(object.json) ? globalThis.String(object.json) : "",
      validation: isSet(object.validation) ? StructuredOutputValidation.fromJSON(object.validation) : undefined,
      rawText: isSet(object.rawText)
        ? globalThis.String(object.rawText)
        : isSet(object.raw_text)
        ? globalThis.String(object.raw_text)
        : undefined,
      error: isSet(object.error) ? SDKError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: StructuredOutputResult): unknown {
    const obj: any = {};
    if (message.json !== "") {
      obj.json = message.json;
    }
    if (message.validation !== undefined) {
      obj.validation = StructuredOutputValidation.toJSON(message.validation);
    }
    if (message.rawText !== undefined) {
      obj.rawText = message.rawText;
    }
    if (message.error !== undefined) {
      obj.error = SDKError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StructuredOutputResult>, I>>(base?: I): StructuredOutputResult {
    return StructuredOutputResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StructuredOutputResult>, I>>(object: I): StructuredOutputResult {
    const message = createBaseStructuredOutputResult();
    message.json = object.json ?? "";
    message.validation = (object.validation !== undefined && object.validation !== null)
      ? StructuredOutputValidation.fromPartial(object.validation)
      : undefined;
    message.rawText = object.rawText ?? undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? SDKError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseStructuredOutputParseRequest(): StructuredOutputParseRequest {
  return { requestId: "", text: "", options: undefined, metadata: {} };
}

export const StructuredOutputParseRequest: MessageFns<StructuredOutputParseRequest> = {
  encode(message: StructuredOutputParseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    if (message.options !== undefined) {
      StructuredOutputOptions.encode(message.options, writer.uint32(26).fork()).join();
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      StructuredOutputParseRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StructuredOutputParseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStructuredOutputParseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.options = StructuredOutputOptions.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = StructuredOutputParseRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.metadata[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StructuredOutputParseRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      options: isSet(object.options) ? StructuredOutputOptions.fromJSON(object.options) : undefined,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: StructuredOutputParseRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.options !== undefined) {
      obj.options = StructuredOutputOptions.toJSON(message.options);
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StructuredOutputParseRequest>, I>>(base?: I): StructuredOutputParseRequest {
    return StructuredOutputParseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StructuredOutputParseRequest>, I>>(object: I): StructuredOutputParseRequest {
    const message = createBaseStructuredOutputParseRequest();
    message.requestId = object.requestId ?? "";
    message.text = object.text ?? "";
    message.options = (object.options !== undefined && object.options !== null)
      ? StructuredOutputOptions.fromPartial(object.options)
      : undefined;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseStructuredOutputParseRequest_MetadataEntry(): StructuredOutputParseRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const StructuredOutputParseRequest_MetadataEntry: MessageFns<StructuredOutputParseRequest_MetadataEntry> = {
  encode(message: StructuredOutputParseRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StructuredOutputParseRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStructuredOutputParseRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StructuredOutputParseRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: StructuredOutputParseRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StructuredOutputParseRequest_MetadataEntry>, I>>(
    base?: I,
  ): StructuredOutputParseRequest_MetadataEntry {
    return StructuredOutputParseRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StructuredOutputParseRequest_MetadataEntry>, I>>(
    object: I,
  ): StructuredOutputParseRequest_MetadataEntry {
    const message = createBaseStructuredOutputParseRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseStructuredOutputPromptResult(): StructuredOutputPromptResult {
  return {
    preparedPrompt: "",
    systemPrompt: undefined,
    jsonSchema: undefined,
    regexPattern: undefined,
    grammar: undefined,
    error: undefined,
  };
}

export const StructuredOutputPromptResult: MessageFns<StructuredOutputPromptResult> = {
  encode(message: StructuredOutputPromptResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.preparedPrompt !== "") {
      writer.uint32(10).string(message.preparedPrompt);
    }
    if (message.systemPrompt !== undefined) {
      writer.uint32(18).string(message.systemPrompt);
    }
    if (message.jsonSchema !== undefined) {
      writer.uint32(26).string(message.jsonSchema);
    }
    if (message.regexPattern !== undefined) {
      writer.uint32(34).string(message.regexPattern);
    }
    if (message.grammar !== undefined) {
      writer.uint32(42).string(message.grammar);
    }
    if (message.error !== undefined) {
      SDKError.encode(message.error, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StructuredOutputPromptResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStructuredOutputPromptResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preparedPrompt = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.systemPrompt = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.jsonSchema = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.regexPattern = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.grammar = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.error = SDKError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StructuredOutputPromptResult {
    return {
      preparedPrompt: isSet(object.preparedPrompt)
        ? globalThis.String(object.preparedPrompt)
        : isSet(object.prepared_prompt)
        ? globalThis.String(object.prepared_prompt)
        : "",
      systemPrompt: isSet(object.systemPrompt)
        ? globalThis.String(object.systemPrompt)
        : isSet(object.system_prompt)
        ? globalThis.String(object.system_prompt)
        : undefined,
      jsonSchema: isSet(object.jsonSchema)
        ? globalThis.String(object.jsonSchema)
        : isSet(object.json_schema)
        ? globalThis.String(object.json_schema)
        : undefined,
      regexPattern: isSet(object.regexPattern)
        ? globalThis.String(object.regexPattern)
        : isSet(object.regex_pattern)
        ? globalThis.String(object.regex_pattern)
        : undefined,
      grammar: isSet(object.grammar) ? globalThis.String(object.grammar) : undefined,
      error: isSet(object.error) ? SDKError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: StructuredOutputPromptResult): unknown {
    const obj: any = {};
    if (message.preparedPrompt !== "") {
      obj.preparedPrompt = message.preparedPrompt;
    }
    if (message.systemPrompt !== undefined) {
      obj.systemPrompt = message.systemPrompt;
    }
    if (message.jsonSchema !== undefined) {
      obj.jsonSchema = message.jsonSchema;
    }
    if (message.regexPattern !== undefined) {
      obj.regexPattern = message.regexPattern;
    }
    if (message.grammar !== undefined) {
      obj.grammar = message.grammar;
    }
    if (message.error !== undefined) {
      obj.error = SDKError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StructuredOutputPromptResult>, I>>(base?: I): StructuredOutputPromptResult {
    return StructuredOutputPromptResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StructuredOutputPromptResult>, I>>(object: I): StructuredOutputPromptResult {
    const message = createBaseStructuredOutputPromptResult();
    message.preparedPrompt = object.preparedPrompt ?? "";
    message.systemPrompt = object.systemPrompt ?? undefined;
    message.jsonSchema = object.jsonSchema ?? undefined;
    message.regexPattern = object.regexPattern ?? undefined;
    message.grammar = object.grammar ?? undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? SDKError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
