// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: vad_options.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SDKError } from "./errors";
import {
  AudioEncoding,
  audioEncodingFromJSON,
  audioEncodingToJSON,
  InferenceFramework,
  inferenceFrameworkFromJSON,
  inferenceFrameworkToJSON,
} from "./model_types";

export const protobufPackage = "runanywhere.v1";

export enum SpeechActivityKind {
  SPEECH_ACTIVITY_KIND_UNSPECIFIED = 0,
  SPEECH_ACTIVITY_KIND_SPEECH_STARTED = 1,
  SPEECH_ACTIVITY_KIND_SPEECH_ENDED = 2,
  SPEECH_ACTIVITY_KIND_ONGOING = 3,
  UNRECOGNIZED = -1,
}

export function speechActivityKindFromJSON(object: any): SpeechActivityKind {
  switch (object) {
    case 0:
    case "SPEECH_ACTIVITY_KIND_UNSPECIFIED":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_UNSPECIFIED;
    case 1:
    case "SPEECH_ACTIVITY_KIND_SPEECH_STARTED":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_STARTED;
    case 2:
    case "SPEECH_ACTIVITY_KIND_SPEECH_ENDED":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_ENDED;
    case 3:
    case "SPEECH_ACTIVITY_KIND_ONGOING":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_ONGOING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SpeechActivityKind.UNRECOGNIZED;
  }
}

export function speechActivityKindToJSON(object: SpeechActivityKind): string {
  switch (object) {
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_UNSPECIFIED:
      return "SPEECH_ACTIVITY_KIND_UNSPECIFIED";
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_STARTED:
      return "SPEECH_ACTIVITY_KIND_SPEECH_STARTED";
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_ENDED:
      return "SPEECH_ACTIVITY_KIND_SPEECH_ENDED";
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_ONGOING:
      return "SPEECH_ACTIVITY_KIND_ONGOING";
    case SpeechActivityKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum VADStreamEventKind {
  VAD_STREAM_EVENT_KIND_UNSPECIFIED = 0,
  VAD_STREAM_EVENT_KIND_STARTED = 1,
  VAD_STREAM_EVENT_KIND_FRAME = 2,
  VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY = 3,
  VAD_STREAM_EVENT_KIND_STATISTICS = 4,
  VAD_STREAM_EVENT_KIND_STOPPED = 5,
  VAD_STREAM_EVENT_KIND_ERROR = 6,
  /**
   * VAD_STREAM_EVENT_KIND_BARGE_IN - Speech that interrupts active assistant playback. Downstream pipeline
   * also routes this through InterruptedEvent/InterruptReason.
   */
  VAD_STREAM_EVENT_KIND_BARGE_IN = 7,
  UNRECOGNIZED = -1,
}

export function vADStreamEventKindFromJSON(object: any): VADStreamEventKind {
  switch (object) {
    case 0:
    case "VAD_STREAM_EVENT_KIND_UNSPECIFIED":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_UNSPECIFIED;
    case 1:
    case "VAD_STREAM_EVENT_KIND_STARTED":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_STARTED;
    case 2:
    case "VAD_STREAM_EVENT_KIND_FRAME":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_FRAME;
    case 3:
    case "VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY;
    case 4:
    case "VAD_STREAM_EVENT_KIND_STATISTICS":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_STATISTICS;
    case 5:
    case "VAD_STREAM_EVENT_KIND_STOPPED":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_STOPPED;
    case 6:
    case "VAD_STREAM_EVENT_KIND_ERROR":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_ERROR;
    case 7:
    case "VAD_STREAM_EVENT_KIND_BARGE_IN":
      return VADStreamEventKind.VAD_STREAM_EVENT_KIND_BARGE_IN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VADStreamEventKind.UNRECOGNIZED;
  }
}

export function vADStreamEventKindToJSON(object: VADStreamEventKind): string {
  switch (object) {
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_UNSPECIFIED:
      return "VAD_STREAM_EVENT_KIND_UNSPECIFIED";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_STARTED:
      return "VAD_STREAM_EVENT_KIND_STARTED";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_FRAME:
      return "VAD_STREAM_EVENT_KIND_FRAME";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY:
      return "VAD_STREAM_EVENT_KIND_SPEECH_ACTIVITY";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_STATISTICS:
      return "VAD_STREAM_EVENT_KIND_STATISTICS";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_STOPPED:
      return "VAD_STREAM_EVENT_KIND_STOPPED";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_ERROR:
      return "VAD_STREAM_EVENT_KIND_ERROR";
    case VADStreamEventKind.VAD_STREAM_EVENT_KIND_BARGE_IN:
      return "VAD_STREAM_EVENT_KIND_BARGE_IN";
    case VADStreamEventKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Load-time configuration for a VAD instance. */
export interface VADConfiguration {
  /** Empty when using the built-in energy VAD. */
  modelId: string;
  sampleRate: number;
  /**
   * Milliseconds on the wire; Swift/Kotlin/Dart/C hold seconds, so generated
   * bindings divide by 1000 when they bind to those types.
   */
  frameLengthMs: number;
  /** Commons rejects values outside [0, 1] and warns below 0.002 or above 0.1. */
  activationThreshold: number;
  /**
   * Calibrate against ambient noise and scale the threshold by
   * calibration_multiplier.
   */
  enableAutoCalibration: boolean;
  /** threshold = ambient noise * multiplier */
  calibrationMultiplier: number;
  preferredFramework?:
    | InferenceFramework
    | undefined;
  /** For backend-specific VADs such as Silero ONNX. */
  modelPath?:
    | string
    | undefined;
  /** 0 = backend default, for both of these. */
  windowSizeSamples: number;
  maxSpeechDurationMs: number;
}

/** Per-call options. Field vocabulary follows LiveKit/Silero naming. */
export interface VADOptions {
  /** 0 = keep the configured threshold. */
  activationThreshold: number;
  minSpeechDurationMs: number;
  minSilenceDurationMs: number;
  /** 0 = backend default, for both of these. */
  maxSpeechDurationMs: number;
  /**
   * Audio retained before SPEECH_STARTED so segments don't clip the first
   * syllable.
   */
  prefixPaddingMs: number;
  includeStatistics: boolean;
}

export interface VADAudioSource {
  audioData?: Uint8Array | undefined;
  adapterHandle?: string | undefined;
  encoding: AudioEncoding;
  sampleRate: number;
  channels: number;
  frameOffsetMs: number;
}

export interface VADProcessRequest {
  requestId: string;
  audio?: VADAudioSource | undefined;
  options?: VADOptions | undefined;
  metadata: { [key: string]: string };
}

export interface VADProcessRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface VADResult {
  isSpeech: boolean;
  /** [0.0, 1.0], backend-dependent. */
  confidence: number;
  /** RMS energy of the analyzed frame. */
  energy: number;
  /** Length of the analyzed frame. */
  durationMs: number;
  /** Milliseconds since epoch. */
  timestampMs: number;
  /** 0 = unset. */
  startTimeMs: number;
  endTimeMs: number;
  statistics?: VADStatistics | undefined;
  error?: SDKError | undefined;
}

/** Exposed for debugging and waveform UIs. */
export interface VADStatistics {
  currentEnergy: number;
  currentThreshold: number;
  /** Ambient noise level captured by calibration. */
  ambientLevel: number;
  /** Moving-window average and peak. */
  recentAvg: number;
  recentMax: number;
  /** Zero = unset for energy-only implementations. */
  totalSpeechSegments: number;
  totalSpeechDurationMs: number;
  averageEnergy: number;
  peakEnergy: number;
}

/**
 * Narrow component-level transition. voice_events.proto's VADEvent carries the
 * broader pipeline taxonomy (BARGE_IN, END_OF_UTTERANCE) via VADStreamEventKind.
 */
export interface SpeechActivityEvent {
  eventType: SpeechActivityKind;
  /** Milliseconds since epoch. */
  timestampMs: number;
  /**
   * Length of the just-finished utterance on SPEECH_ENDED; zero on
   * SPEECH_STARTED.
   */
  durationMs: number;
  confidence: number;
  result?: VADResult | undefined;
  segmentId?: string | undefined;
}

export interface VADStreamEvent {
  timestampUs: number;
  requestId: string;
  kind: VADStreamEventKind;
  result?: VADResult | undefined;
  activity?: SpeechActivityEvent | undefined;
  statistics?: VADStatistics | undefined;
  error?: SDKError | undefined;
}

export interface VADServiceState {
  isReady: boolean;
  isSpeechActive: boolean;
  energyThreshold: number;
  sampleRate: number;
  frameLengthMs: number;
  currentModel?: string | undefined;
  error?: SDKError | undefined;
}

function createBaseVADConfiguration(): VADConfiguration {
  return {
    modelId: "",
    sampleRate: 0,
    frameLengthMs: 0,
    activationThreshold: 0,
    enableAutoCalibration: false,
    calibrationMultiplier: 0,
    preferredFramework: undefined,
    modelPath: undefined,
    windowSizeSamples: 0,
    maxSpeechDurationMs: 0,
  };
}

export const VADConfiguration: MessageFns<VADConfiguration> = {
  encode(message: VADConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(16).int32(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      writer.uint32(24).int32(message.frameLengthMs);
    }
    if (message.activationThreshold !== 0) {
      writer.uint32(37).float(message.activationThreshold);
    }
    if (message.enableAutoCalibration !== false) {
      writer.uint32(40).bool(message.enableAutoCalibration);
    }
    if (message.calibrationMultiplier !== 0) {
      writer.uint32(53).float(message.calibrationMultiplier);
    }
    if (message.preferredFramework !== undefined) {
      writer.uint32(56).int32(message.preferredFramework);
    }
    if (message.modelPath !== undefined) {
      writer.uint32(66).string(message.modelPath);
    }
    if (message.windowSizeSamples !== 0) {
      writer.uint32(72).int32(message.windowSizeSamples);
    }
    if (message.maxSpeechDurationMs !== 0) {
      writer.uint32(80).int32(message.maxSpeechDurationMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.frameLengthMs = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.activationThreshold = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.enableAutoCalibration = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.calibrationMultiplier = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.preferredFramework = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.modelPath = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.windowSizeSamples = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.maxSpeechDurationMs = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADConfiguration {
    return {
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      frameLengthMs: isSet(object.frameLengthMs)
        ? globalThis.Number(object.frameLengthMs)
        : isSet(object.frame_length_ms)
        ? globalThis.Number(object.frame_length_ms)
        : 0,
      activationThreshold: isSet(object.activationThreshold)
        ? globalThis.Number(object.activationThreshold)
        : isSet(object.activation_threshold)
        ? globalThis.Number(object.activation_threshold)
        : 0,
      enableAutoCalibration: isSet(object.enableAutoCalibration)
        ? globalThis.Boolean(object.enableAutoCalibration)
        : isSet(object.enable_auto_calibration)
        ? globalThis.Boolean(object.enable_auto_calibration)
        : false,
      calibrationMultiplier: isSet(object.calibrationMultiplier)
        ? globalThis.Number(object.calibrationMultiplier)
        : isSet(object.calibration_multiplier)
        ? globalThis.Number(object.calibration_multiplier)
        : 0,
      preferredFramework: isSet(object.preferredFramework)
        ? inferenceFrameworkFromJSON(object.preferredFramework)
        : isSet(object.preferred_framework)
        ? inferenceFrameworkFromJSON(object.preferred_framework)
        : undefined,
      modelPath: isSet(object.modelPath)
        ? globalThis.String(object.modelPath)
        : isSet(object.model_path)
        ? globalThis.String(object.model_path)
        : undefined,
      windowSizeSamples: isSet(object.windowSizeSamples)
        ? globalThis.Number(object.windowSizeSamples)
        : isSet(object.window_size_samples)
        ? globalThis.Number(object.window_size_samples)
        : 0,
      maxSpeechDurationMs: isSet(object.maxSpeechDurationMs)
        ? globalThis.Number(object.maxSpeechDurationMs)
        : isSet(object.max_speech_duration_ms)
        ? globalThis.Number(object.max_speech_duration_ms)
        : 0,
    };
  },

  toJSON(message: VADConfiguration): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      obj.frameLengthMs = Math.round(message.frameLengthMs);
    }
    if (message.activationThreshold !== 0) {
      obj.activationThreshold = message.activationThreshold;
    }
    if (message.enableAutoCalibration !== false) {
      obj.enableAutoCalibration = message.enableAutoCalibration;
    }
    if (message.calibrationMultiplier !== 0) {
      obj.calibrationMultiplier = message.calibrationMultiplier;
    }
    if (message.preferredFramework !== undefined) {
      obj.preferredFramework = inferenceFrameworkToJSON(message.preferredFramework);
    }
    if (message.modelPath !== undefined) {
      obj.modelPath = message.modelPath;
    }
    if (message.windowSizeSamples !== 0) {
      obj.windowSizeSamples = Math.round(message.windowSizeSamples);
    }
    if (message.maxSpeechDurationMs !== 0) {
      obj.maxSpeechDurationMs = Math.round(message.maxSpeechDurationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADConfiguration>, I>>(base?: I): VADConfiguration {
    return VADConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADConfiguration>, I>>(object: I): VADConfiguration {
    const message = createBaseVADConfiguration();
    message.modelId = object.modelId ?? "";
    message.sampleRate = object.sampleRate ?? 0;
    message.frameLengthMs = object.frameLengthMs ?? 0;
    message.activationThreshold = object.activationThreshold ?? 0;
    message.enableAutoCalibration = object.enableAutoCalibration ?? false;
    message.calibrationMultiplier = object.calibrationMultiplier ?? 0;
    message.preferredFramework = object.preferredFramework ?? undefined;
    message.modelPath = object.modelPath ?? undefined;
    message.windowSizeSamples = object.windowSizeSamples ?? 0;
    message.maxSpeechDurationMs = object.maxSpeechDurationMs ?? 0;
    return message;
  },
};

function createBaseVADOptions(): VADOptions {
  return {
    activationThreshold: 0,
    minSpeechDurationMs: 0,
    minSilenceDurationMs: 0,
    maxSpeechDurationMs: 0,
    prefixPaddingMs: 0,
    includeStatistics: false,
  };
}

export const VADOptions: MessageFns<VADOptions> = {
  encode(message: VADOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.activationThreshold !== 0) {
      writer.uint32(53).float(message.activationThreshold);
    }
    if (message.minSpeechDurationMs !== 0) {
      writer.uint32(16).int32(message.minSpeechDurationMs);
    }
    if (message.minSilenceDurationMs !== 0) {
      writer.uint32(24).int32(message.minSilenceDurationMs);
    }
    if (message.maxSpeechDurationMs !== 0) {
      writer.uint32(32).int32(message.maxSpeechDurationMs);
    }
    if (message.prefixPaddingMs !== 0) {
      writer.uint32(56).int32(message.prefixPaddingMs);
    }
    if (message.includeStatistics !== false) {
      writer.uint32(40).bool(message.includeStatistics);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.activationThreshold = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.minSpeechDurationMs = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.minSilenceDurationMs = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxSpeechDurationMs = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.prefixPaddingMs = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.includeStatistics = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADOptions {
    return {
      activationThreshold: isSet(object.activationThreshold)
        ? globalThis.Number(object.activationThreshold)
        : isSet(object.activation_threshold)
        ? globalThis.Number(object.activation_threshold)
        : 0,
      minSpeechDurationMs: isSet(object.minSpeechDurationMs)
        ? globalThis.Number(object.minSpeechDurationMs)
        : isSet(object.min_speech_duration_ms)
        ? globalThis.Number(object.min_speech_duration_ms)
        : 0,
      minSilenceDurationMs: isSet(object.minSilenceDurationMs)
        ? globalThis.Number(object.minSilenceDurationMs)
        : isSet(object.min_silence_duration_ms)
        ? globalThis.Number(object.min_silence_duration_ms)
        : 0,
      maxSpeechDurationMs: isSet(object.maxSpeechDurationMs)
        ? globalThis.Number(object.maxSpeechDurationMs)
        : isSet(object.max_speech_duration_ms)
        ? globalThis.Number(object.max_speech_duration_ms)
        : 0,
      prefixPaddingMs: isSet(object.prefixPaddingMs)
        ? globalThis.Number(object.prefixPaddingMs)
        : isSet(object.prefix_padding_ms)
        ? globalThis.Number(object.prefix_padding_ms)
        : 0,
      includeStatistics: isSet(object.includeStatistics)
        ? globalThis.Boolean(object.includeStatistics)
        : isSet(object.include_statistics)
        ? globalThis.Boolean(object.include_statistics)
        : false,
    };
  },

  toJSON(message: VADOptions): unknown {
    const obj: any = {};
    if (message.activationThreshold !== 0) {
      obj.activationThreshold = message.activationThreshold;
    }
    if (message.minSpeechDurationMs !== 0) {
      obj.minSpeechDurationMs = Math.round(message.minSpeechDurationMs);
    }
    if (message.minSilenceDurationMs !== 0) {
      obj.minSilenceDurationMs = Math.round(message.minSilenceDurationMs);
    }
    if (message.maxSpeechDurationMs !== 0) {
      obj.maxSpeechDurationMs = Math.round(message.maxSpeechDurationMs);
    }
    if (message.prefixPaddingMs !== 0) {
      obj.prefixPaddingMs = Math.round(message.prefixPaddingMs);
    }
    if (message.includeStatistics !== false) {
      obj.includeStatistics = message.includeStatistics;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADOptions>, I>>(base?: I): VADOptions {
    return VADOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADOptions>, I>>(object: I): VADOptions {
    const message = createBaseVADOptions();
    message.activationThreshold = object.activationThreshold ?? 0;
    message.minSpeechDurationMs = object.minSpeechDurationMs ?? 0;
    message.minSilenceDurationMs = object.minSilenceDurationMs ?? 0;
    message.maxSpeechDurationMs = object.maxSpeechDurationMs ?? 0;
    message.prefixPaddingMs = object.prefixPaddingMs ?? 0;
    message.includeStatistics = object.includeStatistics ?? false;
    return message;
  },
};

function createBaseVADAudioSource(): VADAudioSource {
  return { audioData: undefined, adapterHandle: undefined, encoding: 0, sampleRate: 0, channels: 0, frameOffsetMs: 0 };
}

export const VADAudioSource: MessageFns<VADAudioSource> = {
  encode(message: VADAudioSource, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audioData !== undefined) {
      writer.uint32(10).bytes(message.audioData);
    }
    if (message.adapterHandle !== undefined) {
      writer.uint32(18).string(message.adapterHandle);
    }
    if (message.encoding !== 0) {
      writer.uint32(24).int32(message.encoding);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(32).int32(message.sampleRate);
    }
    if (message.channels !== 0) {
      writer.uint32(40).int32(message.channels);
    }
    if (message.frameOffsetMs !== 0) {
      writer.uint32(48).int64(message.frameOffsetMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADAudioSource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADAudioSource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audioData = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.adapterHandle = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.encoding = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.channels = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.frameOffsetMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADAudioSource {
    return {
      audioData: isSet(object.audioData)
        ? bytesFromBase64(object.audioData)
        : isSet(object.audio_data)
        ? bytesFromBase64(object.audio_data)
        : undefined,
      adapterHandle: isSet(object.adapterHandle)
        ? globalThis.String(object.adapterHandle)
        : isSet(object.adapter_handle)
        ? globalThis.String(object.adapter_handle)
        : undefined,
      encoding: isSet(object.encoding) ? audioEncodingFromJSON(object.encoding) : 0,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      channels: isSet(object.channels) ? globalThis.Number(object.channels) : 0,
      frameOffsetMs: isSet(object.frameOffsetMs)
        ? globalThis.Number(object.frameOffsetMs)
        : isSet(object.frame_offset_ms)
        ? globalThis.Number(object.frame_offset_ms)
        : 0,
    };
  },

  toJSON(message: VADAudioSource): unknown {
    const obj: any = {};
    if (message.audioData !== undefined) {
      obj.audioData = base64FromBytes(message.audioData);
    }
    if (message.adapterHandle !== undefined) {
      obj.adapterHandle = message.adapterHandle;
    }
    if (message.encoding !== 0) {
      obj.encoding = audioEncodingToJSON(message.encoding);
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.channels !== 0) {
      obj.channels = Math.round(message.channels);
    }
    if (message.frameOffsetMs !== 0) {
      obj.frameOffsetMs = Math.round(message.frameOffsetMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADAudioSource>, I>>(base?: I): VADAudioSource {
    return VADAudioSource.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADAudioSource>, I>>(object: I): VADAudioSource {
    const message = createBaseVADAudioSource();
    message.audioData = object.audioData ?? undefined;
    message.adapterHandle = object.adapterHandle ?? undefined;
    message.encoding = object.encoding ?? 0;
    message.sampleRate = object.sampleRate ?? 0;
    message.channels = object.channels ?? 0;
    message.frameOffsetMs = object.frameOffsetMs ?? 0;
    return message;
  },
};

function createBaseVADProcessRequest(): VADProcessRequest {
  return { requestId: "", audio: undefined, options: undefined, metadata: {} };
}

export const VADProcessRequest: MessageFns<VADProcessRequest> = {
  encode(message: VADProcessRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.audio !== undefined) {
      VADAudioSource.encode(message.audio, writer.uint32(18).fork()).join();
    }
    if (message.options !== undefined) {
      VADOptions.encode(message.options, writer.uint32(26).fork()).join();
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      VADProcessRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADProcessRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADProcessRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.audio = VADAudioSource.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.options = VADOptions.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = VADProcessRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.metadata[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADProcessRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      audio: isSet(object.audio) ? VADAudioSource.fromJSON(object.audio) : undefined,
      options: isSet(object.options) ? VADOptions.fromJSON(object.options) : undefined,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: VADProcessRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.audio !== undefined) {
      obj.audio = VADAudioSource.toJSON(message.audio);
    }
    if (message.options !== undefined) {
      obj.options = VADOptions.toJSON(message.options);
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADProcessRequest>, I>>(base?: I): VADProcessRequest {
    return VADProcessRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADProcessRequest>, I>>(object: I): VADProcessRequest {
    const message = createBaseVADProcessRequest();
    message.requestId = object.requestId ?? "";
    message.audio = (object.audio !== undefined && object.audio !== null)
      ? VADAudioSource.fromPartial(object.audio)
      : undefined;
    message.options = (object.options !== undefined && object.options !== null)
      ? VADOptions.fromPartial(object.options)
      : undefined;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseVADProcessRequest_MetadataEntry(): VADProcessRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const VADProcessRequest_MetadataEntry: MessageFns<VADProcessRequest_MetadataEntry> = {
  encode(message: VADProcessRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADProcessRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADProcessRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADProcessRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: VADProcessRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADProcessRequest_MetadataEntry>, I>>(base?: I): VADProcessRequest_MetadataEntry {
    return VADProcessRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADProcessRequest_MetadataEntry>, I>>(
    object: I,
  ): VADProcessRequest_MetadataEntry {
    const message = createBaseVADProcessRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseVADResult(): VADResult {
  return {
    isSpeech: false,
    confidence: 0,
    energy: 0,
    durationMs: 0,
    timestampMs: 0,
    startTimeMs: 0,
    endTimeMs: 0,
    statistics: undefined,
    error: undefined,
  };
}

export const VADResult: MessageFns<VADResult> = {
  encode(message: VADResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isSpeech !== false) {
      writer.uint32(8).bool(message.isSpeech);
    }
    if (message.confidence !== 0) {
      writer.uint32(21).float(message.confidence);
    }
    if (message.energy !== 0) {
      writer.uint32(29).float(message.energy);
    }
    if (message.durationMs !== 0) {
      writer.uint32(32).int32(message.durationMs);
    }
    if (message.timestampMs !== 0) {
      writer.uint32(40).int64(message.timestampMs);
    }
    if (message.startTimeMs !== 0) {
      writer.uint32(48).int64(message.startTimeMs);
    }
    if (message.endTimeMs !== 0) {
      writer.uint32(56).int64(message.endTimeMs);
    }
    if (message.statistics !== undefined) {
      VADStatistics.encode(message.statistics, writer.uint32(66).fork()).join();
    }
    if (message.error !== undefined) {
      SDKError.encode(message.error, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isSpeech = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.energy = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.durationMs = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestampMs = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.startTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.endTimeMs = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.statistics = VADStatistics.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.error = SDKError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADResult {
    return {
      isSpeech: isSet(object.isSpeech)
        ? globalThis.Boolean(object.isSpeech)
        : isSet(object.is_speech)
        ? globalThis.Boolean(object.is_speech)
        : false,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      energy: isSet(object.energy) ? globalThis.Number(object.energy) : 0,
      durationMs: isSet(object.durationMs)
        ? globalThis.Number(object.durationMs)
        : isSet(object.duration_ms)
        ? globalThis.Number(object.duration_ms)
        : 0,
      timestampMs: isSet(object.timestampMs)
        ? globalThis.Number(object.timestampMs)
        : isSet(object.timestamp_ms)
        ? globalThis.Number(object.timestamp_ms)
        : 0,
      startTimeMs: isSet(object.startTimeMs)
        ? globalThis.Number(object.startTimeMs)
        : isSet(object.start_time_ms)
        ? globalThis.Number(object.start_time_ms)
        : 0,
      endTimeMs: isSet(object.endTimeMs)
        ? globalThis.Number(object.endTimeMs)
        : isSet(object.end_time_ms)
        ? globalThis.Number(object.end_time_ms)
        : 0,
      statistics: isSet(object.statistics) ? VADStatistics.fromJSON(object.statistics) : undefined,
      error: isSet(object.error) ? SDKError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: VADResult): unknown {
    const obj: any = {};
    if (message.isSpeech !== false) {
      obj.isSpeech = message.isSpeech;
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.energy !== 0) {
      obj.energy = message.energy;
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    if (message.timestampMs !== 0) {
      obj.timestampMs = Math.round(message.timestampMs);
    }
    if (message.startTimeMs !== 0) {
      obj.startTimeMs = Math.round(message.startTimeMs);
    }
    if (message.endTimeMs !== 0) {
      obj.endTimeMs = Math.round(message.endTimeMs);
    }
    if (message.statistics !== undefined) {
      obj.statistics = VADStatistics.toJSON(message.statistics);
    }
    if (message.error !== undefined) {
      obj.error = SDKError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADResult>, I>>(base?: I): VADResult {
    return VADResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADResult>, I>>(object: I): VADResult {
    const message = createBaseVADResult();
    message.isSpeech = object.isSpeech ?? false;
    message.confidence = object.confidence ?? 0;
    message.energy = object.energy ?? 0;
    message.durationMs = object.durationMs ?? 0;
    message.timestampMs = object.timestampMs ?? 0;
    message.startTimeMs = object.startTimeMs ?? 0;
    message.endTimeMs = object.endTimeMs ?? 0;
    message.statistics = (object.statistics !== undefined && object.statistics !== null)
      ? VADStatistics.fromPartial(object.statistics)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? SDKError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseVADStatistics(): VADStatistics {
  return {
    currentEnergy: 0,
    currentThreshold: 0,
    ambientLevel: 0,
    recentAvg: 0,
    recentMax: 0,
    totalSpeechSegments: 0,
    totalSpeechDurationMs: 0,
    averageEnergy: 0,
    peakEnergy: 0,
  };
}

export const VADStatistics: MessageFns<VADStatistics> = {
  encode(message: VADStatistics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.currentEnergy !== 0) {
      writer.uint32(13).float(message.currentEnergy);
    }
    if (message.currentThreshold !== 0) {
      writer.uint32(21).float(message.currentThreshold);
    }
    if (message.ambientLevel !== 0) {
      writer.uint32(29).float(message.ambientLevel);
    }
    if (message.recentAvg !== 0) {
      writer.uint32(37).float(message.recentAvg);
    }
    if (message.recentMax !== 0) {
      writer.uint32(45).float(message.recentMax);
    }
    if (message.totalSpeechSegments !== 0) {
      writer.uint32(48).int32(message.totalSpeechSegments);
    }
    if (message.totalSpeechDurationMs !== 0) {
      writer.uint32(56).int64(message.totalSpeechDurationMs);
    }
    if (message.averageEnergy !== 0) {
      writer.uint32(69).float(message.averageEnergy);
    }
    if (message.peakEnergy !== 0) {
      writer.uint32(77).float(message.peakEnergy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADStatistics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADStatistics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.currentEnergy = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.currentThreshold = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.ambientLevel = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.recentAvg = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.recentMax = reader.float();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalSpeechSegments = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalSpeechDurationMs = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.averageEnergy = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.peakEnergy = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADStatistics {
    return {
      currentEnergy: isSet(object.currentEnergy)
        ? globalThis.Number(object.currentEnergy)
        : isSet(object.current_energy)
        ? globalThis.Number(object.current_energy)
        : 0,
      currentThreshold: isSet(object.currentThreshold)
        ? globalThis.Number(object.currentThreshold)
        : isSet(object.current_threshold)
        ? globalThis.Number(object.current_threshold)
        : 0,
      ambientLevel: isSet(object.ambientLevel)
        ? globalThis.Number(object.ambientLevel)
        : isSet(object.ambient_level)
        ? globalThis.Number(object.ambient_level)
        : 0,
      recentAvg: isSet(object.recentAvg)
        ? globalThis.Number(object.recentAvg)
        : isSet(object.recent_avg)
        ? globalThis.Number(object.recent_avg)
        : 0,
      recentMax: isSet(object.recentMax)
        ? globalThis.Number(object.recentMax)
        : isSet(object.recent_max)
        ? globalThis.Number(object.recent_max)
        : 0,
      totalSpeechSegments: isSet(object.totalSpeechSegments)
        ? globalThis.Number(object.totalSpeechSegments)
        : isSet(object.total_speech_segments)
        ? globalThis.Number(object.total_speech_segments)
        : 0,
      totalSpeechDurationMs: isSet(object.totalSpeechDurationMs)
        ? globalThis.Number(object.totalSpeechDurationMs)
        : isSet(object.total_speech_duration_ms)
        ? globalThis.Number(object.total_speech_duration_ms)
        : 0,
      averageEnergy: isSet(object.averageEnergy)
        ? globalThis.Number(object.averageEnergy)
        : isSet(object.average_energy)
        ? globalThis.Number(object.average_energy)
        : 0,
      peakEnergy: isSet(object.peakEnergy)
        ? globalThis.Number(object.peakEnergy)
        : isSet(object.peak_energy)
        ? globalThis.Number(object.peak_energy)
        : 0,
    };
  },

  toJSON(message: VADStatistics): unknown {
    const obj: any = {};
    if (message.currentEnergy !== 0) {
      obj.currentEnergy = message.currentEnergy;
    }
    if (message.currentThreshold !== 0) {
      obj.currentThreshold = message.currentThreshold;
    }
    if (message.ambientLevel !== 0) {
      obj.ambientLevel = message.ambientLevel;
    }
    if (message.recentAvg !== 0) {
      obj.recentAvg = message.recentAvg;
    }
    if (message.recentMax !== 0) {
      obj.recentMax = message.recentMax;
    }
    if (message.totalSpeechSegments !== 0) {
      obj.totalSpeechSegments = Math.round(message.totalSpeechSegments);
    }
    if (message.totalSpeechDurationMs !== 0) {
      obj.totalSpeechDurationMs = Math.round(message.totalSpeechDurationMs);
    }
    if (message.averageEnergy !== 0) {
      obj.averageEnergy = message.averageEnergy;
    }
    if (message.peakEnergy !== 0) {
      obj.peakEnergy = message.peakEnergy;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADStatistics>, I>>(base?: I): VADStatistics {
    return VADStatistics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADStatistics>, I>>(object: I): VADStatistics {
    const message = createBaseVADStatistics();
    message.currentEnergy = object.currentEnergy ?? 0;
    message.currentThreshold = object.currentThreshold ?? 0;
    message.ambientLevel = object.ambientLevel ?? 0;
    message.recentAvg = object.recentAvg ?? 0;
    message.recentMax = object.recentMax ?? 0;
    message.totalSpeechSegments = object.totalSpeechSegments ?? 0;
    message.totalSpeechDurationMs = object.totalSpeechDurationMs ?? 0;
    message.averageEnergy = object.averageEnergy ?? 0;
    message.peakEnergy = object.peakEnergy ?? 0;
    return message;
  },
};

function createBaseSpeechActivityEvent(): SpeechActivityEvent {
  return { eventType: 0, timestampMs: 0, durationMs: 0, confidence: 0, result: undefined, segmentId: undefined };
}

export const SpeechActivityEvent: MessageFns<SpeechActivityEvent> = {
  encode(message: SpeechActivityEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventType !== 0) {
      writer.uint32(8).int32(message.eventType);
    }
    if (message.timestampMs !== 0) {
      writer.uint32(16).int64(message.timestampMs);
    }
    if (message.durationMs !== 0) {
      writer.uint32(24).int32(message.durationMs);
    }
    if (message.confidence !== 0) {
      writer.uint32(37).float(message.confidence);
    }
    if (message.result !== undefined) {
      VADResult.encode(message.result, writer.uint32(42).fork()).join();
    }
    if (message.segmentId !== undefined) {
      writer.uint32(50).string(message.segmentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeechActivityEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeechActivityEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.eventType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestampMs = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.durationMs = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.confidence = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.result = VADResult.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.segmentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeechActivityEvent {
    return {
      eventType: isSet(object.eventType)
        ? speechActivityKindFromJSON(object.eventType)
        : isSet(object.event_type)
        ? speechActivityKindFromJSON(object.event_type)
        : 0,
      timestampMs: isSet(object.timestampMs)
        ? globalThis.Number(object.timestampMs)
        : isSet(object.timestamp_ms)
        ? globalThis.Number(object.timestamp_ms)
        : 0,
      durationMs: isSet(object.durationMs)
        ? globalThis.Number(object.durationMs)
        : isSet(object.duration_ms)
        ? globalThis.Number(object.duration_ms)
        : 0,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      result: isSet(object.result) ? VADResult.fromJSON(object.result) : undefined,
      segmentId: isSet(object.segmentId)
        ? globalThis.String(object.segmentId)
        : isSet(object.segment_id)
        ? globalThis.String(object.segment_id)
        : undefined,
    };
  },

  toJSON(message: SpeechActivityEvent): unknown {
    const obj: any = {};
    if (message.eventType !== 0) {
      obj.eventType = speechActivityKindToJSON(message.eventType);
    }
    if (message.timestampMs !== 0) {
      obj.timestampMs = Math.round(message.timestampMs);
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.result !== undefined) {
      obj.result = VADResult.toJSON(message.result);
    }
    if (message.segmentId !== undefined) {
      obj.segmentId = message.segmentId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeechActivityEvent>, I>>(base?: I): SpeechActivityEvent {
    return SpeechActivityEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeechActivityEvent>, I>>(object: I): SpeechActivityEvent {
    const message = createBaseSpeechActivityEvent();
    message.eventType = object.eventType ?? 0;
    message.timestampMs = object.timestampMs ?? 0;
    message.durationMs = object.durationMs ?? 0;
    message.confidence = object.confidence ?? 0;
    message.result = (object.result !== undefined && object.result !== null)
      ? VADResult.fromPartial(object.result)
      : undefined;
    message.segmentId = object.segmentId ?? undefined;
    return message;
  },
};

function createBaseVADStreamEvent(): VADStreamEvent {
  return {
    timestampUs: 0,
    requestId: "",
    kind: 0,
    result: undefined,
    activity: undefined,
    statistics: undefined,
    error: undefined,
  };
}

export const VADStreamEvent: MessageFns<VADStreamEvent> = {
  encode(message: VADStreamEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestampUs !== 0) {
      writer.uint32(16).int64(message.timestampUs);
    }
    if (message.requestId !== "") {
      writer.uint32(26).string(message.requestId);
    }
    if (message.kind !== 0) {
      writer.uint32(32).int32(message.kind);
    }
    if (message.result !== undefined) {
      VADResult.encode(message.result, writer.uint32(42).fork()).join();
    }
    if (message.activity !== undefined) {
      SpeechActivityEvent.encode(message.activity, writer.uint32(50).fork()).join();
    }
    if (message.statistics !== undefined) {
      VADStatistics.encode(message.statistics, writer.uint32(58).fork()).join();
    }
    if (message.error !== undefined) {
      SDKError.encode(message.error, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADStreamEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADStreamEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestampUs = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.kind = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.result = VADResult.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.activity = SpeechActivityEvent.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.statistics = VADStatistics.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.error = SDKError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADStreamEvent {
    return {
      timestampUs: isSet(object.timestampUs)
        ? globalThis.Number(object.timestampUs)
        : isSet(object.timestamp_us)
        ? globalThis.Number(object.timestamp_us)
        : 0,
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      kind: isSet(object.kind) ? vADStreamEventKindFromJSON(object.kind) : 0,
      result: isSet(object.result) ? VADResult.fromJSON(object.result) : undefined,
      activity: isSet(object.activity) ? SpeechActivityEvent.fromJSON(object.activity) : undefined,
      statistics: isSet(object.statistics) ? VADStatistics.fromJSON(object.statistics) : undefined,
      error: isSet(object.error) ? SDKError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: VADStreamEvent): unknown {
    const obj: any = {};
    if (message.timestampUs !== 0) {
      obj.timestampUs = Math.round(message.timestampUs);
    }
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.kind !== 0) {
      obj.kind = vADStreamEventKindToJSON(message.kind);
    }
    if (message.result !== undefined) {
      obj.result = VADResult.toJSON(message.result);
    }
    if (message.activity !== undefined) {
      obj.activity = SpeechActivityEvent.toJSON(message.activity);
    }
    if (message.statistics !== undefined) {
      obj.statistics = VADStatistics.toJSON(message.statistics);
    }
    if (message.error !== undefined) {
      obj.error = SDKError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADStreamEvent>, I>>(base?: I): VADStreamEvent {
    return VADStreamEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADStreamEvent>, I>>(object: I): VADStreamEvent {
    const message = createBaseVADStreamEvent();
    message.timestampUs = object.timestampUs ?? 0;
    message.requestId = object.requestId ?? "";
    message.kind = object.kind ?? 0;
    message.result = (object.result !== undefined && object.result !== null)
      ? VADResult.fromPartial(object.result)
      : undefined;
    message.activity = (object.activity !== undefined && object.activity !== null)
      ? SpeechActivityEvent.fromPartial(object.activity)
      : undefined;
    message.statistics = (object.statistics !== undefined && object.statistics !== null)
      ? VADStatistics.fromPartial(object.statistics)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? SDKError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseVADServiceState(): VADServiceState {
  return {
    isReady: false,
    isSpeechActive: false,
    energyThreshold: 0,
    sampleRate: 0,
    frameLengthMs: 0,
    currentModel: undefined,
    error: undefined,
  };
}

export const VADServiceState: MessageFns<VADServiceState> = {
  encode(message: VADServiceState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isReady !== false) {
      writer.uint32(8).bool(message.isReady);
    }
    if (message.isSpeechActive !== false) {
      writer.uint32(16).bool(message.isSpeechActive);
    }
    if (message.energyThreshold !== 0) {
      writer.uint32(29).float(message.energyThreshold);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(32).int32(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      writer.uint32(40).int32(message.frameLengthMs);
    }
    if (message.currentModel !== undefined) {
      writer.uint32(50).string(message.currentModel);
    }
    if (message.error !== undefined) {
      SDKError.encode(message.error, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VADServiceState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADServiceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isReady = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isSpeechActive = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.energyThreshold = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.frameLengthMs = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.currentModel = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.error = SDKError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADServiceState {
    return {
      isReady: isSet(object.isReady)
        ? globalThis.Boolean(object.isReady)
        : isSet(object.is_ready)
        ? globalThis.Boolean(object.is_ready)
        : false,
      isSpeechActive: isSet(object.isSpeechActive)
        ? globalThis.Boolean(object.isSpeechActive)
        : isSet(object.is_speech_active)
        ? globalThis.Boolean(object.is_speech_active)
        : false,
      energyThreshold: isSet(object.energyThreshold)
        ? globalThis.Number(object.energyThreshold)
        : isSet(object.energy_threshold)
        ? globalThis.Number(object.energy_threshold)
        : 0,
      sampleRate: isSet(object.sampleRate)
        ? globalThis.Number(object.sampleRate)
        : isSet(object.sample_rate)
        ? globalThis.Number(object.sample_rate)
        : 0,
      frameLengthMs: isSet(object.frameLengthMs)
        ? globalThis.Number(object.frameLengthMs)
        : isSet(object.frame_length_ms)
        ? globalThis.Number(object.frame_length_ms)
        : 0,
      currentModel: isSet(object.currentModel)
        ? globalThis.String(object.currentModel)
        : isSet(object.current_model)
        ? globalThis.String(object.current_model)
        : undefined,
      error: isSet(object.error) ? SDKError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: VADServiceState): unknown {
    const obj: any = {};
    if (message.isReady !== false) {
      obj.isReady = message.isReady;
    }
    if (message.isSpeechActive !== false) {
      obj.isSpeechActive = message.isSpeechActive;
    }
    if (message.energyThreshold !== 0) {
      obj.energyThreshold = message.energyThreshold;
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      obj.frameLengthMs = Math.round(message.frameLengthMs);
    }
    if (message.currentModel !== undefined) {
      obj.currentModel = message.currentModel;
    }
    if (message.error !== undefined) {
      obj.error = SDKError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADServiceState>, I>>(base?: I): VADServiceState {
    return VADServiceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADServiceState>, I>>(object: I): VADServiceState {
    const message = createBaseVADServiceState();
    message.isReady = object.isReady ?? false;
    message.isSpeechActive = object.isSpeechActive ?? false;
    message.energyThreshold = object.energyThreshold ?? 0;
    message.sampleRate = object.sampleRate ?? 0;
    message.frameLengthMs = object.frameLengthMs ?? 0;
    message.currentModel = object.currentModel ?? undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? SDKError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
