// GENERATED by idl/codegen/generate_ts_convenience.py — DO NOT EDIT.
//
// Source: idl/sdk_events.proto
//
// Convenience helpers derived from RunAnywhere's `rac_*` proto
// annotations (see idl/rac_options.proto):
//   * `<enumName>WireString`         (rac_wire_string)
//   * `<enumName>FromWireString`     (reverse of rac_wire_string)
//   * `<enumName>DisplayName`        (rac_display_name)
//   * `<enumName>AnalyticsKey`       (rac_analytics_key)
//   * `<msgName>Defaults`            (rac_default)
//   * `validate<MsgName>`            (rac_required / rac_min / rac_max /
//                                     rac_min_float / rac_max_float)

/* eslint-disable */

import { SDKComponent } from '../sdk_events';

export const sDKComponentWireString = (e: SDKComponent): string => {
  switch (e) {
    case SDKComponent.SDK_COMPONENT_UNSPECIFIED:
      return 'unspecified';
    case SDKComponent.SDK_COMPONENT_STT:
      return 'stt';
    case SDKComponent.SDK_COMPONENT_TTS:
      return 'tts';
    case SDKComponent.SDK_COMPONENT_VAD:
      return 'vad';
    case SDKComponent.SDK_COMPONENT_LLM:
      return 'llm';
    case SDKComponent.SDK_COMPONENT_VLM:
      return 'vlm';
    case SDKComponent.SDK_COMPONENT_DIFFUSION:
      return 'diffusion';
    case SDKComponent.SDK_COMPONENT_RAG:
      return 'rag';
    case SDKComponent.SDK_COMPONENT_EMBEDDINGS:
      return 'embeddings';
    case SDKComponent.SDK_COMPONENT_VOICE_AGENT:
      return 'voice_agent';
    case SDKComponent.SDK_COMPONENT_WAKEWORD:
      return 'wakeword';
    case SDKComponent.SDK_COMPONENT_SPEAKER_DIARIZATION:
      return 'speaker_diarization';
    case SDKComponent.SDK_COMPONENT_SEMANTIC_SEGMENTATION:
      return 'semantic_segmentation';
    case SDKComponent.SDK_COMPONENT_RERANK:
      return 'rerank';
    default:
      return '';
  }
};

export const sDKComponentFromWireString = (s: string): SDKComponent | undefined => {
  switch (s.toLowerCase()) {
    case 'unspecified':
      return SDKComponent.SDK_COMPONENT_UNSPECIFIED;
    case 'stt':
      return SDKComponent.SDK_COMPONENT_STT;
    case 'tts':
      return SDKComponent.SDK_COMPONENT_TTS;
    case 'vad':
      return SDKComponent.SDK_COMPONENT_VAD;
    case 'llm':
      return SDKComponent.SDK_COMPONENT_LLM;
    case 'vlm':
      return SDKComponent.SDK_COMPONENT_VLM;
    case 'diffusion':
      return SDKComponent.SDK_COMPONENT_DIFFUSION;
    case 'rag':
      return SDKComponent.SDK_COMPONENT_RAG;
    case 'embeddings':
      return SDKComponent.SDK_COMPONENT_EMBEDDINGS;
    case 'voice_agent':
      return SDKComponent.SDK_COMPONENT_VOICE_AGENT;
    case 'wakeword':
      return SDKComponent.SDK_COMPONENT_WAKEWORD;
    case 'speaker_diarization':
      return SDKComponent.SDK_COMPONENT_SPEAKER_DIARIZATION;
    case 'semantic_segmentation':
      return SDKComponent.SDK_COMPONENT_SEMANTIC_SEGMENTATION;
    case 'rerank':
      return SDKComponent.SDK_COMPONENT_RERANK;
    default:
      return undefined;
  }
};
