// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: finish_reason.proto

/* eslint-disable */

export const protobufPackage = "runanywhere.v1";

/**
 * One declared vocabulary, used in every place a finish reason is reported
 * on the LLM generation path (LLMGenerationResult, LLMStreamEvent,
 * ToolCallingResult).
 */
export enum FinishReason {
  FINISH_REASON_UNSPECIFIED = 0,
  /** FINISH_REASON_STOP - End-of-turn token. OpenAI "stop" / Anthropic "end_turn". */
  FINISH_REASON_STOP = 1,
  /** FINISH_REASON_LENGTH - Hit max_output_tokens. OpenAI "length" / Anthropic "max_tokens". */
  FINISH_REASON_LENGTH = 2,
  /** FINISH_REASON_STOP_SEQUENCE - One of options.stop_sequences fired; see `stop_sequence`. */
  FINISH_REASON_STOP_SEQUENCE = 3,
  /** FINISH_REASON_TOOL_CALLS - Model wants a tool run before it can continue. */
  FINISH_REASON_TOOL_CALLS = 4,
  /** FINISH_REASON_CANCELLED - Caller cancelled. No cloud analogue. */
  FINISH_REASON_CANCELLED = 5,
  /** FINISH_REASON_CONTEXT_OVERFLOW - Conversation exceeded the allocated context window. */
  FINISH_REASON_CONTEXT_OVERFLOW = 6,
  /** FINISH_REASON_ERROR - Generation failed; see `error`. */
  FINISH_REASON_ERROR = 7,
  UNRECOGNIZED = -1,
}

export function finishReasonFromJSON(object: any): FinishReason {
  switch (object) {
    case 0:
    case "FINISH_REASON_UNSPECIFIED":
      return FinishReason.FINISH_REASON_UNSPECIFIED;
    case 1:
    case "FINISH_REASON_STOP":
      return FinishReason.FINISH_REASON_STOP;
    case 2:
    case "FINISH_REASON_LENGTH":
      return FinishReason.FINISH_REASON_LENGTH;
    case 3:
    case "FINISH_REASON_STOP_SEQUENCE":
      return FinishReason.FINISH_REASON_STOP_SEQUENCE;
    case 4:
    case "FINISH_REASON_TOOL_CALLS":
      return FinishReason.FINISH_REASON_TOOL_CALLS;
    case 5:
    case "FINISH_REASON_CANCELLED":
      return FinishReason.FINISH_REASON_CANCELLED;
    case 6:
    case "FINISH_REASON_CONTEXT_OVERFLOW":
      return FinishReason.FINISH_REASON_CONTEXT_OVERFLOW;
    case 7:
    case "FINISH_REASON_ERROR":
      return FinishReason.FINISH_REASON_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FinishReason.UNRECOGNIZED;
  }
}

export function finishReasonToJSON(object: FinishReason): string {
  switch (object) {
    case FinishReason.FINISH_REASON_UNSPECIFIED:
      return "FINISH_REASON_UNSPECIFIED";
    case FinishReason.FINISH_REASON_STOP:
      return "FINISH_REASON_STOP";
    case FinishReason.FINISH_REASON_LENGTH:
      return "FINISH_REASON_LENGTH";
    case FinishReason.FINISH_REASON_STOP_SEQUENCE:
      return "FINISH_REASON_STOP_SEQUENCE";
    case FinishReason.FINISH_REASON_TOOL_CALLS:
      return "FINISH_REASON_TOOL_CALLS";
    case FinishReason.FINISH_REASON_CANCELLED:
      return "FINISH_REASON_CANCELLED";
    case FinishReason.FINISH_REASON_CONTEXT_OVERFLOW:
      return "FINISH_REASON_CONTEXT_OVERFLOW";
    case FinishReason.FINISH_REASON_ERROR:
      return "FINISH_REASON_ERROR";
    case FinishReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
