// VENDORED from @runanywhere/proto-ts (sdk/shared/proto-ts, generated from
// idl/hardware_profile.proto). Copied verbatim because @runanywhere/electron is a standalone
// package outside the monorepo's proto-ts workspace, so it can't consume the
// shared package via workspace resolution. Regenerate by re-copying the shared
// file — do NOT hand-edit. Only runtime dep is @bufbuild/protobuf (pure TS).
//
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: hardware_profile.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { NPUChip, nPUChipFromJSON, nPUChipToJSON } from "./storage_types";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * Hardware acceleration preference for inference. Device CLASS, not graphics
 * API. A hint, never a hard requirement — the runtime may fall back.
 * UNSPECIFIED means "you choose".
 *
 * Canonical single enum. It lives in this file rather than model_types.proto
 * because model_types.proto already imports this file; placing it here avoids
 * a cyclic import.
 * ---------------------------------------------------------------------------
 */
export enum AccelerationPreference {
  /** ACCELERATION_PREFERENCE_UNSPECIFIED - let the runtime choose */
  ACCELERATION_PREFERENCE_UNSPECIFIED = 0,
  /** ACCELERATION_PREFERENCE_AUTO - DEPRECATED: alias of UNSPECIFIED */
  ACCELERATION_PREFERENCE_AUTO = 1,
  ACCELERATION_PREFERENCE_CPU = 2,
  /** ACCELERATION_PREFERENCE_GPU - covers Metal / Vulkan / WebGPU */
  ACCELERATION_PREFERENCE_GPU = 3,
  /**
   * ACCELERATION_PREFERENCE_NPU - WEBGPU / METAL / VULKAN were removed: they are spellings of GPU, not
   * device classes. The concrete API is the runtime's choice; pass vendor
   * knobs as engine options instead.
   */
  ACCELERATION_PREFERENCE_NPU = 4,
  UNRECOGNIZED = -1,
}

export function accelerationPreferenceFromJSON(object: any): AccelerationPreference {
  switch (object) {
    case 0:
    case "ACCELERATION_PREFERENCE_UNSPECIFIED":
      return AccelerationPreference.ACCELERATION_PREFERENCE_UNSPECIFIED;
    case 1:
    case "ACCELERATION_PREFERENCE_AUTO":
      return AccelerationPreference.ACCELERATION_PREFERENCE_AUTO;
    case 2:
    case "ACCELERATION_PREFERENCE_CPU":
      return AccelerationPreference.ACCELERATION_PREFERENCE_CPU;
    case 3:
    case "ACCELERATION_PREFERENCE_GPU":
      return AccelerationPreference.ACCELERATION_PREFERENCE_GPU;
    case 4:
    case "ACCELERATION_PREFERENCE_NPU":
      return AccelerationPreference.ACCELERATION_PREFERENCE_NPU;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AccelerationPreference.UNRECOGNIZED;
  }
}

export function accelerationPreferenceToJSON(object: AccelerationPreference): string {
  switch (object) {
    case AccelerationPreference.ACCELERATION_PREFERENCE_UNSPECIFIED:
      return "ACCELERATION_PREFERENCE_UNSPECIFIED";
    case AccelerationPreference.ACCELERATION_PREFERENCE_AUTO:
      return "ACCELERATION_PREFERENCE_AUTO";
    case AccelerationPreference.ACCELERATION_PREFERENCE_CPU:
      return "ACCELERATION_PREFERENCE_CPU";
    case AccelerationPreference.ACCELERATION_PREFERENCE_GPU:
      return "ACCELERATION_PREFERENCE_GPU";
    case AccelerationPreference.ACCELERATION_PREFERENCE_NPU:
      return "ACCELERATION_PREFERENCE_NPU";
    case AccelerationPreference.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Pre-flight Qualcomm Hexagon NPU probe. Mirrors QHexRT's engine-owned C ABI
 * (`rac/qhexrt/rac_qhexrt.h`) and is serialized by
 * rac_qhexrt_probe_proto(). Enum values equal the Hexagon HTP version number
 * to stay in lock-step with rac_qhexrt_hexagon_arch_t.
 */
export enum HexagonArch {
  HEXAGON_ARCH_UNKNOWN = 0,
  HEXAGON_ARCH_V68 = 68,
  HEXAGON_ARCH_V69 = 69,
  HEXAGON_ARCH_V73 = 73,
  HEXAGON_ARCH_V75 = 75,
  HEXAGON_ARCH_V79 = 79,
  HEXAGON_ARCH_V81 = 81,
  UNRECOGNIZED = -1,
}

export function hexagonArchFromJSON(object: any): HexagonArch {
  switch (object) {
    case 0:
    case "HEXAGON_ARCH_UNKNOWN":
      return HexagonArch.HEXAGON_ARCH_UNKNOWN;
    case 68:
    case "HEXAGON_ARCH_V68":
      return HexagonArch.HEXAGON_ARCH_V68;
    case 69:
    case "HEXAGON_ARCH_V69":
      return HexagonArch.HEXAGON_ARCH_V69;
    case 73:
    case "HEXAGON_ARCH_V73":
      return HexagonArch.HEXAGON_ARCH_V73;
    case 75:
    case "HEXAGON_ARCH_V75":
      return HexagonArch.HEXAGON_ARCH_V75;
    case 79:
    case "HEXAGON_ARCH_V79":
      return HexagonArch.HEXAGON_ARCH_V79;
    case 81:
    case "HEXAGON_ARCH_V81":
      return HexagonArch.HEXAGON_ARCH_V81;
    case -1:
    case "UNRECOGNIZED":
    default:
      return HexagonArch.UNRECOGNIZED;
  }
}

export function hexagonArchToJSON(object: HexagonArch): string {
  switch (object) {
    case HexagonArch.HEXAGON_ARCH_UNKNOWN:
      return "HEXAGON_ARCH_UNKNOWN";
    case HexagonArch.HEXAGON_ARCH_V68:
      return "HEXAGON_ARCH_V68";
    case HexagonArch.HEXAGON_ARCH_V69:
      return "HEXAGON_ARCH_V69";
    case HexagonArch.HEXAGON_ARCH_V73:
      return "HEXAGON_ARCH_V73";
    case HexagonArch.HEXAGON_ARCH_V75:
      return "HEXAGON_ARCH_V75";
    case HexagonArch.HEXAGON_ARCH_V79:
      return "HEXAGON_ARCH_V79";
    case HexagonArch.HEXAGON_ARCH_V81:
      return "HEXAGON_ARCH_V81";
    case HexagonArch.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * The single NPU-capability description in this IDL. Static device
 * description lives in exactly one other place: device_info.proto's
 * DeviceInfo.
 */
export interface NpuCapability {
  /** Vendor SoC model (e.g. "SM8750"); empty when unknown. */
  socModel: string;
  /**
   * /sys/devices/soc0/soc_id value. ABSENT when unavailable — never a -1 or 0
   * sentinel; a default-constructed message is already "unavailable".
   */
  socId?: number | undefined;
  hexagonArch: HexagonArch;
  /**
   * True iff this accelerator generation is in the device-validated supported
   * set (Hexagon v75/v79/v81 today). Engine-agnostic on purpose: a second NPU
   * engine must not require a second boolean.
   */
  supported: boolean;
  /**
   * NPU vendor family. Re-homed here so a non-Qualcomm device gets a
   * meaningful answer instead of an empty message.
   */
  npu: NPUChip;
}

function createBaseNpuCapability(): NpuCapability {
  return { socModel: "", socId: undefined, hexagonArch: 0, supported: false, npu: 0 };
}

export const NpuCapability: MessageFns<NpuCapability> = {
  encode(message: NpuCapability, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.socModel !== "") {
      writer.uint32(10).string(message.socModel);
    }
    if (message.socId !== undefined) {
      writer.uint32(16).int32(message.socId);
    }
    if (message.hexagonArch !== 0) {
      writer.uint32(24).int32(message.hexagonArch);
    }
    if (message.supported !== false) {
      writer.uint32(32).bool(message.supported);
    }
    if (message.npu !== 0) {
      writer.uint32(40).int32(message.npu);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NpuCapability {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNpuCapability();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.socModel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.socId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hexagonArch = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.supported = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.npu = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NpuCapability {
    return {
      socModel: isSet(object.socModel)
        ? globalThis.String(object.socModel)
        : isSet(object.soc_model)
        ? globalThis.String(object.soc_model)
        : "",
      socId: isSet(object.socId)
        ? globalThis.Number(object.socId)
        : isSet(object.soc_id)
        ? globalThis.Number(object.soc_id)
        : undefined,
      hexagonArch: isSet(object.hexagonArch)
        ? hexagonArchFromJSON(object.hexagonArch)
        : isSet(object.hexagon_arch)
        ? hexagonArchFromJSON(object.hexagon_arch)
        : 0,
      supported: isSet(object.supported) ? globalThis.Boolean(object.supported) : false,
      npu: isSet(object.npu) ? nPUChipFromJSON(object.npu) : 0,
    };
  },

  toJSON(message: NpuCapability): unknown {
    const obj: any = {};
    if (message.socModel !== "") {
      obj.socModel = message.socModel;
    }
    if (message.socId !== undefined) {
      obj.socId = Math.round(message.socId);
    }
    if (message.hexagonArch !== 0) {
      obj.hexagonArch = hexagonArchToJSON(message.hexagonArch);
    }
    if (message.supported !== false) {
      obj.supported = message.supported;
    }
    if (message.npu !== 0) {
      obj.npu = nPUChipToJSON(message.npu);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NpuCapability>, I>>(base?: I): NpuCapability {
    return NpuCapability.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NpuCapability>, I>>(object: I): NpuCapability {
    const message = createBaseNpuCapability();
    message.socModel = object.socModel ?? "";
    message.socId = object.socId ?? undefined;
    message.hexagonArch = object.hexagonArch ?? 0;
    message.supported = object.supported ?? false;
    message.npu = object.npu ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
