// VENDORED from @runanywhere/proto-ts (sdk/shared/proto-ts, generated from
// idl/thinking_tag_pattern.proto). Copied verbatim because @runanywhere/electron is a standalone
// package outside the monorepo's proto-ts workspace, so it can't consume the
// shared package via workspace resolution. Regenerate by re-copying the shared
// file — do NOT hand-edit. Only runtime dep is @bufbuild/protobuf (pure TS).
//
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: thinking_tag_pattern.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * The single home for reasoning/thinking control. Replaces the retired
 * per-message toggles (LLMGenerationOptions.disable_thinking,
 * ToolCallingOptions.disable_thinking, RAGQueryOptions.disable_thinking,
 * ToolCallingSessionCreateRequest.disable_thinking,
 * LLMGenerateRequest.emit_thoughts). Referenced from LLM and VLM generation
 * options; every composed surface (tool calling, RAG, voice agent) inherits
 * it through the embedded LLMGenerationOptions.
 * ---------------------------------------------------------------------------
 */
export enum ReasoningMode {
  /** REASONING_MODE_UNSPECIFIED - Model default: reasoning-capable models think, others don't. */
  REASONING_MODE_UNSPECIFIED = 0,
  /**
   * REASONING_MODE_OFF - Suppress the thinking phase (commons applies the model's no-think
   * directive at the prompt level).
   */
  REASONING_MODE_OFF = 1,
  /** REASONING_MODE_ON - Request the thinking phase on models where it is optional. */
  REASONING_MODE_ON = 2,
  UNRECOGNIZED = -1,
}

export function reasoningModeFromJSON(object: any): ReasoningMode {
  switch (object) {
    case 0:
    case "REASONING_MODE_UNSPECIFIED":
      return ReasoningMode.REASONING_MODE_UNSPECIFIED;
    case 1:
    case "REASONING_MODE_OFF":
      return ReasoningMode.REASONING_MODE_OFF;
    case 2:
    case "REASONING_MODE_ON":
      return ReasoningMode.REASONING_MODE_ON;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ReasoningMode.UNRECOGNIZED;
  }
}

export function reasoningModeToJSON(object: ReasoningMode): string {
  switch (object) {
    case ReasoningMode.REASONING_MODE_UNSPECIFIED:
      return "REASONING_MODE_UNSPECIFIED";
    case ReasoningMode.REASONING_MODE_OFF:
      return "REASONING_MODE_OFF";
    case ReasoningMode.REASONING_MODE_ON:
      return "REASONING_MODE_ON";
    case ReasoningMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * ---------------------------------------------------------------------------
 * Pattern used to extract a model's "thinking" / reasoning block from its
 * raw output. Used by Qwen3 and LFM2 family models that emit
 * <think>...</think> wrappers. Shared by LLM generation options (per-call
 * override) and ModelInfo catalog metadata (default pattern for a model).
 * ---------------------------------------------------------------------------
 */
export interface ThinkingTagPattern {
  /** Opening tag string. Default if empty: "<think>". */
  openTag: string;
  /** Closing tag string. Default if empty: "</think>". */
  closeTag: string;
}

export interface ReasoningOptions {
  mode: ReasoningMode;
  /**
   * Emit thought tokens/content to the caller (stream TokenKind.THOUGHT
   * events and result thinking_content). False = thinking is stripped.
   */
  includeInOutput: boolean;
  /**
   * Tag override for models whose thinking markers differ from the
   * catalog default.
   */
  pattern?: ThinkingTagPattern | undefined;
}

function createBaseThinkingTagPattern(): ThinkingTagPattern {
  return { openTag: "", closeTag: "" };
}

export const ThinkingTagPattern: MessageFns<ThinkingTagPattern> = {
  encode(message: ThinkingTagPattern, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.openTag !== "") {
      writer.uint32(10).string(message.openTag);
    }
    if (message.closeTag !== "") {
      writer.uint32(18).string(message.closeTag);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ThinkingTagPattern {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseThinkingTagPattern();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.openTag = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.closeTag = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ThinkingTagPattern {
    return {
      openTag: isSet(object.openTag)
        ? globalThis.String(object.openTag)
        : isSet(object.open_tag)
        ? globalThis.String(object.open_tag)
        : "",
      closeTag: isSet(object.closeTag)
        ? globalThis.String(object.closeTag)
        : isSet(object.close_tag)
        ? globalThis.String(object.close_tag)
        : "",
    };
  },

  toJSON(message: ThinkingTagPattern): unknown {
    const obj: any = {};
    if (message.openTag !== "") {
      obj.openTag = message.openTag;
    }
    if (message.closeTag !== "") {
      obj.closeTag = message.closeTag;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ThinkingTagPattern>, I>>(base?: I): ThinkingTagPattern {
    return ThinkingTagPattern.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ThinkingTagPattern>, I>>(object: I): ThinkingTagPattern {
    const message = createBaseThinkingTagPattern();
    message.openTag = object.openTag ?? "";
    message.closeTag = object.closeTag ?? "";
    return message;
  },
};

function createBaseReasoningOptions(): ReasoningOptions {
  return { mode: 0, includeInOutput: false, pattern: undefined };
}

export const ReasoningOptions: MessageFns<ReasoningOptions> = {
  encode(message: ReasoningOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mode !== 0) {
      writer.uint32(8).int32(message.mode);
    }
    if (message.includeInOutput !== false) {
      writer.uint32(16).bool(message.includeInOutput);
    }
    if (message.pattern !== undefined) {
      ThinkingTagPattern.encode(message.pattern, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReasoningOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReasoningOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.mode = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.includeInOutput = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pattern = ThinkingTagPattern.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReasoningOptions {
    return {
      mode: isSet(object.mode) ? reasoningModeFromJSON(object.mode) : 0,
      includeInOutput: isSet(object.includeInOutput)
        ? globalThis.Boolean(object.includeInOutput)
        : isSet(object.include_in_output)
        ? globalThis.Boolean(object.include_in_output)
        : false,
      pattern: isSet(object.pattern) ? ThinkingTagPattern.fromJSON(object.pattern) : undefined,
    };
  },

  toJSON(message: ReasoningOptions): unknown {
    const obj: any = {};
    if (message.mode !== 0) {
      obj.mode = reasoningModeToJSON(message.mode);
    }
    if (message.includeInOutput !== false) {
      obj.includeInOutput = message.includeInOutput;
    }
    if (message.pattern !== undefined) {
      obj.pattern = ThinkingTagPattern.toJSON(message.pattern);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReasoningOptions>, I>>(base?: I): ReasoningOptions {
    return ReasoningOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReasoningOptions>, I>>(object: I): ReasoningOptions {
    const message = createBaseReasoningOptions();
    message.mode = object.mode ?? 0;
    message.includeInOutput = object.includeInOutput ?? false;
    message.pattern = (object.pattern !== undefined && object.pattern !== null)
      ? ThinkingTagPattern.fromPartial(object.pattern)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
