// GENERATED by idl/codegen/generate_ts_convenience.py — DO NOT EDIT.
//
// Source: idl/diffusion_options.proto
//
// Convenience helpers derived from RunAnywhere's `rac_*` proto
// annotations (see idl/rac_options.proto):
//   * `<enumName>WireString`         (rac_wire_string)
//   * `<enumName>FromWireString`     (reverse of rac_wire_string)
//   * `<enumName>DisplayName`        (rac_display_name)
//   * `<enumName>AnalyticsKey`       (rac_analytics_key)
//   * `<msgName>Defaults`            (rac_default)
//   * `validate<MsgName>`            (rac_required / rac_min / rac_max /
//                                     rac_min_float / rac_max_float)

/* eslint-disable */

import { DiffusionGenerationOptions } from '../diffusion_options';
import { ValidationError } from './_errors';

export const diffusionGenerationOptionsDefaults = (): DiffusionGenerationOptions => ({
  prompt: '',
  negativePrompt: '',
  width: 0,
  height: 0,
  steps: 0,
  guidanceScale: 0.0,
  seed: -1,
  scheduler: 0,
  mode: 0,
  denoiseStrength: 0.75,
  reportIntermediateImages: false,
  progressStride: 0,
  inputImageWidth: 0,
  inputImageHeight: 0,
  batchSize: 0,
  returnLatents: false,
});

export const validateDiffusionGenerationOptions = (m: DiffusionGenerationOptions): void => {
  if (m.prompt === '') {
    throw new ValidationError({
      fieldPath: 'DiffusionGenerationOptions.prompt',
      message: 'prompt is required',
    });
  }
  if (m.steps < 0 || m.steps > 50) {
    throw new ValidationError({
      fieldPath: 'DiffusionGenerationOptions.steps',
      message: `steps must be in 0...50 (got ${m.steps})`,
    });
  }
  if (!Number.isFinite(m.guidanceScale) || m.guidanceScale < 0.0 || m.guidanceScale > 20.0) {
    throw new ValidationError({
      fieldPath: 'DiffusionGenerationOptions.guidance_scale',
      message: `guidance_scale must be in 0.0...20.0 (got ${m.guidanceScale})`,
    });
  }
  if (!Number.isFinite(m.denoiseStrength) || m.denoiseStrength < 0.0 || m.denoiseStrength > 1.0) {
    throw new ValidationError({
      fieldPath: 'DiffusionGenerationOptions.denoise_strength',
      message: `denoise_strength must be in 0.0...1.0 (got ${m.denoiseStrength})`,
    });
  }
};
