// GENERATED by idl/codegen/generate_ts_convenience.py — DO NOT EDIT.
//
// Source: idl/diffusion_options.proto
//
// Convenience helpers derived from RunAnywhere's `rac_*` proto
// annotations (see idl/rac_options.proto):
//   * `<enumName>WireString`         (rac_wire_string)
//   * `<enumName>FromWireString`     (reverse of rac_wire_string)
//   * `<enumName>DisplayName`        (rac_display_name)
//   * `<enumName>AnalyticsKey`       (rac_analytics_key)
//   * `<msgName>Defaults`            (rac_default)
//   * `validate<MsgName>`            (rac_required / rac_min / rac_max /
//                                     rac_min_float / rac_max_float)

/* eslint-disable */

import { DiffusionGenerationOptions, DiffusionOutputFormat } from '../diffusion_options';
import { ValidationError } from './_errors';

export const diffusionGenerationOptionsDefaults = (): DiffusionGenerationOptions => ({
  prompt: '',
  negativePrompt: '',
  width: 0,
  height: 0,
  steps: 0,
  guidanceScale: 0.0,
  scheduler: 0,
  strength: 0.75,
  n: 1,
  outputFormat: DiffusionOutputFormat.DIFFUSION_OUTPUT_FORMAT_PNG,
});

export const validateDiffusionGenerationOptions = (m: DiffusionGenerationOptions): void => {
  if (m.prompt === '') {
    throw new ValidationError({
      fieldPath: 'DiffusionGenerationOptions.prompt',
      message: 'prompt is required',
    });
  }
  if (m.steps < 0 || m.steps > 50) {
    throw new ValidationError({
      fieldPath: 'DiffusionGenerationOptions.steps',
      message: `steps must be in 0...50 (got ${m.steps})`,
    });
  }
  if (!Number.isFinite(m.guidanceScale) || m.guidanceScale < 0.0 || m.guidanceScale > 20.0) {
    throw new ValidationError({
      fieldPath: 'DiffusionGenerationOptions.guidance_scale',
      message: `guidance_scale must be in 0.0...20.0 (got ${m.guidanceScale})`,
    });
  }
  if (!Number.isFinite(m.strength) || m.strength < 0.0 || m.strength > 1.0) {
    throw new ValidationError({
      fieldPath: 'DiffusionGenerationOptions.strength',
      message: `strength must be in 0.0...1.0 (got ${m.strength})`,
    });
  }
  if (m.n !== undefined && (m.n < 1 || m.n > 8)) {
    throw new ValidationError({
      fieldPath: 'DiffusionGenerationOptions.n',
      message: `n must be in 1...8 (got ${m.n})`,
    });
  }
};
