// GENERATED by idl/codegen/generate_ts_convenience.py — DO NOT EDIT.
//
// Source: idl/llm_options.proto
//
// Convenience helpers derived from RunAnywhere's `rac_*` proto
// annotations (see idl/rac_options.proto):
//   * `<enumName>WireString`         (rac_wire_string)
//   * `<enumName>FromWireString`     (reverse of rac_wire_string)
//   * `<enumName>DisplayName`        (rac_display_name)
//   * `<enumName>AnalyticsKey`       (rac_analytics_key)
//   * `<msgName>Defaults`            (rac_default)
//   * `validate<MsgName>`            (rac_required / rac_min / rac_max /
//                                     rac_min_float / rac_max_float)

/* eslint-disable */

import { LLMConfiguration, LLMGenerationOptions } from '../llm_options';
import { ValidationError } from './_errors';

export const lLMGenerationOptionsDefaults = (): LLMGenerationOptions => ({
  maxOutputTokens: 512,
  temperature: 0.7,
  topP: 1.0,
  topK: 40,
  repeatPenalty: 1.1,
  stopSequences: [],
  preferredFramework: 0,
  seed: 0,
  frequencyPenalty: 0.0,
  presencePenalty: 0.0,
  repeatLastN: 0,
  minP: 0.05,
  echoPrompt: false,
});

export const validateLLMGenerationOptions = (m: LLMGenerationOptions): void => {
  if (m.maxOutputTokens !== undefined && (m.maxOutputTokens < 0)) {
    throw new ValidationError({
      fieldPath: 'LLMGenerationOptions.max_output_tokens',
      message: `max_output_tokens must be >= 0 (got ${m.maxOutputTokens})`,
    });
  }
  if (m.temperature !== undefined && (!Number.isFinite(m.temperature) || m.temperature < 0.0 || m.temperature > 2.0)) {
    throw new ValidationError({
      fieldPath: 'LLMGenerationOptions.temperature',
      message: `temperature must be in 0.0...2.0 (got ${m.temperature})`,
    });
  }
  if (m.topP !== undefined && (!Number.isFinite(m.topP) || m.topP < 0.0 || m.topP > 1.0)) {
    throw new ValidationError({
      fieldPath: 'LLMGenerationOptions.top_p',
      message: `top_p must be in 0.0...1.0 (got ${m.topP})`,
    });
  }
  if (m.topK !== undefined && (m.topK < 0)) {
    throw new ValidationError({
      fieldPath: 'LLMGenerationOptions.top_k',
      message: `top_k must be >= 0 (got ${m.topK})`,
    });
  }
  if (m.repeatPenalty !== undefined && (!Number.isFinite(m.repeatPenalty) || m.repeatPenalty < 0.0)) {
    throw new ValidationError({
      fieldPath: 'LLMGenerationOptions.repeat_penalty',
      message: `repeat_penalty must be >= 0.0 (got ${m.repeatPenalty})`,
    });
  }
};

export const lLMConfigurationDefaults = (): LLMConfiguration => ({
  contextLength: 2048,
});
