// GENERATED by idl/codegen/generate_ts_convenience.py — DO NOT EDIT.
//
// Source: idl/stt_options.proto
//
// Convenience helpers derived from RunAnywhere's `rac_*` proto
// annotations (see idl/rac_options.proto):
//   * `<enumName>WireString`         (rac_wire_string)
//   * `<enumName>FromWireString`     (reverse of rac_wire_string)
//   * `<enumName>DisplayName`        (rac_display_name)
//   * `<enumName>AnalyticsKey`       (rac_analytics_key)
//   * `<msgName>Defaults`            (rac_default)
//   * `validate<MsgName>`            (rac_required / rac_min / rac_max /
//                                     rac_min_float / rac_max_float)

/* eslint-disable */

import { STTConfiguration, STTOptions } from '../stt_options';
import { ValidationError } from './_errors';

export const sTTConfigurationDefaults = (): STTConfiguration => ({
  modelId: '',
  sampleRate: 16000,
  enableVad: false,
  audioFormat: 0,
  enablePunctuation: true,
  enableDiarization: false,
  vocabularyList: [],
  maxAlternatives: 0,
  enableWordTimestamps: true,
});

export const validateSTTConfiguration = (m: STTConfiguration): void => {
  if (m.sampleRate < 8000 || m.sampleRate > 48000) {
    throw new ValidationError({
      fieldPath: 'STTConfiguration.sample_rate',
      message: `sample_rate must be in 8000...48000 (got ${m.sampleRate})`,
    });
  }
};

export const sTTOptionsDefaults = (): STTOptions => ({
  enablePunctuation: true,
  enableDiarization: false,
  maxSpeakers: 0,
  vocabularyList: [],
  enableWordTimestamps: true,
  beamSize: 0,
  maxAlternatives: 0,
  chunkDurationMs: 0,
  endpointSilenceMs: 0,
  suppressBlank: false,
  translateToEnglish: false,
});
