"""Hand-written type stubs for the compiled ``_core`` pybind11 extension.

Mirror the native surface bound in ``native/module.cpp`` exactly (snake_case). Handles are
opaque ``int`` ids. Streaming ``generate`` / ``generate_vlm`` push tokens through an
``on_token(str) -> bool | None`` callback (returning ``False`` requests an early stop).
"""

from __future__ import annotations

from typing import Any, Callable, Union

import numpy as np
import numpy.typing as npt

# A per-token streaming callback: receives the next token, may return ``False`` to stop.
OnToken = Callable[[str], "bool | None"]

def version() -> str: ...
def backends() -> list[str]: ...
def initialize(secure_dir: str, base_dir: str | None = ...) -> None: ...
def shutdown() -> None: ...

# Control plane (telemetry + auth). Present when the protobuf runtime is built
# (RAC_PY_CONTROL_PLANE); ``has_control_plane`` is the capability flag. HTTP is
# performed by ``http_poster`` — a Python callable
# ``(method, url, [(k, v), ...], body: bytes, timeout_ms: int) ->
# (status: int, [(k, v), ...], body: bytes) | None`` — registered as the transport
# (None => network error). ``environment`` is a rac_environment_t (0=dev, 2=prod);
# ``phase1_bytes``/``phase2_bytes`` are serialized SdkInit{Phase1,Phase2}Request;
# the return is a serialized SdkInitResult (empty on a phase failure).
has_control_plane: bool
def device_persistent_id() -> str: ...
def dev_staging_base_url() -> str: ...
def configure_control_plane(
    http_poster: Callable[[str, str, list, bytes, int], "tuple | None"],
    environment: int,
    api_key: str,
    base_url: str,
    device_id: str,
    platform: str,
    sdk_version: str,
    sdk_binding: str,
    app_identifier: str,
    app_name: str,
    app_version: str,
    phase1_bytes: bytes,
    phase2_bytes: bytes,
) -> bytes: ...

# ---- LLM -------------------------------------------------------------------------------
def load_model(path: str, id: str | None = ..., name: str | None = ...) -> int: ...
def generate(
    handle: int,
    prompt: str,
    on_token: OnToken,
    max_tokens: int | None = ...,
    temperature: float | None = ...,
    top_p: float | None = ...,
    top_k: int | None = ...,
    system_prompt: str | None = ...,
    grammar: str | None = ...,
    disable_thinking: bool | None = ...,
) -> None: ...
def cancel_generate(handle: int) -> None: ...
def unload_model(handle: int) -> None: ...

# ---- VLM -------------------------------------------------------------------------------
def load_vlm_model(
    model_path: str, mmproj_path: str, id: str | None = ..., name: str | None = ...
) -> int: ...
def generate_vlm(
    handle: int,
    image_path: str,
    prompt: str,
    on_token: OnToken,
    max_tokens: int | None = ...,
    temperature: float | None = ...,
    top_p: float | None = ...,
    top_k: int | None = ...,
    system_prompt: str | None = ...,
) -> None: ...
def cancel_generate_vlm(handle: int) -> None: ...
def unload_vlm_model(handle: int) -> None: ...

# ---- Embeddings (ONNX) -----------------------------------------------------------------
def load_embedding_model(path: str) -> int: ...
def embed(handle: int, text: str) -> npt.NDArray[np.float32]: ...
def embed_batch(handle: int, texts: list[str]) -> list[npt.NDArray[np.float32]]: ...
def unload_embedding_model(handle: int) -> None: ...

# ---- STT (sherpa) ----------------------------------------------------------------------
def load_stt_model(dir: str, id: str | None = ..., name: str | None = ...) -> int: ...
def transcribe(handle: int, pcm16: Union[bytes, bytearray, memoryview, npt.NDArray]) -> str: ...
def unload_stt_model(handle: int) -> None: ...

# ---- TTS (sherpa) ----------------------------------------------------------------------
def load_tts_voice(dir: str, id: str | None = ..., name: str | None = ...) -> int: ...
def synthesize(handle: int, text: str) -> tuple[npt.NDArray[np.float32], int]: ...
def unload_tts_voice(handle: int) -> None: ...

# ---- VAD (energy + optional Silero/sherpa model) ---------------------------------------
def create_vad(threshold: float | None = ...) -> int: ...
def vad_process(handle: int, samples: npt.NDArray[np.float32]) -> bool: ...
def vad_is_active(handle: int) -> bool: ...
def vad_set_threshold(handle: int, threshold: float) -> None: ...
def vad_reset(handle: int) -> None: ...
def load_vad_model(
    handle: int, model_path: str, id: str | None = ..., name: str | None = ...
) -> None: ...
def unload_vad(handle: int) -> None: ...

# ---- LoRA (LlamaCPP) -------------------------------------------------------------------
def lora_apply(handle: int, adapter_path: str, scale: float | None = ...) -> None: ...
def lora_remove(handle: int, adapter_path: str) -> None: ...
def lora_remove_all(handle: int) -> None: ...

# ---- Diarization (ONNX Sortformer) -----------------------------------------------------
def load_diarization_model(model_path: str, id: str | None = ...) -> int: ...
def diarize(
    handle: int,
    samples: npt.NDArray[np.float32],
    sample_rate_hz: int | None = ...,
    threshold: float | None = ...,
    minimum_duration_ms: int | None = ...,
    merge_gap_ms: int | None = ...,
) -> dict[str, Any]: ...
def unload_diarization_model(handle: int) -> None: ...

# ---- Segmentation (ONNX) ---------------------------------------------------------------
def load_segmentation_model(model_path: str, id: str | None = ...) -> int: ...
def segment(
    handle: int,
    data: Union[bytes, bytearray, memoryview, npt.NDArray],
    width: int,
    height: int,
    pixel_format: int | None = ...,
    stride_bytes: int | None = ...,
    include_diagnostic_rgba: bool | None = ...,
) -> dict[str, Any]: ...
def unload_segmentation_model(handle: int) -> None: ...

# ---- Voice agent (file-PCM turn; STT→LLM→TTS) ------------------------------------------
def create_voice_agent() -> int: ...
def initialize_voice_agent(
    handle: int,
    stt_path: str,
    llm_path: str,
    tts_path: str,
    stt_id: str | None = ...,
    llm_id: str | None = ...,
    tts_id: str | None = ...,
    stt_name: str | None = ...,
    llm_name: str | None = ...,
    tts_name: str | None = ...,
) -> None: ...
def process_voice_turn(
    handle: int, pcm16: Union[bytes, bytearray, memoryview, npt.NDArray]
) -> dict[str, Any]: ...
def destroy_voice_agent(handle: int) -> None: ...

# ---- Diffusion (present only when built with RAC_HAVE_BACKEND_COREML) ------------------
def load_diffusion_model(model_path: str, id: str | None = ...) -> int: ...
def generate_image(
    handle: int,
    prompt: str,
    negative_prompt: str | None = ...,
    width: int | None = ...,
    height: int | None = ...,
    steps: int | None = ...,
    guidance_scale: float | None = ...,
    seed: int | None = ...,
) -> dict[str, Any]: ...
def unload_diffusion_model(handle: int) -> None: ...

# ---- Model registry --------------------------------------------------------------------
# Register a model (id -> local_path + framework/category ints) into the global model
# registry so the RAG session ABI can resolve embedding_model_id / llm_model_id to paths.
def register_model(model_id: str, local_path: str, framework: int, category: int) -> None: ...
def get_model(model_id: str) -> dict[str, Any] | None: ...
def list_models() -> list[dict[str, Any]]: ...
def remove_model(model_id: str) -> None: ...

# ---- RAG (proto-bytes in / proto-bytes out; present when built with RAC_BACKEND_RAG) ----
# Each call takes/returns serialized runanywhere.v1.* protobuf bytes; runanywhere.rag owns
# the (de)serialization. A streaming query pushes serialized RAGStreamEvent bytes through
# on_event (returning False requests an early stop).
OnEvent = Callable[[bytes], "bool | None"]

def rag_session_create(config_bytes: bytes) -> int: ...
def rag_ingest(handle: int, document_bytes: bytes) -> bytes: ...
def rag_query(handle: int, query_bytes: bytes) -> bytes: ...
def rag_search(handle: int, request_bytes: bytes) -> bytes: ...
def rag_query_stream(handle: int, query_bytes: bytes, on_event: OnEvent) -> None: ...
def rag_cancel(handle: int) -> None: ...
def rag_clear(handle: int) -> bytes: ...
def rag_stats(handle: int) -> bytes: ...
def rag_session_destroy(handle: int) -> None: ...

# ---- Secure key-value store ------------------------------------------------------------
def secure_set(key: str, value: str) -> None: ...
def secure_get(key: str) -> str | None: ...
def secure_delete(key: str) -> None: ...
