"""Hand-written type stubs for the compiled ``_core`` pybind11 extension.

Mirror the native surface bound in ``native/module.cpp`` exactly (snake_case). Handles are
opaque ``int`` ids. Streaming ``generate`` / ``generate_vlm`` push tokens through an
``on_token(str) -> bool | None`` callback (returning ``False`` requests an early stop).
"""

from __future__ import annotations

from typing import Callable, Union

import numpy as np
import numpy.typing as npt

# A per-token streaming callback: receives the next token, may return ``False`` to stop.
OnToken = Callable[[str], "bool | None"]

def version() -> str: ...
def initialize(secure_dir: str, base_dir: str | None = ...) -> None: ...
def shutdown() -> None: ...

# ---- LLM -------------------------------------------------------------------------------
def load_model(path: str, id: str | None = ..., name: str | None = ...) -> int: ...
def generate(
    handle: int,
    prompt: str,
    on_token: OnToken,
    max_tokens: int | None = ...,
    temperature: float | None = ...,
    top_p: float | None = ...,
    top_k: int | None = ...,
    system_prompt: str | None = ...,
    grammar: str | None = ...,
) -> None: ...
def unload_model(handle: int) -> None: ...

# ---- VLM -------------------------------------------------------------------------------
def load_vlm_model(
    model_path: str, mmproj_path: str, id: str | None = ..., name: str | None = ...
) -> int: ...
def generate_vlm(handle: int, image_path: str, prompt: str, on_token: OnToken) -> None: ...
def unload_vlm_model(handle: int) -> None: ...

# ---- Embeddings (ONNX) -----------------------------------------------------------------
def load_embedding_model(path: str) -> int: ...
def embed(handle: int, text: str) -> npt.NDArray[np.float32]: ...
def unload_embedding_model(handle: int) -> None: ...

# ---- STT (sherpa) ----------------------------------------------------------------------
def load_stt_model(dir: str, id: str | None = ..., name: str | None = ...) -> int: ...
def transcribe(handle: int, pcm16: Union[bytes, bytearray, memoryview, npt.NDArray]) -> str: ...
def unload_stt_model(handle: int) -> None: ...

# ---- TTS (sherpa) ----------------------------------------------------------------------
def load_tts_voice(dir: str, id: str | None = ..., name: str | None = ...) -> int: ...
def synthesize(handle: int, text: str) -> tuple[npt.NDArray[np.float32], int]: ...
def unload_tts_voice(handle: int) -> None: ...

# ---- VAD (built-in energy VAD) ---------------------------------------------------------
def create_vad(threshold: float | None = ...) -> int: ...
def vad_process(handle: int, samples: npt.NDArray[np.float32]) -> bool: ...
def vad_is_active(handle: int) -> bool: ...
def vad_set_threshold(handle: int, threshold: float) -> None: ...
def vad_reset(handle: int) -> None: ...
def unload_vad(handle: int) -> None: ...

# ---- Secure key-value store ------------------------------------------------------------
def secure_set(key: str, value: str) -> None: ...
def secure_get(key: str) -> str | None: ...
def secure_delete(key: str) -> None: ...
