include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore
