// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v7.34.1
// source: download_service.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "runanywhere.v1";

export enum DownloadStage {
  DOWNLOAD_STAGE_UNSPECIFIED = 0,
  DOWNLOAD_STAGE_DOWNLOADING = 1,
  DOWNLOAD_STAGE_EXTRACTING = 2,
  DOWNLOAD_STAGE_VALIDATING = 3,
  DOWNLOAD_STAGE_COMPLETED = 4,
  UNRECOGNIZED = -1,
}

export function downloadStageFromJSON(object: any): DownloadStage {
  switch (object) {
    case 0:
    case "DOWNLOAD_STAGE_UNSPECIFIED":
      return DownloadStage.DOWNLOAD_STAGE_UNSPECIFIED;
    case 1:
    case "DOWNLOAD_STAGE_DOWNLOADING":
      return DownloadStage.DOWNLOAD_STAGE_DOWNLOADING;
    case 2:
    case "DOWNLOAD_STAGE_EXTRACTING":
      return DownloadStage.DOWNLOAD_STAGE_EXTRACTING;
    case 3:
    case "DOWNLOAD_STAGE_VALIDATING":
      return DownloadStage.DOWNLOAD_STAGE_VALIDATING;
    case 4:
    case "DOWNLOAD_STAGE_COMPLETED":
      return DownloadStage.DOWNLOAD_STAGE_COMPLETED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DownloadStage.UNRECOGNIZED;
  }
}

export function downloadStageToJSON(object: DownloadStage): string {
  switch (object) {
    case DownloadStage.DOWNLOAD_STAGE_UNSPECIFIED:
      return "DOWNLOAD_STAGE_UNSPECIFIED";
    case DownloadStage.DOWNLOAD_STAGE_DOWNLOADING:
      return "DOWNLOAD_STAGE_DOWNLOADING";
    case DownloadStage.DOWNLOAD_STAGE_EXTRACTING:
      return "DOWNLOAD_STAGE_EXTRACTING";
    case DownloadStage.DOWNLOAD_STAGE_VALIDATING:
      return "DOWNLOAD_STAGE_VALIDATING";
    case DownloadStage.DOWNLOAD_STAGE_COMPLETED:
      return "DOWNLOAD_STAGE_COMPLETED";
    case DownloadStage.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum DownloadState {
  DOWNLOAD_STATE_UNSPECIFIED = 0,
  DOWNLOAD_STATE_PENDING = 1,
  DOWNLOAD_STATE_DOWNLOADING = 2,
  DOWNLOAD_STATE_EXTRACTING = 3,
  DOWNLOAD_STATE_RETRYING = 4,
  DOWNLOAD_STATE_COMPLETED = 5,
  DOWNLOAD_STATE_FAILED = 6,
  DOWNLOAD_STATE_CANCELLED = 7,
  UNRECOGNIZED = -1,
}

export function downloadStateFromJSON(object: any): DownloadState {
  switch (object) {
    case 0:
    case "DOWNLOAD_STATE_UNSPECIFIED":
      return DownloadState.DOWNLOAD_STATE_UNSPECIFIED;
    case 1:
    case "DOWNLOAD_STATE_PENDING":
      return DownloadState.DOWNLOAD_STATE_PENDING;
    case 2:
    case "DOWNLOAD_STATE_DOWNLOADING":
      return DownloadState.DOWNLOAD_STATE_DOWNLOADING;
    case 3:
    case "DOWNLOAD_STATE_EXTRACTING":
      return DownloadState.DOWNLOAD_STATE_EXTRACTING;
    case 4:
    case "DOWNLOAD_STATE_RETRYING":
      return DownloadState.DOWNLOAD_STATE_RETRYING;
    case 5:
    case "DOWNLOAD_STATE_COMPLETED":
      return DownloadState.DOWNLOAD_STATE_COMPLETED;
    case 6:
    case "DOWNLOAD_STATE_FAILED":
      return DownloadState.DOWNLOAD_STATE_FAILED;
    case 7:
    case "DOWNLOAD_STATE_CANCELLED":
      return DownloadState.DOWNLOAD_STATE_CANCELLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DownloadState.UNRECOGNIZED;
  }
}

export function downloadStateToJSON(object: DownloadState): string {
  switch (object) {
    case DownloadState.DOWNLOAD_STATE_UNSPECIFIED:
      return "DOWNLOAD_STATE_UNSPECIFIED";
    case DownloadState.DOWNLOAD_STATE_PENDING:
      return "DOWNLOAD_STATE_PENDING";
    case DownloadState.DOWNLOAD_STATE_DOWNLOADING:
      return "DOWNLOAD_STATE_DOWNLOADING";
    case DownloadState.DOWNLOAD_STATE_EXTRACTING:
      return "DOWNLOAD_STATE_EXTRACTING";
    case DownloadState.DOWNLOAD_STATE_RETRYING:
      return "DOWNLOAD_STATE_RETRYING";
    case DownloadState.DOWNLOAD_STATE_COMPLETED:
      return "DOWNLOAD_STATE_COMPLETED";
    case DownloadState.DOWNLOAD_STATE_FAILED:
      return "DOWNLOAD_STATE_FAILED";
    case DownloadState.DOWNLOAD_STATE_CANCELLED:
      return "DOWNLOAD_STATE_CANCELLED";
    case DownloadState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface DownloadSubscribeRequest {
  modelId: string;
}

export interface DownloadProgress {
  modelId: string;
  stage: DownloadStage;
  bytesDownloaded: number;
  /** 0 if unknown */
  totalBytes: number;
  /** 0.0..1.0 within current stage */
  stageProgress: number;
  overallSpeedBps: number;
  /** -1 if unknown */
  etaSeconds: number;
  state: DownloadState;
  /** 0 on first try */
  retryAttempt: number;
  /** populated when state == FAILED */
  errorMessage: string;
}

function createBaseDownloadSubscribeRequest(): DownloadSubscribeRequest {
  return { modelId: "" };
}

export const DownloadSubscribeRequest = {
  encode(message: DownloadSubscribeRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DownloadSubscribeRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDownloadSubscribeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DownloadSubscribeRequest {
    return { modelId: isSet(object.modelId) ? globalThis.String(object.modelId) : "" };
  },

  toJSON(message: DownloadSubscribeRequest): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DownloadSubscribeRequest>, I>>(base?: I): DownloadSubscribeRequest {
    return DownloadSubscribeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DownloadSubscribeRequest>, I>>(object: I): DownloadSubscribeRequest {
    const message = createBaseDownloadSubscribeRequest();
    message.modelId = object.modelId ?? "";
    return message;
  },
};

function createBaseDownloadProgress(): DownloadProgress {
  return {
    modelId: "",
    stage: 0,
    bytesDownloaded: 0,
    totalBytes: 0,
    stageProgress: 0,
    overallSpeedBps: 0,
    etaSeconds: 0,
    state: 0,
    retryAttempt: 0,
    errorMessage: "",
  };
}

export const DownloadProgress = {
  encode(message: DownloadProgress, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.stage !== 0) {
      writer.uint32(16).int32(message.stage);
    }
    if (message.bytesDownloaded !== 0) {
      writer.uint32(24).int64(message.bytesDownloaded);
    }
    if (message.totalBytes !== 0) {
      writer.uint32(32).int64(message.totalBytes);
    }
    if (message.stageProgress !== 0) {
      writer.uint32(45).float(message.stageProgress);
    }
    if (message.overallSpeedBps !== 0) {
      writer.uint32(53).float(message.overallSpeedBps);
    }
    if (message.etaSeconds !== 0) {
      writer.uint32(56).int64(message.etaSeconds);
    }
    if (message.state !== 0) {
      writer.uint32(64).int32(message.state);
    }
    if (message.retryAttempt !== 0) {
      writer.uint32(72).int32(message.retryAttempt);
    }
    if (message.errorMessage !== "") {
      writer.uint32(82).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DownloadProgress {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDownloadProgress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.stage = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.bytesDownloaded = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.totalBytes = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.stageProgress = reader.float();
          continue;
        case 6:
          if (tag !== 53) {
            break;
          }

          message.overallSpeedBps = reader.float();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.etaSeconds = longToNumber(reader.int64() as Long);
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.retryAttempt = reader.int32();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DownloadProgress {
    return {
      modelId: isSet(object.modelId) ? globalThis.String(object.modelId) : "",
      stage: isSet(object.stage) ? downloadStageFromJSON(object.stage) : 0,
      bytesDownloaded: isSet(object.bytesDownloaded) ? globalThis.Number(object.bytesDownloaded) : 0,
      totalBytes: isSet(object.totalBytes) ? globalThis.Number(object.totalBytes) : 0,
      stageProgress: isSet(object.stageProgress) ? globalThis.Number(object.stageProgress) : 0,
      overallSpeedBps: isSet(object.overallSpeedBps) ? globalThis.Number(object.overallSpeedBps) : 0,
      etaSeconds: isSet(object.etaSeconds) ? globalThis.Number(object.etaSeconds) : 0,
      state: isSet(object.state) ? downloadStateFromJSON(object.state) : 0,
      retryAttempt: isSet(object.retryAttempt) ? globalThis.Number(object.retryAttempt) : 0,
      errorMessage: isSet(object.errorMessage) ? globalThis.String(object.errorMessage) : "",
    };
  },

  toJSON(message: DownloadProgress): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.stage !== 0) {
      obj.stage = downloadStageToJSON(message.stage);
    }
    if (message.bytesDownloaded !== 0) {
      obj.bytesDownloaded = Math.round(message.bytesDownloaded);
    }
    if (message.totalBytes !== 0) {
      obj.totalBytes = Math.round(message.totalBytes);
    }
    if (message.stageProgress !== 0) {
      obj.stageProgress = message.stageProgress;
    }
    if (message.overallSpeedBps !== 0) {
      obj.overallSpeedBps = message.overallSpeedBps;
    }
    if (message.etaSeconds !== 0) {
      obj.etaSeconds = Math.round(message.etaSeconds);
    }
    if (message.state !== 0) {
      obj.state = downloadStateToJSON(message.state);
    }
    if (message.retryAttempt !== 0) {
      obj.retryAttempt = Math.round(message.retryAttempt);
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DownloadProgress>, I>>(base?: I): DownloadProgress {
    return DownloadProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DownloadProgress>, I>>(object: I): DownloadProgress {
    const message = createBaseDownloadProgress();
    message.modelId = object.modelId ?? "";
    message.stage = object.stage ?? 0;
    message.bytesDownloaded = object.bytesDownloaded ?? 0;
    message.totalBytes = object.totalBytes ?? 0;
    message.stageProgress = object.stageProgress ?? 0;
    message.overallSpeedBps = object.overallSpeedBps ?? 0;
    message.etaSeconds = object.etaSeconds ?? 0;
    message.state = object.state ?? 0;
    message.retryAttempt = object.retryAttempt ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
