// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v7.34.1
// source: llm_options.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { InferenceFramework, inferenceFrameworkFromJSON, inferenceFrameworkToJSON } from "./model_types";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * Options for a single text generation invocation.
 *
 * Field names match Swift LLMGenerationOptions exactly; consumers may treat
 * proto3 scalar defaults as "unset" (Swift handled this via Optionals — proto
 * represents optional reference fields explicitly via `optional` keyword).
 * ---------------------------------------------------------------------------
 */
export interface LLMGenerationOptions {
  /**
   * Maximum number of tokens to generate. 0 (default) = unset → engine
   * default (typically 100).
   */
  maxTokens: number;
  /** Sampling temperature (0.0 - 2.0). 0.0 = greedy decoding. */
  temperature: number;
  /** Nucleus sampling (top-p). 1.0 = no nucleus truncation. */
  topP: number;
  /** Top-K sampling (Kotlin/Dart/RN field). 0 = disabled. */
  topK: number;
  /** Repetition penalty (Kotlin/Dart/RN field). 1.0 = no penalty. */
  repetitionPenalty: number;
  /**
   * Stop sequences. Generation halts when any of these strings appears in
   * the output stream.
   */
  stopSequences: string[];
  /** Whether to stream tokens vs return result at end (Swift field). */
  streamingEnabled: boolean;
  /** Preferred inference framework. UNSPECIFIED = pick automatically. */
  preferredFramework: InferenceFramework;
  /** System prompt to define AI behavior and formatting rules. */
  systemPrompt?:
    | string
    | undefined;
  /**
   * Optional structured-output mode (JSON schema). Engine returns text
   * that conforms to this schema. Swift wraps this in a StructuredOutputConfig
   * struct with the Generatable.Type — proto carries just the schema string.
   */
  jsonSchema?: string | undefined;
}

/**
 * ---------------------------------------------------------------------------
 * Result of a single text generation. Same fields as the Swift
 * LLMGenerationResult plus the fields RN/Web carry that Swift derives from
 * the rac_llm_stream_result_t C struct.
 * ---------------------------------------------------------------------------
 */
export interface LLMGenerationResult {
  /** Generated text (with thinking content removed if extracted). */
  text: string;
  /** Optional thinking/reasoning content extracted from the response. */
  thinkingContent?:
    | string
    | undefined;
  /** Number of input/prompt tokens (from tokenizer). */
  inputTokens: number;
  /** Number of tokens used (output / completion tokens). */
  tokensGenerated: number;
  /** Model used for generation. */
  modelUsed: string;
  /** Total wall-clock generation time in milliseconds. */
  generationTimeMs: number;
  /** Time-to-first-token in milliseconds (only set in streaming mode). */
  ttftMs?:
    | number
    | undefined;
  /** Tokens-per-second throughput. */
  tokensPerSecond: number;
  /**
   * Framework that actually performed the generation. Optional because
   * some C ABI paths don't surface it.
   */
  framework?:
    | string
    | undefined;
  /**
   * Reason the generation stopped: "stop", "length", "cancelled", "error".
   * Empty = unset.
   */
  finishReason: string;
  /** Number of tokens used for thinking/reasoning. 0 = not applicable. */
  thinkingTokens: number;
  /** Number of tokens in the actual response content (vs thinking). */
  responseTokens: number;
  /**
   * Optional JSON output (when structured-output mode was requested).
   * Empty = no structured output.
   */
  jsonOutput?: string | undefined;
}

function createBaseLLMGenerationOptions(): LLMGenerationOptions {
  return {
    maxTokens: 0,
    temperature: 0,
    topP: 0,
    topK: 0,
    repetitionPenalty: 0,
    stopSequences: [],
    streamingEnabled: false,
    preferredFramework: 0,
    systemPrompt: undefined,
    jsonSchema: undefined,
  };
}

export const LLMGenerationOptions = {
  encode(message: LLMGenerationOptions, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.maxTokens !== 0) {
      writer.uint32(8).int32(message.maxTokens);
    }
    if (message.temperature !== 0) {
      writer.uint32(21).float(message.temperature);
    }
    if (message.topP !== 0) {
      writer.uint32(29).float(message.topP);
    }
    if (message.topK !== 0) {
      writer.uint32(32).int32(message.topK);
    }
    if (message.repetitionPenalty !== 0) {
      writer.uint32(45).float(message.repetitionPenalty);
    }
    for (const v of message.stopSequences) {
      writer.uint32(50).string(v!);
    }
    if (message.streamingEnabled !== false) {
      writer.uint32(56).bool(message.streamingEnabled);
    }
    if (message.preferredFramework !== 0) {
      writer.uint32(64).int32(message.preferredFramework);
    }
    if (message.systemPrompt !== undefined) {
      writer.uint32(74).string(message.systemPrompt);
    }
    if (message.jsonSchema !== undefined) {
      writer.uint32(82).string(message.jsonSchema);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LLMGenerationOptions {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLLMGenerationOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.maxTokens = reader.int32();
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.temperature = reader.float();
          continue;
        case 3:
          if (tag !== 29) {
            break;
          }

          message.topP = reader.float();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.topK = reader.int32();
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.repetitionPenalty = reader.float();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.stopSequences.push(reader.string());
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.streamingEnabled = reader.bool();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.preferredFramework = reader.int32() as any;
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.systemPrompt = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.jsonSchema = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LLMGenerationOptions {
    return {
      maxTokens: isSet(object.maxTokens) ? globalThis.Number(object.maxTokens) : 0,
      temperature: isSet(object.temperature) ? globalThis.Number(object.temperature) : 0,
      topP: isSet(object.topP) ? globalThis.Number(object.topP) : 0,
      topK: isSet(object.topK) ? globalThis.Number(object.topK) : 0,
      repetitionPenalty: isSet(object.repetitionPenalty) ? globalThis.Number(object.repetitionPenalty) : 0,
      stopSequences: globalThis.Array.isArray(object?.stopSequences)
        ? object.stopSequences.map((e: any) => globalThis.String(e))
        : [],
      streamingEnabled: isSet(object.streamingEnabled) ? globalThis.Boolean(object.streamingEnabled) : false,
      preferredFramework: isSet(object.preferredFramework) ? inferenceFrameworkFromJSON(object.preferredFramework) : 0,
      systemPrompt: isSet(object.systemPrompt) ? globalThis.String(object.systemPrompt) : undefined,
      jsonSchema: isSet(object.jsonSchema) ? globalThis.String(object.jsonSchema) : undefined,
    };
  },

  toJSON(message: LLMGenerationOptions): unknown {
    const obj: any = {};
    if (message.maxTokens !== 0) {
      obj.maxTokens = Math.round(message.maxTokens);
    }
    if (message.temperature !== 0) {
      obj.temperature = message.temperature;
    }
    if (message.topP !== 0) {
      obj.topP = message.topP;
    }
    if (message.topK !== 0) {
      obj.topK = Math.round(message.topK);
    }
    if (message.repetitionPenalty !== 0) {
      obj.repetitionPenalty = message.repetitionPenalty;
    }
    if (message.stopSequences?.length) {
      obj.stopSequences = message.stopSequences;
    }
    if (message.streamingEnabled !== false) {
      obj.streamingEnabled = message.streamingEnabled;
    }
    if (message.preferredFramework !== 0) {
      obj.preferredFramework = inferenceFrameworkToJSON(message.preferredFramework);
    }
    if (message.systemPrompt !== undefined) {
      obj.systemPrompt = message.systemPrompt;
    }
    if (message.jsonSchema !== undefined) {
      obj.jsonSchema = message.jsonSchema;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LLMGenerationOptions>, I>>(base?: I): LLMGenerationOptions {
    return LLMGenerationOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LLMGenerationOptions>, I>>(object: I): LLMGenerationOptions {
    const message = createBaseLLMGenerationOptions();
    message.maxTokens = object.maxTokens ?? 0;
    message.temperature = object.temperature ?? 0;
    message.topP = object.topP ?? 0;
    message.topK = object.topK ?? 0;
    message.repetitionPenalty = object.repetitionPenalty ?? 0;
    message.stopSequences = object.stopSequences?.map((e) => e) || [];
    message.streamingEnabled = object.streamingEnabled ?? false;
    message.preferredFramework = object.preferredFramework ?? 0;
    message.systemPrompt = object.systemPrompt ?? undefined;
    message.jsonSchema = object.jsonSchema ?? undefined;
    return message;
  },
};

function createBaseLLMGenerationResult(): LLMGenerationResult {
  return {
    text: "",
    thinkingContent: undefined,
    inputTokens: 0,
    tokensGenerated: 0,
    modelUsed: "",
    generationTimeMs: 0,
    ttftMs: undefined,
    tokensPerSecond: 0,
    framework: undefined,
    finishReason: "",
    thinkingTokens: 0,
    responseTokens: 0,
    jsonOutput: undefined,
  };
}

export const LLMGenerationResult = {
  encode(message: LLMGenerationResult, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.thinkingContent !== undefined) {
      writer.uint32(18).string(message.thinkingContent);
    }
    if (message.inputTokens !== 0) {
      writer.uint32(24).int32(message.inputTokens);
    }
    if (message.tokensGenerated !== 0) {
      writer.uint32(32).int32(message.tokensGenerated);
    }
    if (message.modelUsed !== "") {
      writer.uint32(42).string(message.modelUsed);
    }
    if (message.generationTimeMs !== 0) {
      writer.uint32(49).double(message.generationTimeMs);
    }
    if (message.ttftMs !== undefined) {
      writer.uint32(57).double(message.ttftMs);
    }
    if (message.tokensPerSecond !== 0) {
      writer.uint32(65).double(message.tokensPerSecond);
    }
    if (message.framework !== undefined) {
      writer.uint32(74).string(message.framework);
    }
    if (message.finishReason !== "") {
      writer.uint32(82).string(message.finishReason);
    }
    if (message.thinkingTokens !== 0) {
      writer.uint32(88).int32(message.thinkingTokens);
    }
    if (message.responseTokens !== 0) {
      writer.uint32(96).int32(message.responseTokens);
    }
    if (message.jsonOutput !== undefined) {
      writer.uint32(106).string(message.jsonOutput);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LLMGenerationResult {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLLMGenerationResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.thinkingContent = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.inputTokens = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.tokensGenerated = reader.int32();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.modelUsed = reader.string();
          continue;
        case 6:
          if (tag !== 49) {
            break;
          }

          message.generationTimeMs = reader.double();
          continue;
        case 7:
          if (tag !== 57) {
            break;
          }

          message.ttftMs = reader.double();
          continue;
        case 8:
          if (tag !== 65) {
            break;
          }

          message.tokensPerSecond = reader.double();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.framework = reader.string();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.finishReason = reader.string();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.thinkingTokens = reader.int32();
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.responseTokens = reader.int32();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.jsonOutput = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LLMGenerationResult {
    return {
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      thinkingContent: isSet(object.thinkingContent) ? globalThis.String(object.thinkingContent) : undefined,
      inputTokens: isSet(object.inputTokens) ? globalThis.Number(object.inputTokens) : 0,
      tokensGenerated: isSet(object.tokensGenerated) ? globalThis.Number(object.tokensGenerated) : 0,
      modelUsed: isSet(object.modelUsed) ? globalThis.String(object.modelUsed) : "",
      generationTimeMs: isSet(object.generationTimeMs) ? globalThis.Number(object.generationTimeMs) : 0,
      ttftMs: isSet(object.ttftMs) ? globalThis.Number(object.ttftMs) : undefined,
      tokensPerSecond: isSet(object.tokensPerSecond) ? globalThis.Number(object.tokensPerSecond) : 0,
      framework: isSet(object.framework) ? globalThis.String(object.framework) : undefined,
      finishReason: isSet(object.finishReason) ? globalThis.String(object.finishReason) : "",
      thinkingTokens: isSet(object.thinkingTokens) ? globalThis.Number(object.thinkingTokens) : 0,
      responseTokens: isSet(object.responseTokens) ? globalThis.Number(object.responseTokens) : 0,
      jsonOutput: isSet(object.jsonOutput) ? globalThis.String(object.jsonOutput) : undefined,
    };
  },

  toJSON(message: LLMGenerationResult): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.thinkingContent !== undefined) {
      obj.thinkingContent = message.thinkingContent;
    }
    if (message.inputTokens !== 0) {
      obj.inputTokens = Math.round(message.inputTokens);
    }
    if (message.tokensGenerated !== 0) {
      obj.tokensGenerated = Math.round(message.tokensGenerated);
    }
    if (message.modelUsed !== "") {
      obj.modelUsed = message.modelUsed;
    }
    if (message.generationTimeMs !== 0) {
      obj.generationTimeMs = message.generationTimeMs;
    }
    if (message.ttftMs !== undefined) {
      obj.ttftMs = message.ttftMs;
    }
    if (message.tokensPerSecond !== 0) {
      obj.tokensPerSecond = message.tokensPerSecond;
    }
    if (message.framework !== undefined) {
      obj.framework = message.framework;
    }
    if (message.finishReason !== "") {
      obj.finishReason = message.finishReason;
    }
    if (message.thinkingTokens !== 0) {
      obj.thinkingTokens = Math.round(message.thinkingTokens);
    }
    if (message.responseTokens !== 0) {
      obj.responseTokens = Math.round(message.responseTokens);
    }
    if (message.jsonOutput !== undefined) {
      obj.jsonOutput = message.jsonOutput;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LLMGenerationResult>, I>>(base?: I): LLMGenerationResult {
    return LLMGenerationResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LLMGenerationResult>, I>>(object: I): LLMGenerationResult {
    const message = createBaseLLMGenerationResult();
    message.text = object.text ?? "";
    message.thinkingContent = object.thinkingContent ?? undefined;
    message.inputTokens = object.inputTokens ?? 0;
    message.tokensGenerated = object.tokensGenerated ?? 0;
    message.modelUsed = object.modelUsed ?? "";
    message.generationTimeMs = object.generationTimeMs ?? 0;
    message.ttftMs = object.ttftMs ?? undefined;
    message.tokensPerSecond = object.tokensPerSecond ?? 0;
    message.framework = object.framework ?? undefined;
    message.finishReason = object.finishReason ?? "";
    message.thinkingTokens = object.thinkingTokens ?? 0;
    message.responseTokens = object.responseTokens ?? 0;
    message.jsonOutput = object.jsonOutput ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
