// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v7.34.1
// source: rag.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * RAGConfiguration — low-level pipeline config (pre-IDL hand-rolled).
 *
 * This is the runtime configuration consumed by the RAG pipeline directly,
 * distinct from solutions.proto::RAGConfig (which is the high-level solution
 * spec resolved through the model registry). RAGConfiguration takes raw model
 * paths because the pipeline runs after model resolution has already happened.
 * ---------------------------------------------------------------------------
 */
export interface RAGConfiguration {
  /** Filesystem path to the embedding model (typically ONNX). */
  embeddingModelPath: string;
  /** Filesystem path to the LLM model (typically GGUF). */
  llmModelPath: string;
  /**
   * Embedding vector dimension — must match the embedding model.
   * Common: 384 (all-MiniLM-L6-v2), 768 (bge-base), 1024 (bge-large).
   */
  embeddingDimension: number;
  /** Number of top chunks to retrieve per query. */
  topK: number;
  /**
   * Minimum cosine similarity threshold (0.0–1.0). Chunks below this
   * score are discarded before being passed to the LLM as context.
   */
  similarityThreshold: number;
  /** Tokens per chunk when splitting documents during ingestion. */
  chunkSize: number;
  /** Overlap tokens between consecutive chunks. Must be < chunk_size. */
  chunkOverlap: number;
}

/**
 * ---------------------------------------------------------------------------
 * RAGQueryOptions — per-query sampling and prompt overrides.
 * ---------------------------------------------------------------------------
 */
export interface RAGQueryOptions {
  /** The user question to answer. Required (empty = no-op). */
  question: string;
  /** Optional system prompt override. Unset uses the pipeline default. */
  systemPrompt?:
    | string
    | undefined;
  /** Maximum tokens to generate in the answer. */
  maxTokens: number;
  /** Sampling temperature. 0.0 = greedy, higher = more random. */
  temperature: number;
  /** Nucleus (top-p) sampling parameter. 1.0 = disabled. */
  topP: number;
  /** Top-k sampling parameter. 0 = disabled. */
  topK: number;
}

/**
 * ---------------------------------------------------------------------------
 * RAGSearchResult — a single retrieved document chunk with similarity score.
 * ---------------------------------------------------------------------------
 */
export interface RAGSearchResult {
  /** Unique identifier of the chunk (assigned at ingestion time). */
  chunkId: string;
  /** Text content of the chunk (the actual snippet shown to the LLM). */
  text: string;
  /** Cosine similarity score (0.0–1.0). Higher = more relevant. */
  similarityScore: number;
  /**
   * Optional source document identifier (filename, URL, or document ID).
   * Set when the chunk's origin is tracked at ingestion time.
   */
  sourceDocument?:
    | string
    | undefined;
  /**
   * Free-form metadata associated with the chunk (e.g. page number, section,
   * ingestion timestamp). Pre-IDL all SDKs encoded this as a JSON string;
   * canonicalized here as a typed map so consumers don't re-parse.
   */
  metadata: { [key: string]: string };
}

export interface RAGSearchResult_MetadataEntry {
  key: string;
  value: string;
}

/**
 * ---------------------------------------------------------------------------
 * RAGResult — the full result of a RAG query.
 * ---------------------------------------------------------------------------
 */
export interface RAGResult {
  /** The LLM-generated answer grounded in the retrieved context. */
  answer: string;
  /**
   * Document chunks retrieved during vector search and used as context.
   * Order matches retrieval rank (highest similarity first).
   */
  retrievedChunks: RAGSearchResult[];
  /**
   * Full context string passed to the LLM (chunks joined into a prompt).
   * May be empty for queries with no matching chunks.
   */
  contextUsed: string;
  /** Time spent in the retrieval phase (vector search), in milliseconds. */
  retrievalTimeMs: number;
  /** Time spent in the LLM generation phase, in milliseconds. */
  generationTimeMs: number;
  /**
   * Total end-to-end query time (retrieval + generation + overhead),
   * in milliseconds.
   */
  totalTimeMs: number;
}

/**
 * ---------------------------------------------------------------------------
 * RAGStatistics — index-level counters for the RAG pipeline.
 *
 * Returned by RunAnywhere.rag.statistics() / ragGetStatistics().
 * ---------------------------------------------------------------------------
 */
export interface RAGStatistics {
  /** Total number of documents ever ingested into the index. */
  indexedDocuments: number;
  /** Total number of chunks across all indexed documents. */
  indexedChunks: number;
  /** Approximate total token count across all indexed chunks. */
  totalTokensIndexed: number;
  /**
   * Wall-clock timestamp of the most recent ingestion, in milliseconds
   * since Unix epoch. 0 = no ingestion yet.
   */
  lastUpdatedMs: number;
  /**
   * Filesystem path to the on-disk index, when applicable. Unset for
   * in-memory-only indexes.
   */
  indexPath?: string | undefined;
}

function createBaseRAGConfiguration(): RAGConfiguration {
  return {
    embeddingModelPath: "",
    llmModelPath: "",
    embeddingDimension: 0,
    topK: 0,
    similarityThreshold: 0,
    chunkSize: 0,
    chunkOverlap: 0,
  };
}

export const RAGConfiguration = {
  encode(message: RAGConfiguration, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.embeddingModelPath !== "") {
      writer.uint32(10).string(message.embeddingModelPath);
    }
    if (message.llmModelPath !== "") {
      writer.uint32(18).string(message.llmModelPath);
    }
    if (message.embeddingDimension !== 0) {
      writer.uint32(24).int32(message.embeddingDimension);
    }
    if (message.topK !== 0) {
      writer.uint32(32).int32(message.topK);
    }
    if (message.similarityThreshold !== 0) {
      writer.uint32(45).float(message.similarityThreshold);
    }
    if (message.chunkSize !== 0) {
      writer.uint32(48).int32(message.chunkSize);
    }
    if (message.chunkOverlap !== 0) {
      writer.uint32(56).int32(message.chunkOverlap);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RAGConfiguration {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRAGConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.embeddingModelPath = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.llmModelPath = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.embeddingDimension = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.topK = reader.int32();
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.similarityThreshold = reader.float();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.chunkSize = reader.int32();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.chunkOverlap = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RAGConfiguration {
    return {
      embeddingModelPath: isSet(object.embeddingModelPath) ? globalThis.String(object.embeddingModelPath) : "",
      llmModelPath: isSet(object.llmModelPath) ? globalThis.String(object.llmModelPath) : "",
      embeddingDimension: isSet(object.embeddingDimension) ? globalThis.Number(object.embeddingDimension) : 0,
      topK: isSet(object.topK) ? globalThis.Number(object.topK) : 0,
      similarityThreshold: isSet(object.similarityThreshold) ? globalThis.Number(object.similarityThreshold) : 0,
      chunkSize: isSet(object.chunkSize) ? globalThis.Number(object.chunkSize) : 0,
      chunkOverlap: isSet(object.chunkOverlap) ? globalThis.Number(object.chunkOverlap) : 0,
    };
  },

  toJSON(message: RAGConfiguration): unknown {
    const obj: any = {};
    if (message.embeddingModelPath !== "") {
      obj.embeddingModelPath = message.embeddingModelPath;
    }
    if (message.llmModelPath !== "") {
      obj.llmModelPath = message.llmModelPath;
    }
    if (message.embeddingDimension !== 0) {
      obj.embeddingDimension = Math.round(message.embeddingDimension);
    }
    if (message.topK !== 0) {
      obj.topK = Math.round(message.topK);
    }
    if (message.similarityThreshold !== 0) {
      obj.similarityThreshold = message.similarityThreshold;
    }
    if (message.chunkSize !== 0) {
      obj.chunkSize = Math.round(message.chunkSize);
    }
    if (message.chunkOverlap !== 0) {
      obj.chunkOverlap = Math.round(message.chunkOverlap);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RAGConfiguration>, I>>(base?: I): RAGConfiguration {
    return RAGConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RAGConfiguration>, I>>(object: I): RAGConfiguration {
    const message = createBaseRAGConfiguration();
    message.embeddingModelPath = object.embeddingModelPath ?? "";
    message.llmModelPath = object.llmModelPath ?? "";
    message.embeddingDimension = object.embeddingDimension ?? 0;
    message.topK = object.topK ?? 0;
    message.similarityThreshold = object.similarityThreshold ?? 0;
    message.chunkSize = object.chunkSize ?? 0;
    message.chunkOverlap = object.chunkOverlap ?? 0;
    return message;
  },
};

function createBaseRAGQueryOptions(): RAGQueryOptions {
  return { question: "", systemPrompt: undefined, maxTokens: 0, temperature: 0, topP: 0, topK: 0 };
}

export const RAGQueryOptions = {
  encode(message: RAGQueryOptions, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.question !== "") {
      writer.uint32(10).string(message.question);
    }
    if (message.systemPrompt !== undefined) {
      writer.uint32(18).string(message.systemPrompt);
    }
    if (message.maxTokens !== 0) {
      writer.uint32(24).int32(message.maxTokens);
    }
    if (message.temperature !== 0) {
      writer.uint32(37).float(message.temperature);
    }
    if (message.topP !== 0) {
      writer.uint32(45).float(message.topP);
    }
    if (message.topK !== 0) {
      writer.uint32(48).int32(message.topK);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RAGQueryOptions {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRAGQueryOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.question = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.systemPrompt = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.maxTokens = reader.int32();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.temperature = reader.float();
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.topP = reader.float();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.topK = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RAGQueryOptions {
    return {
      question: isSet(object.question) ? globalThis.String(object.question) : "",
      systemPrompt: isSet(object.systemPrompt) ? globalThis.String(object.systemPrompt) : undefined,
      maxTokens: isSet(object.maxTokens) ? globalThis.Number(object.maxTokens) : 0,
      temperature: isSet(object.temperature) ? globalThis.Number(object.temperature) : 0,
      topP: isSet(object.topP) ? globalThis.Number(object.topP) : 0,
      topK: isSet(object.topK) ? globalThis.Number(object.topK) : 0,
    };
  },

  toJSON(message: RAGQueryOptions): unknown {
    const obj: any = {};
    if (message.question !== "") {
      obj.question = message.question;
    }
    if (message.systemPrompt !== undefined) {
      obj.systemPrompt = message.systemPrompt;
    }
    if (message.maxTokens !== 0) {
      obj.maxTokens = Math.round(message.maxTokens);
    }
    if (message.temperature !== 0) {
      obj.temperature = message.temperature;
    }
    if (message.topP !== 0) {
      obj.topP = message.topP;
    }
    if (message.topK !== 0) {
      obj.topK = Math.round(message.topK);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RAGQueryOptions>, I>>(base?: I): RAGQueryOptions {
    return RAGQueryOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RAGQueryOptions>, I>>(object: I): RAGQueryOptions {
    const message = createBaseRAGQueryOptions();
    message.question = object.question ?? "";
    message.systemPrompt = object.systemPrompt ?? undefined;
    message.maxTokens = object.maxTokens ?? 0;
    message.temperature = object.temperature ?? 0;
    message.topP = object.topP ?? 0;
    message.topK = object.topK ?? 0;
    return message;
  },
};

function createBaseRAGSearchResult(): RAGSearchResult {
  return { chunkId: "", text: "", similarityScore: 0, sourceDocument: undefined, metadata: {} };
}

export const RAGSearchResult = {
  encode(message: RAGSearchResult, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.chunkId !== "") {
      writer.uint32(10).string(message.chunkId);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    if (message.similarityScore !== 0) {
      writer.uint32(29).float(message.similarityScore);
    }
    if (message.sourceDocument !== undefined) {
      writer.uint32(34).string(message.sourceDocument);
    }
    Object.entries(message.metadata).forEach(([key, value]) => {
      RAGSearchResult_MetadataEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).ldelim();
    });
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RAGSearchResult {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRAGSearchResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.chunkId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        case 3:
          if (tag !== 29) {
            break;
          }

          message.similarityScore = reader.float();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.sourceDocument = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          const entry5 = RAGSearchResult_MetadataEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.metadata[entry5.key] = entry5.value;
          }
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RAGSearchResult {
    return {
      chunkId: isSet(object.chunkId) ? globalThis.String(object.chunkId) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      similarityScore: isSet(object.similarityScore) ? globalThis.Number(object.similarityScore) : 0,
      sourceDocument: isSet(object.sourceDocument) ? globalThis.String(object.sourceDocument) : undefined,
      metadata: isObject(object.metadata)
        ? Object.entries(object.metadata).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: RAGSearchResult): unknown {
    const obj: any = {};
    if (message.chunkId !== "") {
      obj.chunkId = message.chunkId;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.similarityScore !== 0) {
      obj.similarityScore = message.similarityScore;
    }
    if (message.sourceDocument !== undefined) {
      obj.sourceDocument = message.sourceDocument;
    }
    if (message.metadata) {
      const entries = Object.entries(message.metadata);
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RAGSearchResult>, I>>(base?: I): RAGSearchResult {
    return RAGSearchResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RAGSearchResult>, I>>(object: I): RAGSearchResult {
    const message = createBaseRAGSearchResult();
    message.chunkId = object.chunkId ?? "";
    message.text = object.text ?? "";
    message.similarityScore = object.similarityScore ?? 0;
    message.sourceDocument = object.sourceDocument ?? undefined;
    message.metadata = Object.entries(object.metadata ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseRAGSearchResult_MetadataEntry(): RAGSearchResult_MetadataEntry {
  return { key: "", value: "" };
}

export const RAGSearchResult_MetadataEntry = {
  encode(message: RAGSearchResult_MetadataEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RAGSearchResult_MetadataEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRAGSearchResult_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RAGSearchResult_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: RAGSearchResult_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RAGSearchResult_MetadataEntry>, I>>(base?: I): RAGSearchResult_MetadataEntry {
    return RAGSearchResult_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RAGSearchResult_MetadataEntry>, I>>(
    object: I,
  ): RAGSearchResult_MetadataEntry {
    const message = createBaseRAGSearchResult_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseRAGResult(): RAGResult {
  return { answer: "", retrievedChunks: [], contextUsed: "", retrievalTimeMs: 0, generationTimeMs: 0, totalTimeMs: 0 };
}

export const RAGResult = {
  encode(message: RAGResult, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.answer !== "") {
      writer.uint32(10).string(message.answer);
    }
    for (const v of message.retrievedChunks) {
      RAGSearchResult.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    if (message.contextUsed !== "") {
      writer.uint32(26).string(message.contextUsed);
    }
    if (message.retrievalTimeMs !== 0) {
      writer.uint32(32).int64(message.retrievalTimeMs);
    }
    if (message.generationTimeMs !== 0) {
      writer.uint32(40).int64(message.generationTimeMs);
    }
    if (message.totalTimeMs !== 0) {
      writer.uint32(48).int64(message.totalTimeMs);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RAGResult {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRAGResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.answer = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.retrievedChunks.push(RAGSearchResult.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.contextUsed = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.retrievalTimeMs = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.generationTimeMs = longToNumber(reader.int64() as Long);
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.totalTimeMs = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RAGResult {
    return {
      answer: isSet(object.answer) ? globalThis.String(object.answer) : "",
      retrievedChunks: globalThis.Array.isArray(object?.retrievedChunks)
        ? object.retrievedChunks.map((e: any) => RAGSearchResult.fromJSON(e))
        : [],
      contextUsed: isSet(object.contextUsed) ? globalThis.String(object.contextUsed) : "",
      retrievalTimeMs: isSet(object.retrievalTimeMs) ? globalThis.Number(object.retrievalTimeMs) : 0,
      generationTimeMs: isSet(object.generationTimeMs) ? globalThis.Number(object.generationTimeMs) : 0,
      totalTimeMs: isSet(object.totalTimeMs) ? globalThis.Number(object.totalTimeMs) : 0,
    };
  },

  toJSON(message: RAGResult): unknown {
    const obj: any = {};
    if (message.answer !== "") {
      obj.answer = message.answer;
    }
    if (message.retrievedChunks?.length) {
      obj.retrievedChunks = message.retrievedChunks.map((e) => RAGSearchResult.toJSON(e));
    }
    if (message.contextUsed !== "") {
      obj.contextUsed = message.contextUsed;
    }
    if (message.retrievalTimeMs !== 0) {
      obj.retrievalTimeMs = Math.round(message.retrievalTimeMs);
    }
    if (message.generationTimeMs !== 0) {
      obj.generationTimeMs = Math.round(message.generationTimeMs);
    }
    if (message.totalTimeMs !== 0) {
      obj.totalTimeMs = Math.round(message.totalTimeMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RAGResult>, I>>(base?: I): RAGResult {
    return RAGResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RAGResult>, I>>(object: I): RAGResult {
    const message = createBaseRAGResult();
    message.answer = object.answer ?? "";
    message.retrievedChunks = object.retrievedChunks?.map((e) => RAGSearchResult.fromPartial(e)) || [];
    message.contextUsed = object.contextUsed ?? "";
    message.retrievalTimeMs = object.retrievalTimeMs ?? 0;
    message.generationTimeMs = object.generationTimeMs ?? 0;
    message.totalTimeMs = object.totalTimeMs ?? 0;
    return message;
  },
};

function createBaseRAGStatistics(): RAGStatistics {
  return { indexedDocuments: 0, indexedChunks: 0, totalTokensIndexed: 0, lastUpdatedMs: 0, indexPath: undefined };
}

export const RAGStatistics = {
  encode(message: RAGStatistics, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.indexedDocuments !== 0) {
      writer.uint32(8).int64(message.indexedDocuments);
    }
    if (message.indexedChunks !== 0) {
      writer.uint32(16).int64(message.indexedChunks);
    }
    if (message.totalTokensIndexed !== 0) {
      writer.uint32(24).int64(message.totalTokensIndexed);
    }
    if (message.lastUpdatedMs !== 0) {
      writer.uint32(32).int64(message.lastUpdatedMs);
    }
    if (message.indexPath !== undefined) {
      writer.uint32(42).string(message.indexPath);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RAGStatistics {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRAGStatistics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.indexedDocuments = longToNumber(reader.int64() as Long);
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.indexedChunks = longToNumber(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.totalTokensIndexed = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.lastUpdatedMs = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.indexPath = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RAGStatistics {
    return {
      indexedDocuments: isSet(object.indexedDocuments) ? globalThis.Number(object.indexedDocuments) : 0,
      indexedChunks: isSet(object.indexedChunks) ? globalThis.Number(object.indexedChunks) : 0,
      totalTokensIndexed: isSet(object.totalTokensIndexed) ? globalThis.Number(object.totalTokensIndexed) : 0,
      lastUpdatedMs: isSet(object.lastUpdatedMs) ? globalThis.Number(object.lastUpdatedMs) : 0,
      indexPath: isSet(object.indexPath) ? globalThis.String(object.indexPath) : undefined,
    };
  },

  toJSON(message: RAGStatistics): unknown {
    const obj: any = {};
    if (message.indexedDocuments !== 0) {
      obj.indexedDocuments = Math.round(message.indexedDocuments);
    }
    if (message.indexedChunks !== 0) {
      obj.indexedChunks = Math.round(message.indexedChunks);
    }
    if (message.totalTokensIndexed !== 0) {
      obj.totalTokensIndexed = Math.round(message.totalTokensIndexed);
    }
    if (message.lastUpdatedMs !== 0) {
      obj.lastUpdatedMs = Math.round(message.lastUpdatedMs);
    }
    if (message.indexPath !== undefined) {
      obj.indexPath = message.indexPath;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RAGStatistics>, I>>(base?: I): RAGStatistics {
    return RAGStatistics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RAGStatistics>, I>>(object: I): RAGStatistics {
    const message = createBaseRAGStatistics();
    message.indexedDocuments = object.indexedDocuments ?? 0;
    message.indexedChunks = object.indexedChunks ?? 0;
    message.totalTokensIndexed = object.totalTokensIndexed ?? 0;
    message.lastUpdatedMs = object.lastUpdatedMs ?? 0;
    message.indexPath = object.indexPath ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
