// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v7.34.1
// source: vad_options.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "runanywhere.v1";

/**
 * ---------------------------------------------------------------------------
 * Speech-activity lifecycle kind.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift:235               (started, ended)
 *   Kotlin VADTypes.kt:171                  (STARTED, ENDED)
 *   Dart   runanywhere_vad.dart:28          (started, ended)
 *   RN     VADTypes.ts:43                   ('started' | 'ended')
 *   Web    VADTypes.ts:8                    (Started, Ended, Ongoing)   ← only SDK with ONGOING
 *   C ABI  rac_vad_types.h:107              (RAC_SPEECH_STARTED, RAC_SPEECH_ENDED, RAC_SPEECH_ONGOING)
 * Canonical union: STARTED, ENDED, ONGOING.
 * ---------------------------------------------------------------------------
 */
export enum SpeechActivityKind {
  /** SPEECH_ACTIVITY_KIND_UNSPECIFIED - Reserved (proto3 default) */
  SPEECH_ACTIVITY_KIND_UNSPECIFIED = 0,
  SPEECH_ACTIVITY_KIND_SPEECH_STARTED = 1,
  SPEECH_ACTIVITY_KIND_SPEECH_ENDED = 2,
  SPEECH_ACTIVITY_KIND_ONGOING = 3,
  UNRECOGNIZED = -1,
}

export function speechActivityKindFromJSON(object: any): SpeechActivityKind {
  switch (object) {
    case 0:
    case "SPEECH_ACTIVITY_KIND_UNSPECIFIED":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_UNSPECIFIED;
    case 1:
    case "SPEECH_ACTIVITY_KIND_SPEECH_STARTED":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_STARTED;
    case 2:
    case "SPEECH_ACTIVITY_KIND_SPEECH_ENDED":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_ENDED;
    case 3:
    case "SPEECH_ACTIVITY_KIND_ONGOING":
      return SpeechActivityKind.SPEECH_ACTIVITY_KIND_ONGOING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SpeechActivityKind.UNRECOGNIZED;
  }
}

export function speechActivityKindToJSON(object: SpeechActivityKind): string {
  switch (object) {
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_UNSPECIFIED:
      return "SPEECH_ACTIVITY_KIND_UNSPECIFIED";
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_STARTED:
      return "SPEECH_ACTIVITY_KIND_SPEECH_STARTED";
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_SPEECH_ENDED:
      return "SPEECH_ACTIVITY_KIND_SPEECH_ENDED";
    case SpeechActivityKind.SPEECH_ACTIVITY_KIND_ONGOING:
      return "SPEECH_ACTIVITY_KIND_ONGOING";
    case SpeechActivityKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * ---------------------------------------------------------------------------
 * Compile-time / load-time configuration for a VAD instance.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift:15                (energyThreshold, sampleRate, frameLength,
 *                                            enableAutoCalibration, calibrationMultiplier)
 *   Kotlin VADTypes.kt:26                   (same five fields, defaults match Swift)
 *   Dart   vad_configuration.dart:5         (same five fields)
 *   RN     VADTypes.ts:12                   (sampleRate, frameLength, energyThreshold;
 *                                            no calibration fields)
 *   Web    VADTypes.ts —                    (no VADConfiguration; per-backend in WebSDK)
 *   C ABI  rac_vad_types.h:63 (rac_vad_config_t)
 *                                           (model_id, preferred_framework, energy_threshold,
 *                                            sample_rate, frame_length, enable_auto_calibration,
 *                                            calibration_multiplier)
 *
 * `frame_length_ms` is the canonical wire field — Swift/Kotlin/Dart/C use
 * seconds (float), but ms is more interoperable across protobuf consumers.
 * Generators must convert when binding to per-platform types.
 * ---------------------------------------------------------------------------
 */
export interface VADConfiguration {
  /**
   * Optional model id; empty when using the built-in energy VAD.
   * C ABI: model_id (rac_vad_config_t::model_id, may be NULL).
   */
  modelId: string;
  /** PCM sample rate in Hz. Default 16000 (RAC_VAD_DEFAULT_SAMPLE_RATE). */
  sampleRate: number;
  /**
   * Frame length in milliseconds. Default 100 (Swift/Kotlin/Dart store
   * 0.1 seconds; we canonicalize to ms on the wire).
   */
  frameLengthMs: number;
  /**
   * Energy threshold in [0.0, 1.0] for voice detection.
   * Recommended range 0.01–0.05; default 0.015 across SDKs.
   */
  threshold: number;
  /**
   * When true, the VAD performs ambient-noise calibration and uses the
   * result as a multiplier on the threshold (see calibration_multiplier
   * in the C ABI). Defaults to false.
   */
  enableAutoCalibration: boolean;
}

/**
 * ---------------------------------------------------------------------------
 * Runtime / per-call options applied to a VAD pass.
 * Sources pre-IDL:
 *   Swift  none — Swift uses raw arguments to detectSpeech().
 *   Kotlin none — same as Swift.
 *   Dart   runanywhere_vad.dart:99          (`detectSpeech` takes raw Float32List)
 *   RN     VADTypes.ts —                    (no per-call options struct)
 *   Web    VADTypes.ts —                    (no per-call options struct)
 *   C ABI  rac_vad_types.h:123 (rac_vad_input_t)
 *                                           (audio_samples, num_samples,
 *                                            energy_threshold_override)
 *
 * We canonicalize on the energy_threshold_override + the speech-duration
 * gates that already appear as constants in rac_vad_types.h:50-51:
 *   RAC_VAD_MIN_SPEECH_DURATION_MS  = 100
 *   RAC_VAD_MIN_SILENCE_DURATION_MS = 300
 * Surfacing them as fields lets callers tune debouncing without a rebuild.
 * ---------------------------------------------------------------------------
 */
export interface VADOptions {
  /**
   * Per-call energy threshold override. Use 0 (default) to keep the
   * configured threshold. Mirrors rac_vad_input_t::energy_threshold_override
   * (which uses -1 as the sentinel; on the wire we use 0 for proto3
   * default semantics — generators emit -1 when this is unset).
   */
  threshold: number;
  /**
   * Minimum continuous speech duration (ms) before SPEECH_STARTED fires.
   * Default 100 (RAC_VAD_MIN_SPEECH_DURATION_MS).
   */
  minSpeechDurationMs: number;
  /**
   * Minimum continuous silence duration (ms) before SPEECH_ENDED fires.
   * Default 300 (RAC_VAD_MIN_SILENCE_DURATION_MS).
   */
  minSilenceDurationMs: number;
}

/**
 * ---------------------------------------------------------------------------
 * Result of a single VAD pass over a chunk of PCM audio.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift —                 (no struct; bool returned from detectSpeech())
 *   Kotlin VADTypes.kt:152                  (isSpeech, confidence, energyLevel,
 *                                            statistics, timestamp)
 *   Dart   dart_bridge_vad.dart:290         (isSpeech, energy, speechProbability)
 *   RN     VADTypes.ts:26                   (isSpeech, probability, startTime, endTime)
 *   Web    VADTypes.ts —                    (no VADResult; only SpeechSegment)
 *   C ABI  rac_vad_types.h:151 (rac_vad_output_t)
 *                                           (is_speech_detected, energy_level, timestamp_ms)
 *
 * Drift notes:
 *   - Kotlin's `confidence` and Dart's `speechProbability` and RN's
 *     `probability` collapse onto the canonical `confidence` field.
 *   - Kotlin/RN/C all carry timing — we encode duration_ms (length of the
 *     analyzed frame). Wall-clock timestamps belong on the carrying envelope
 *     (e.g. VoiceEvent.timestamp_us in voice_events.proto).
 * ---------------------------------------------------------------------------
 */
export interface VADResult {
  /**
   * Whether speech was detected in this frame.
   * Mirrors rac_vad_output_t::is_speech_detected.
   */
  isSpeech: boolean;
  /** Confidence / probability in [0.0, 1.0]. Backend-dependent. */
  confidence: number;
  /**
   * RMS energy level of the analyzed frame.
   * Mirrors rac_vad_output_t::energy_level.
   */
  energy: number;
  /** Length of the analyzed frame in milliseconds. */
  durationMs: number;
}

/**
 * ---------------------------------------------------------------------------
 * Internal VAD statistics, exposed for debugging / waveform UIs.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift:174               (current, threshold, ambient,
 *                                            recentAvg, recentMax)
 *   Kotlin VADTypes.kt:123                  (same five fields)
 *   Dart   none — Dart bridge does not surface statistics yet.
 *   RN     VADTypes.ts —                    (none)
 *   Web    VADTypes.ts —                    (none)
 *   C ABI  rac_vad_types.h:194 (rac_vad_statistics_t)
 *                                           (current_threshold, ambient_noise_level,
 *                                            total_speech_segments, total_speech_duration_ms,
 *                                            average_energy, peak_energy)
 *
 * We canonicalize on the Swift/Kotlin shape because it is the most widely
 * used. The richer C ABI fields (segment counts, totals) belong on a future
 * VADAnalytics message and are intentionally NOT included here.
 * ---------------------------------------------------------------------------
 */
export interface VADStatistics {
  /** Current instantaneous energy level. (Swift/Kotlin: `current`) */
  currentEnergy: number;
  /**
   * Energy threshold currently in use. (Swift/Kotlin: `threshold`;
   * C ABI: rac_vad_statistics_t::current_threshold)
   */
  currentThreshold: number;
  /**
   * Ambient noise level captured by calibration. (Swift/Kotlin: `ambient`;
   * C ABI: rac_vad_statistics_t::ambient_noise_level)
   */
  ambientLevel: number;
  /** Recent moving-window average energy. (Swift/Kotlin: `recentAvg`) */
  recentAvg: number;
  /** Recent moving-window peak energy. (Swift/Kotlin: `recentMax`) */
  recentMax: number;
}

/**
 * ---------------------------------------------------------------------------
 * Activity transition emitted by the VAD as it watches a stream.
 * Sources pre-IDL:
 *   Swift  VADTypes.swift:235               (SpeechActivityEvent enum: started/ended)
 *   Kotlin VADTypes.kt:171                  (SpeechActivityEvent enum: STARTED/ENDED)
 *   Dart   runanywhere_vad.dart:28          (SpeechActivityEvent enum: started/ended)
 *   RN     VADTypes.ts:43                   ('started' | 'ended' string union)
 *   Web    VADTypes.ts:8                    (SpeechActivity enum: Started/Ended/Ongoing)
 *   C ABI  rac_vad_types.h:107 (rac_speech_activity_t)
 *                                           (RAC_SPEECH_STARTED/ENDED/ONGOING)
 *
 * Distinct from voice_events.proto's `VADEvent`/`VADEventType`, which carry
 * the broader pipeline-level taxonomy (BARGE_IN, END_OF_UTTERANCE, etc).
 * `SpeechActivityEvent` here is the narrow component-level transition.
 * ---------------------------------------------------------------------------
 */
export interface SpeechActivityEvent {
  /** Which transition happened. */
  eventType: SpeechActivityKind;
  /**
   * Wall-clock time of the transition, in milliseconds since epoch.
   * Aligns with rac_vad_output_t::timestamp_ms.
   */
  timestampMs: number;
  /**
   * Optional duration of the speech / silence that triggered this event,
   * in milliseconds. Set on SPEECH_ENDED to communicate the just-finished
   * utterance length; left zero on SPEECH_STARTED.
   */
  durationMs: number;
}

function createBaseVADConfiguration(): VADConfiguration {
  return { modelId: "", sampleRate: 0, frameLengthMs: 0, threshold: 0, enableAutoCalibration: false };
}

export const VADConfiguration = {
  encode(message: VADConfiguration, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.modelId !== "") {
      writer.uint32(10).string(message.modelId);
    }
    if (message.sampleRate !== 0) {
      writer.uint32(16).int32(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      writer.uint32(24).int32(message.frameLengthMs);
    }
    if (message.threshold !== 0) {
      writer.uint32(37).float(message.threshold);
    }
    if (message.enableAutoCalibration !== false) {
      writer.uint32(40).bool(message.enableAutoCalibration);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VADConfiguration {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.modelId = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.sampleRate = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.frameLengthMs = reader.int32();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.threshold = reader.float();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.enableAutoCalibration = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADConfiguration {
    return {
      modelId: isSet(object.modelId) ? globalThis.String(object.modelId) : "",
      sampleRate: isSet(object.sampleRate) ? globalThis.Number(object.sampleRate) : 0,
      frameLengthMs: isSet(object.frameLengthMs) ? globalThis.Number(object.frameLengthMs) : 0,
      threshold: isSet(object.threshold) ? globalThis.Number(object.threshold) : 0,
      enableAutoCalibration: isSet(object.enableAutoCalibration)
        ? globalThis.Boolean(object.enableAutoCalibration)
        : false,
    };
  },

  toJSON(message: VADConfiguration): unknown {
    const obj: any = {};
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.sampleRate !== 0) {
      obj.sampleRate = Math.round(message.sampleRate);
    }
    if (message.frameLengthMs !== 0) {
      obj.frameLengthMs = Math.round(message.frameLengthMs);
    }
    if (message.threshold !== 0) {
      obj.threshold = message.threshold;
    }
    if (message.enableAutoCalibration !== false) {
      obj.enableAutoCalibration = message.enableAutoCalibration;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADConfiguration>, I>>(base?: I): VADConfiguration {
    return VADConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADConfiguration>, I>>(object: I): VADConfiguration {
    const message = createBaseVADConfiguration();
    message.modelId = object.modelId ?? "";
    message.sampleRate = object.sampleRate ?? 0;
    message.frameLengthMs = object.frameLengthMs ?? 0;
    message.threshold = object.threshold ?? 0;
    message.enableAutoCalibration = object.enableAutoCalibration ?? false;
    return message;
  },
};

function createBaseVADOptions(): VADOptions {
  return { threshold: 0, minSpeechDurationMs: 0, minSilenceDurationMs: 0 };
}

export const VADOptions = {
  encode(message: VADOptions, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.threshold !== 0) {
      writer.uint32(13).float(message.threshold);
    }
    if (message.minSpeechDurationMs !== 0) {
      writer.uint32(16).int32(message.minSpeechDurationMs);
    }
    if (message.minSilenceDurationMs !== 0) {
      writer.uint32(24).int32(message.minSilenceDurationMs);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VADOptions {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 13) {
            break;
          }

          message.threshold = reader.float();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.minSpeechDurationMs = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.minSilenceDurationMs = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADOptions {
    return {
      threshold: isSet(object.threshold) ? globalThis.Number(object.threshold) : 0,
      minSpeechDurationMs: isSet(object.minSpeechDurationMs) ? globalThis.Number(object.minSpeechDurationMs) : 0,
      minSilenceDurationMs: isSet(object.minSilenceDurationMs) ? globalThis.Number(object.minSilenceDurationMs) : 0,
    };
  },

  toJSON(message: VADOptions): unknown {
    const obj: any = {};
    if (message.threshold !== 0) {
      obj.threshold = message.threshold;
    }
    if (message.minSpeechDurationMs !== 0) {
      obj.minSpeechDurationMs = Math.round(message.minSpeechDurationMs);
    }
    if (message.minSilenceDurationMs !== 0) {
      obj.minSilenceDurationMs = Math.round(message.minSilenceDurationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADOptions>, I>>(base?: I): VADOptions {
    return VADOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADOptions>, I>>(object: I): VADOptions {
    const message = createBaseVADOptions();
    message.threshold = object.threshold ?? 0;
    message.minSpeechDurationMs = object.minSpeechDurationMs ?? 0;
    message.minSilenceDurationMs = object.minSilenceDurationMs ?? 0;
    return message;
  },
};

function createBaseVADResult(): VADResult {
  return { isSpeech: false, confidence: 0, energy: 0, durationMs: 0 };
}

export const VADResult = {
  encode(message: VADResult, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isSpeech !== false) {
      writer.uint32(8).bool(message.isSpeech);
    }
    if (message.confidence !== 0) {
      writer.uint32(21).float(message.confidence);
    }
    if (message.energy !== 0) {
      writer.uint32(29).float(message.energy);
    }
    if (message.durationMs !== 0) {
      writer.uint32(32).int32(message.durationMs);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VADResult {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.isSpeech = reader.bool();
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.confidence = reader.float();
          continue;
        case 3:
          if (tag !== 29) {
            break;
          }

          message.energy = reader.float();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.durationMs = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADResult {
    return {
      isSpeech: isSet(object.isSpeech) ? globalThis.Boolean(object.isSpeech) : false,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      energy: isSet(object.energy) ? globalThis.Number(object.energy) : 0,
      durationMs: isSet(object.durationMs) ? globalThis.Number(object.durationMs) : 0,
    };
  },

  toJSON(message: VADResult): unknown {
    const obj: any = {};
    if (message.isSpeech !== false) {
      obj.isSpeech = message.isSpeech;
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.energy !== 0) {
      obj.energy = message.energy;
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADResult>, I>>(base?: I): VADResult {
    return VADResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADResult>, I>>(object: I): VADResult {
    const message = createBaseVADResult();
    message.isSpeech = object.isSpeech ?? false;
    message.confidence = object.confidence ?? 0;
    message.energy = object.energy ?? 0;
    message.durationMs = object.durationMs ?? 0;
    return message;
  },
};

function createBaseVADStatistics(): VADStatistics {
  return { currentEnergy: 0, currentThreshold: 0, ambientLevel: 0, recentAvg: 0, recentMax: 0 };
}

export const VADStatistics = {
  encode(message: VADStatistics, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.currentEnergy !== 0) {
      writer.uint32(13).float(message.currentEnergy);
    }
    if (message.currentThreshold !== 0) {
      writer.uint32(21).float(message.currentThreshold);
    }
    if (message.ambientLevel !== 0) {
      writer.uint32(29).float(message.ambientLevel);
    }
    if (message.recentAvg !== 0) {
      writer.uint32(37).float(message.recentAvg);
    }
    if (message.recentMax !== 0) {
      writer.uint32(45).float(message.recentMax);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VADStatistics {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVADStatistics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 13) {
            break;
          }

          message.currentEnergy = reader.float();
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.currentThreshold = reader.float();
          continue;
        case 3:
          if (tag !== 29) {
            break;
          }

          message.ambientLevel = reader.float();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.recentAvg = reader.float();
          continue;
        case 5:
          if (tag !== 45) {
            break;
          }

          message.recentMax = reader.float();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VADStatistics {
    return {
      currentEnergy: isSet(object.currentEnergy) ? globalThis.Number(object.currentEnergy) : 0,
      currentThreshold: isSet(object.currentThreshold) ? globalThis.Number(object.currentThreshold) : 0,
      ambientLevel: isSet(object.ambientLevel) ? globalThis.Number(object.ambientLevel) : 0,
      recentAvg: isSet(object.recentAvg) ? globalThis.Number(object.recentAvg) : 0,
      recentMax: isSet(object.recentMax) ? globalThis.Number(object.recentMax) : 0,
    };
  },

  toJSON(message: VADStatistics): unknown {
    const obj: any = {};
    if (message.currentEnergy !== 0) {
      obj.currentEnergy = message.currentEnergy;
    }
    if (message.currentThreshold !== 0) {
      obj.currentThreshold = message.currentThreshold;
    }
    if (message.ambientLevel !== 0) {
      obj.ambientLevel = message.ambientLevel;
    }
    if (message.recentAvg !== 0) {
      obj.recentAvg = message.recentAvg;
    }
    if (message.recentMax !== 0) {
      obj.recentMax = message.recentMax;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VADStatistics>, I>>(base?: I): VADStatistics {
    return VADStatistics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VADStatistics>, I>>(object: I): VADStatistics {
    const message = createBaseVADStatistics();
    message.currentEnergy = object.currentEnergy ?? 0;
    message.currentThreshold = object.currentThreshold ?? 0;
    message.ambientLevel = object.ambientLevel ?? 0;
    message.recentAvg = object.recentAvg ?? 0;
    message.recentMax = object.recentMax ?? 0;
    return message;
  },
};

function createBaseSpeechActivityEvent(): SpeechActivityEvent {
  return { eventType: 0, timestampMs: 0, durationMs: 0 };
}

export const SpeechActivityEvent = {
  encode(message: SpeechActivityEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.eventType !== 0) {
      writer.uint32(8).int32(message.eventType);
    }
    if (message.timestampMs !== 0) {
      writer.uint32(16).int64(message.timestampMs);
    }
    if (message.durationMs !== 0) {
      writer.uint32(24).int32(message.durationMs);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SpeechActivityEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeechActivityEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.eventType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.timestampMs = longToNumber(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.durationMs = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeechActivityEvent {
    return {
      eventType: isSet(object.eventType) ? speechActivityKindFromJSON(object.eventType) : 0,
      timestampMs: isSet(object.timestampMs) ? globalThis.Number(object.timestampMs) : 0,
      durationMs: isSet(object.durationMs) ? globalThis.Number(object.durationMs) : 0,
    };
  },

  toJSON(message: SpeechActivityEvent): unknown {
    const obj: any = {};
    if (message.eventType !== 0) {
      obj.eventType = speechActivityKindToJSON(message.eventType);
    }
    if (message.timestampMs !== 0) {
      obj.timestampMs = Math.round(message.timestampMs);
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeechActivityEvent>, I>>(base?: I): SpeechActivityEvent {
    return SpeechActivityEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeechActivityEvent>, I>>(object: I): SpeechActivityEvent {
    const message = createBaseSpeechActivityEvent();
    message.eventType = object.eventType ?? 0;
    message.timestampMs = object.timestampMs ?? 0;
    message.durationMs = object.durationMs ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
