// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v7.34.1
// source: voice_agent_service.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { AudioEncoding, audioEncodingFromJSON, audioEncodingToJSON, VoiceAgentComponentStates } from "./voice_events";

export const protobufPackage = "runanywhere.v1";

/**
 * Empty request type — the voice agent already has its config set via
 * `rac_voice_agent_init()` at handle creation time. The Stream rpc just
 * opens a new event subscription on an existing handle.
 */
export interface VoiceAgentRequest {
  /**
   * Optional: filter the stream to only certain VoiceEvent.payload arms
   * (e.g. "user_said,assistant_token"). Empty = all events.
   */
  eventFilter: string;
}

/**
 * ---------------------------------------------------------------------------
 * v3.2: One-shot voice-turn result.
 *
 * Mirrors Swift `VoiceAgentResult`, Kotlin `VoiceAgentResult`, RN
 * `VoiceTurnResult`, Web `VoiceAgentResult`, Flutter (TBD), and the C ABI
 * `rac_voice_agent_result_t` (rac/features/voice_agent/rac_voice_agent.h).
 * Returned by the `processVoiceTurn` ergonomic API where a single audio
 * blob produces transcription + assistant response + synthesized audio in
 * one call (as opposed to the streaming path served by the Stream rpc).
 * ---------------------------------------------------------------------------
 */
export interface VoiceAgentResult {
  /** Whether the input audio passed VAD's speech-detected check. */
  speechDetected: boolean;
  /** Transcribed text from STT. Unset when speech_detected=false. */
  transcription?:
    | string
    | undefined;
  /**
   * Generated assistant response text from the LLM. Unset when STT
   * produced no transcription or LLM was skipped.
   */
  assistantResponse?:
    | string
    | undefined;
  /**
   * Thinking content extracted from `<think>...</think>` tags
   * (qwen3, deepseek-r1). Unset when the active LLM does not emit
   * a chain-of-thought trace.
   */
  thinkingContent?:
    | string
    | undefined;
  /**
   * Synthesized audio data from TTS. Encoding follows AudioFrameEvent
   * conventions (typically PCM-F32-LE, sample rate per voice). Unset
   * when TTS was skipped or auto_play_tts=false in VoiceSessionConfig.
   */
  synthesizedAudio?:
    | Uint8Array
    | undefined;
  /**
   * Component states captured at the end of the turn — useful for UIs
   * surfacing readiness / partial-failure breakdowns alongside the
   * final result. Unset when the caller does not ask for it.
   */
  finalState?:
    | VoiceAgentComponentStates
    | undefined;
  /**
   * Audio metadata for synthesized_audio. 0/UNSPECIFIED = backend default
   * or unknown.
   */
  synthesizedAudioSampleRateHz: number;
  synthesizedAudioChannels: number;
  synthesizedAudioEncoding: AudioEncoding;
}

/**
 * ---------------------------------------------------------------------------
 * v3.2: Voice session behavior configuration.
 *
 * Mirrors Swift `VoiceSessionConfig` and Kotlin `VoiceSessionConfig`.
 * Controls runtime behavior of the voice agent's session loop — silence
 * timing, speech threshold, auto-TTS playback, continuous mode, and
 * LLM thinking-mode toggle.
 * ---------------------------------------------------------------------------
 */
export interface VoiceSessionConfig {
  /**
   * Silence duration (milliseconds) before processing the speech
   * buffer. Default per Swift/Kotlin: 1500 ms.
   */
  silenceDurationMs: number;
  /**
   * Minimum audio level to detect speech (0.0 - 1.0). Default per
   * Swift/Kotlin: 0.1.
   */
  speechThreshold: number;
  /** Whether to auto-play TTS response after synthesis. Default true. */
  autoPlayTts: boolean;
  /** Whether to auto-resume listening after TTS playback. Default true. */
  continuousMode: boolean;
  /**
   * Whether thinking mode is enabled for the LLM (qwen3, deepseek-r1).
   * Default false.
   */
  thinkingModeEnabled: boolean;
  /** Optional per-turn LLM max token limit. 0 = LLM/default. */
  maxTokens: number;
}

/**
 * ---------------------------------------------------------------------------
 * v3.2: Audio pipeline state-manager configuration.
 *
 * Mirrors rac_audio_pipeline_config_t and the Swift state-manager knobs used
 * to prevent microphone/TTS feedback loops.
 * ---------------------------------------------------------------------------
 */
export interface AudioPipelineConfig {
  cooldownDurationMs: number;
  strictTransitions: boolean;
  maxTtsDurationMs: number;
}

/**
 * ---------------------------------------------------------------------------
 * v3.2: Aggregated voice-agent compose configuration.
 *
 * Mirrors the C ABI `rac_voice_agent_config_t` and Swift
 * `VoiceAgentConfiguration`. The existing `runanywhere.v1.VoiceAgentConfig`
 * (idl/solutions.proto) is kept frozen for the SolutionConfig oneof — this
 * new message provides the fine-grained sub-component view consumed by the
 * `rac_voice_agent_initialize()` C entry-point.
 *
 * Each sub-config string field uses a "model_id" naming convention; the
 * runtime resolves IDs against the model registry. An empty string means
 * "use the currently loaded model/voice for that capability".
 * ---------------------------------------------------------------------------
 */
export interface VoiceAgentComposeConfig {
  /**
   * -------------------------------------------------------------------
   * STT sub-config (mirrors rac_voice_agent_stt_config_t).
   * -------------------------------------------------------------------
   */
  sttModelPath?: string | undefined;
  sttModelId?: string | undefined;
  sttModelName?:
    | string
    | undefined;
  /**
   * -------------------------------------------------------------------
   * LLM sub-config (mirrors rac_voice_agent_llm_config_t).
   * -------------------------------------------------------------------
   */
  llmModelPath?: string | undefined;
  llmModelId?: string | undefined;
  llmModelName?:
    | string
    | undefined;
  /**
   * -------------------------------------------------------------------
   * TTS sub-config (mirrors rac_voice_agent_tts_config_t).
   * -------------------------------------------------------------------
   */
  ttsVoicePath?: string | undefined;
  ttsVoiceId?: string | undefined;
  ttsVoiceName?:
    | string
    | undefined;
  /**
   * -------------------------------------------------------------------
   * VAD sub-config (mirrors rac_voice_agent_vad_config_t).
   * -------------------------------------------------------------------
   */
  vadSampleRate: number;
  /** default 0.1 */
  vadFrameLength: number;
  /** default 0.005 */
  vadEnergyThreshold: number;
  /**
   * -------------------------------------------------------------------
   * Wake-word sub-config (mirrors rac_voice_agent_wakeword_config_t /
   * rac_wakeword_config_t).
   * -------------------------------------------------------------------
   */
  wakewordEnabled: boolean;
  wakewordModelPath?: string | undefined;
  wakewordModelId?: string | undefined;
  wakewordPhrase?:
    | string
    | undefined;
  /** default 0.5 */
  wakewordThreshold: number;
  wakewordEmbeddingModelPath?: string | undefined;
  wakewordVadModelPath?:
    | string
    | undefined;
  /**
   * -------------------------------------------------------------------
   * Session-behavior sub-config. Optional so the C ABI can be invoked
   * without runtime-behavior overrides (engine defaults applied).
   * -------------------------------------------------------------------
   */
  sessionConfig?:
    | VoiceSessionConfig
    | undefined;
  /**
   * Audio state-machine behavior. Optional so defaults can be applied by
   * the native voice-agent implementation.
   */
  audioPipelineConfig?: AudioPipelineConfig | undefined;
}

function createBaseVoiceAgentRequest(): VoiceAgentRequest {
  return { eventFilter: "" };
}

export const VoiceAgentRequest = {
  encode(message: VoiceAgentRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.eventFilter !== "") {
      writer.uint32(10).string(message.eventFilter);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VoiceAgentRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoiceAgentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.eventFilter = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VoiceAgentRequest {
    return { eventFilter: isSet(object.eventFilter) ? globalThis.String(object.eventFilter) : "" };
  },

  toJSON(message: VoiceAgentRequest): unknown {
    const obj: any = {};
    if (message.eventFilter !== "") {
      obj.eventFilter = message.eventFilter;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VoiceAgentRequest>, I>>(base?: I): VoiceAgentRequest {
    return VoiceAgentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VoiceAgentRequest>, I>>(object: I): VoiceAgentRequest {
    const message = createBaseVoiceAgentRequest();
    message.eventFilter = object.eventFilter ?? "";
    return message;
  },
};

function createBaseVoiceAgentResult(): VoiceAgentResult {
  return {
    speechDetected: false,
    transcription: undefined,
    assistantResponse: undefined,
    thinkingContent: undefined,
    synthesizedAudio: undefined,
    finalState: undefined,
    synthesizedAudioSampleRateHz: 0,
    synthesizedAudioChannels: 0,
    synthesizedAudioEncoding: 0,
  };
}

export const VoiceAgentResult = {
  encode(message: VoiceAgentResult, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.speechDetected !== false) {
      writer.uint32(8).bool(message.speechDetected);
    }
    if (message.transcription !== undefined) {
      writer.uint32(18).string(message.transcription);
    }
    if (message.assistantResponse !== undefined) {
      writer.uint32(26).string(message.assistantResponse);
    }
    if (message.thinkingContent !== undefined) {
      writer.uint32(34).string(message.thinkingContent);
    }
    if (message.synthesizedAudio !== undefined) {
      writer.uint32(42).bytes(message.synthesizedAudio);
    }
    if (message.finalState !== undefined) {
      VoiceAgentComponentStates.encode(message.finalState, writer.uint32(50).fork()).ldelim();
    }
    if (message.synthesizedAudioSampleRateHz !== 0) {
      writer.uint32(56).int32(message.synthesizedAudioSampleRateHz);
    }
    if (message.synthesizedAudioChannels !== 0) {
      writer.uint32(64).int32(message.synthesizedAudioChannels);
    }
    if (message.synthesizedAudioEncoding !== 0) {
      writer.uint32(72).int32(message.synthesizedAudioEncoding);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VoiceAgentResult {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoiceAgentResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.speechDetected = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.transcription = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.assistantResponse = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.thinkingContent = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.synthesizedAudio = reader.bytes();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.finalState = VoiceAgentComponentStates.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.synthesizedAudioSampleRateHz = reader.int32();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.synthesizedAudioChannels = reader.int32();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.synthesizedAudioEncoding = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VoiceAgentResult {
    return {
      speechDetected: isSet(object.speechDetected) ? globalThis.Boolean(object.speechDetected) : false,
      transcription: isSet(object.transcription) ? globalThis.String(object.transcription) : undefined,
      assistantResponse: isSet(object.assistantResponse) ? globalThis.String(object.assistantResponse) : undefined,
      thinkingContent: isSet(object.thinkingContent) ? globalThis.String(object.thinkingContent) : undefined,
      synthesizedAudio: isSet(object.synthesizedAudio) ? bytesFromBase64(object.synthesizedAudio) : undefined,
      finalState: isSet(object.finalState) ? VoiceAgentComponentStates.fromJSON(object.finalState) : undefined,
      synthesizedAudioSampleRateHz: isSet(object.synthesizedAudioSampleRateHz)
        ? globalThis.Number(object.synthesizedAudioSampleRateHz)
        : 0,
      synthesizedAudioChannels: isSet(object.synthesizedAudioChannels)
        ? globalThis.Number(object.synthesizedAudioChannels)
        : 0,
      synthesizedAudioEncoding: isSet(object.synthesizedAudioEncoding)
        ? audioEncodingFromJSON(object.synthesizedAudioEncoding)
        : 0,
    };
  },

  toJSON(message: VoiceAgentResult): unknown {
    const obj: any = {};
    if (message.speechDetected !== false) {
      obj.speechDetected = message.speechDetected;
    }
    if (message.transcription !== undefined) {
      obj.transcription = message.transcription;
    }
    if (message.assistantResponse !== undefined) {
      obj.assistantResponse = message.assistantResponse;
    }
    if (message.thinkingContent !== undefined) {
      obj.thinkingContent = message.thinkingContent;
    }
    if (message.synthesizedAudio !== undefined) {
      obj.synthesizedAudio = base64FromBytes(message.synthesizedAudio);
    }
    if (message.finalState !== undefined) {
      obj.finalState = VoiceAgentComponentStates.toJSON(message.finalState);
    }
    if (message.synthesizedAudioSampleRateHz !== 0) {
      obj.synthesizedAudioSampleRateHz = Math.round(message.synthesizedAudioSampleRateHz);
    }
    if (message.synthesizedAudioChannels !== 0) {
      obj.synthesizedAudioChannels = Math.round(message.synthesizedAudioChannels);
    }
    if (message.synthesizedAudioEncoding !== 0) {
      obj.synthesizedAudioEncoding = audioEncodingToJSON(message.synthesizedAudioEncoding);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VoiceAgentResult>, I>>(base?: I): VoiceAgentResult {
    return VoiceAgentResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VoiceAgentResult>, I>>(object: I): VoiceAgentResult {
    const message = createBaseVoiceAgentResult();
    message.speechDetected = object.speechDetected ?? false;
    message.transcription = object.transcription ?? undefined;
    message.assistantResponse = object.assistantResponse ?? undefined;
    message.thinkingContent = object.thinkingContent ?? undefined;
    message.synthesizedAudio = object.synthesizedAudio ?? undefined;
    message.finalState = (object.finalState !== undefined && object.finalState !== null)
      ? VoiceAgentComponentStates.fromPartial(object.finalState)
      : undefined;
    message.synthesizedAudioSampleRateHz = object.synthesizedAudioSampleRateHz ?? 0;
    message.synthesizedAudioChannels = object.synthesizedAudioChannels ?? 0;
    message.synthesizedAudioEncoding = object.synthesizedAudioEncoding ?? 0;
    return message;
  },
};

function createBaseVoiceSessionConfig(): VoiceSessionConfig {
  return {
    silenceDurationMs: 0,
    speechThreshold: 0,
    autoPlayTts: false,
    continuousMode: false,
    thinkingModeEnabled: false,
    maxTokens: 0,
  };
}

export const VoiceSessionConfig = {
  encode(message: VoiceSessionConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.silenceDurationMs !== 0) {
      writer.uint32(8).int32(message.silenceDurationMs);
    }
    if (message.speechThreshold !== 0) {
      writer.uint32(21).float(message.speechThreshold);
    }
    if (message.autoPlayTts !== false) {
      writer.uint32(24).bool(message.autoPlayTts);
    }
    if (message.continuousMode !== false) {
      writer.uint32(32).bool(message.continuousMode);
    }
    if (message.thinkingModeEnabled !== false) {
      writer.uint32(40).bool(message.thinkingModeEnabled);
    }
    if (message.maxTokens !== 0) {
      writer.uint32(48).int32(message.maxTokens);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VoiceSessionConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoiceSessionConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.silenceDurationMs = reader.int32();
          continue;
        case 2:
          if (tag !== 21) {
            break;
          }

          message.speechThreshold = reader.float();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.autoPlayTts = reader.bool();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.continuousMode = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.thinkingModeEnabled = reader.bool();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.maxTokens = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VoiceSessionConfig {
    return {
      silenceDurationMs: isSet(object.silenceDurationMs) ? globalThis.Number(object.silenceDurationMs) : 0,
      speechThreshold: isSet(object.speechThreshold) ? globalThis.Number(object.speechThreshold) : 0,
      autoPlayTts: isSet(object.autoPlayTts) ? globalThis.Boolean(object.autoPlayTts) : false,
      continuousMode: isSet(object.continuousMode) ? globalThis.Boolean(object.continuousMode) : false,
      thinkingModeEnabled: isSet(object.thinkingModeEnabled) ? globalThis.Boolean(object.thinkingModeEnabled) : false,
      maxTokens: isSet(object.maxTokens) ? globalThis.Number(object.maxTokens) : 0,
    };
  },

  toJSON(message: VoiceSessionConfig): unknown {
    const obj: any = {};
    if (message.silenceDurationMs !== 0) {
      obj.silenceDurationMs = Math.round(message.silenceDurationMs);
    }
    if (message.speechThreshold !== 0) {
      obj.speechThreshold = message.speechThreshold;
    }
    if (message.autoPlayTts !== false) {
      obj.autoPlayTts = message.autoPlayTts;
    }
    if (message.continuousMode !== false) {
      obj.continuousMode = message.continuousMode;
    }
    if (message.thinkingModeEnabled !== false) {
      obj.thinkingModeEnabled = message.thinkingModeEnabled;
    }
    if (message.maxTokens !== 0) {
      obj.maxTokens = Math.round(message.maxTokens);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VoiceSessionConfig>, I>>(base?: I): VoiceSessionConfig {
    return VoiceSessionConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VoiceSessionConfig>, I>>(object: I): VoiceSessionConfig {
    const message = createBaseVoiceSessionConfig();
    message.silenceDurationMs = object.silenceDurationMs ?? 0;
    message.speechThreshold = object.speechThreshold ?? 0;
    message.autoPlayTts = object.autoPlayTts ?? false;
    message.continuousMode = object.continuousMode ?? false;
    message.thinkingModeEnabled = object.thinkingModeEnabled ?? false;
    message.maxTokens = object.maxTokens ?? 0;
    return message;
  },
};

function createBaseAudioPipelineConfig(): AudioPipelineConfig {
  return { cooldownDurationMs: 0, strictTransitions: false, maxTtsDurationMs: 0 };
}

export const AudioPipelineConfig = {
  encode(message: AudioPipelineConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.cooldownDurationMs !== 0) {
      writer.uint32(8).int32(message.cooldownDurationMs);
    }
    if (message.strictTransitions !== false) {
      writer.uint32(16).bool(message.strictTransitions);
    }
    if (message.maxTtsDurationMs !== 0) {
      writer.uint32(24).int32(message.maxTtsDurationMs);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AudioPipelineConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioPipelineConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.cooldownDurationMs = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.strictTransitions = reader.bool();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.maxTtsDurationMs = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AudioPipelineConfig {
    return {
      cooldownDurationMs: isSet(object.cooldownDurationMs) ? globalThis.Number(object.cooldownDurationMs) : 0,
      strictTransitions: isSet(object.strictTransitions) ? globalThis.Boolean(object.strictTransitions) : false,
      maxTtsDurationMs: isSet(object.maxTtsDurationMs) ? globalThis.Number(object.maxTtsDurationMs) : 0,
    };
  },

  toJSON(message: AudioPipelineConfig): unknown {
    const obj: any = {};
    if (message.cooldownDurationMs !== 0) {
      obj.cooldownDurationMs = Math.round(message.cooldownDurationMs);
    }
    if (message.strictTransitions !== false) {
      obj.strictTransitions = message.strictTransitions;
    }
    if (message.maxTtsDurationMs !== 0) {
      obj.maxTtsDurationMs = Math.round(message.maxTtsDurationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioPipelineConfig>, I>>(base?: I): AudioPipelineConfig {
    return AudioPipelineConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioPipelineConfig>, I>>(object: I): AudioPipelineConfig {
    const message = createBaseAudioPipelineConfig();
    message.cooldownDurationMs = object.cooldownDurationMs ?? 0;
    message.strictTransitions = object.strictTransitions ?? false;
    message.maxTtsDurationMs = object.maxTtsDurationMs ?? 0;
    return message;
  },
};

function createBaseVoiceAgentComposeConfig(): VoiceAgentComposeConfig {
  return {
    sttModelPath: undefined,
    sttModelId: undefined,
    sttModelName: undefined,
    llmModelPath: undefined,
    llmModelId: undefined,
    llmModelName: undefined,
    ttsVoicePath: undefined,
    ttsVoiceId: undefined,
    ttsVoiceName: undefined,
    vadSampleRate: 0,
    vadFrameLength: 0,
    vadEnergyThreshold: 0,
    wakewordEnabled: false,
    wakewordModelPath: undefined,
    wakewordModelId: undefined,
    wakewordPhrase: undefined,
    wakewordThreshold: 0,
    wakewordEmbeddingModelPath: undefined,
    wakewordVadModelPath: undefined,
    sessionConfig: undefined,
    audioPipelineConfig: undefined,
  };
}

export const VoiceAgentComposeConfig = {
  encode(message: VoiceAgentComposeConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sttModelPath !== undefined) {
      writer.uint32(10).string(message.sttModelPath);
    }
    if (message.sttModelId !== undefined) {
      writer.uint32(18).string(message.sttModelId);
    }
    if (message.sttModelName !== undefined) {
      writer.uint32(26).string(message.sttModelName);
    }
    if (message.llmModelPath !== undefined) {
      writer.uint32(34).string(message.llmModelPath);
    }
    if (message.llmModelId !== undefined) {
      writer.uint32(42).string(message.llmModelId);
    }
    if (message.llmModelName !== undefined) {
      writer.uint32(50).string(message.llmModelName);
    }
    if (message.ttsVoicePath !== undefined) {
      writer.uint32(58).string(message.ttsVoicePath);
    }
    if (message.ttsVoiceId !== undefined) {
      writer.uint32(66).string(message.ttsVoiceId);
    }
    if (message.ttsVoiceName !== undefined) {
      writer.uint32(74).string(message.ttsVoiceName);
    }
    if (message.vadSampleRate !== 0) {
      writer.uint32(80).int32(message.vadSampleRate);
    }
    if (message.vadFrameLength !== 0) {
      writer.uint32(93).float(message.vadFrameLength);
    }
    if (message.vadEnergyThreshold !== 0) {
      writer.uint32(101).float(message.vadEnergyThreshold);
    }
    if (message.wakewordEnabled !== false) {
      writer.uint32(104).bool(message.wakewordEnabled);
    }
    if (message.wakewordModelPath !== undefined) {
      writer.uint32(114).string(message.wakewordModelPath);
    }
    if (message.wakewordModelId !== undefined) {
      writer.uint32(122).string(message.wakewordModelId);
    }
    if (message.wakewordPhrase !== undefined) {
      writer.uint32(130).string(message.wakewordPhrase);
    }
    if (message.wakewordThreshold !== 0) {
      writer.uint32(141).float(message.wakewordThreshold);
    }
    if (message.wakewordEmbeddingModelPath !== undefined) {
      writer.uint32(146).string(message.wakewordEmbeddingModelPath);
    }
    if (message.wakewordVadModelPath !== undefined) {
      writer.uint32(154).string(message.wakewordVadModelPath);
    }
    if (message.sessionConfig !== undefined) {
      VoiceSessionConfig.encode(message.sessionConfig, writer.uint32(162).fork()).ldelim();
    }
    if (message.audioPipelineConfig !== undefined) {
      AudioPipelineConfig.encode(message.audioPipelineConfig, writer.uint32(170).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): VoiceAgentComposeConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoiceAgentComposeConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sttModelPath = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.sttModelId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.sttModelName = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.llmModelPath = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.llmModelId = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.llmModelName = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.ttsVoicePath = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.ttsVoiceId = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.ttsVoiceName = reader.string();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.vadSampleRate = reader.int32();
          continue;
        case 11:
          if (tag !== 93) {
            break;
          }

          message.vadFrameLength = reader.float();
          continue;
        case 12:
          if (tag !== 101) {
            break;
          }

          message.vadEnergyThreshold = reader.float();
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.wakewordEnabled = reader.bool();
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.wakewordModelPath = reader.string();
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.wakewordModelId = reader.string();
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.wakewordPhrase = reader.string();
          continue;
        case 17:
          if (tag !== 141) {
            break;
          }

          message.wakewordThreshold = reader.float();
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.wakewordEmbeddingModelPath = reader.string();
          continue;
        case 19:
          if (tag !== 154) {
            break;
          }

          message.wakewordVadModelPath = reader.string();
          continue;
        case 20:
          if (tag !== 162) {
            break;
          }

          message.sessionConfig = VoiceSessionConfig.decode(reader, reader.uint32());
          continue;
        case 21:
          if (tag !== 170) {
            break;
          }

          message.audioPipelineConfig = AudioPipelineConfig.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VoiceAgentComposeConfig {
    return {
      sttModelPath: isSet(object.sttModelPath) ? globalThis.String(object.sttModelPath) : undefined,
      sttModelId: isSet(object.sttModelId) ? globalThis.String(object.sttModelId) : undefined,
      sttModelName: isSet(object.sttModelName) ? globalThis.String(object.sttModelName) : undefined,
      llmModelPath: isSet(object.llmModelPath) ? globalThis.String(object.llmModelPath) : undefined,
      llmModelId: isSet(object.llmModelId) ? globalThis.String(object.llmModelId) : undefined,
      llmModelName: isSet(object.llmModelName) ? globalThis.String(object.llmModelName) : undefined,
      ttsVoicePath: isSet(object.ttsVoicePath) ? globalThis.String(object.ttsVoicePath) : undefined,
      ttsVoiceId: isSet(object.ttsVoiceId) ? globalThis.String(object.ttsVoiceId) : undefined,
      ttsVoiceName: isSet(object.ttsVoiceName) ? globalThis.String(object.ttsVoiceName) : undefined,
      vadSampleRate: isSet(object.vadSampleRate) ? globalThis.Number(object.vadSampleRate) : 0,
      vadFrameLength: isSet(object.vadFrameLength) ? globalThis.Number(object.vadFrameLength) : 0,
      vadEnergyThreshold: isSet(object.vadEnergyThreshold) ? globalThis.Number(object.vadEnergyThreshold) : 0,
      wakewordEnabled: isSet(object.wakewordEnabled) ? globalThis.Boolean(object.wakewordEnabled) : false,
      wakewordModelPath: isSet(object.wakewordModelPath) ? globalThis.String(object.wakewordModelPath) : undefined,
      wakewordModelId: isSet(object.wakewordModelId) ? globalThis.String(object.wakewordModelId) : undefined,
      wakewordPhrase: isSet(object.wakewordPhrase) ? globalThis.String(object.wakewordPhrase) : undefined,
      wakewordThreshold: isSet(object.wakewordThreshold) ? globalThis.Number(object.wakewordThreshold) : 0,
      wakewordEmbeddingModelPath: isSet(object.wakewordEmbeddingModelPath)
        ? globalThis.String(object.wakewordEmbeddingModelPath)
        : undefined,
      wakewordVadModelPath: isSet(object.wakewordVadModelPath)
        ? globalThis.String(object.wakewordVadModelPath)
        : undefined,
      sessionConfig: isSet(object.sessionConfig) ? VoiceSessionConfig.fromJSON(object.sessionConfig) : undefined,
      audioPipelineConfig: isSet(object.audioPipelineConfig)
        ? AudioPipelineConfig.fromJSON(object.audioPipelineConfig)
        : undefined,
    };
  },

  toJSON(message: VoiceAgentComposeConfig): unknown {
    const obj: any = {};
    if (message.sttModelPath !== undefined) {
      obj.sttModelPath = message.sttModelPath;
    }
    if (message.sttModelId !== undefined) {
      obj.sttModelId = message.sttModelId;
    }
    if (message.sttModelName !== undefined) {
      obj.sttModelName = message.sttModelName;
    }
    if (message.llmModelPath !== undefined) {
      obj.llmModelPath = message.llmModelPath;
    }
    if (message.llmModelId !== undefined) {
      obj.llmModelId = message.llmModelId;
    }
    if (message.llmModelName !== undefined) {
      obj.llmModelName = message.llmModelName;
    }
    if (message.ttsVoicePath !== undefined) {
      obj.ttsVoicePath = message.ttsVoicePath;
    }
    if (message.ttsVoiceId !== undefined) {
      obj.ttsVoiceId = message.ttsVoiceId;
    }
    if (message.ttsVoiceName !== undefined) {
      obj.ttsVoiceName = message.ttsVoiceName;
    }
    if (message.vadSampleRate !== 0) {
      obj.vadSampleRate = Math.round(message.vadSampleRate);
    }
    if (message.vadFrameLength !== 0) {
      obj.vadFrameLength = message.vadFrameLength;
    }
    if (message.vadEnergyThreshold !== 0) {
      obj.vadEnergyThreshold = message.vadEnergyThreshold;
    }
    if (message.wakewordEnabled !== false) {
      obj.wakewordEnabled = message.wakewordEnabled;
    }
    if (message.wakewordModelPath !== undefined) {
      obj.wakewordModelPath = message.wakewordModelPath;
    }
    if (message.wakewordModelId !== undefined) {
      obj.wakewordModelId = message.wakewordModelId;
    }
    if (message.wakewordPhrase !== undefined) {
      obj.wakewordPhrase = message.wakewordPhrase;
    }
    if (message.wakewordThreshold !== 0) {
      obj.wakewordThreshold = message.wakewordThreshold;
    }
    if (message.wakewordEmbeddingModelPath !== undefined) {
      obj.wakewordEmbeddingModelPath = message.wakewordEmbeddingModelPath;
    }
    if (message.wakewordVadModelPath !== undefined) {
      obj.wakewordVadModelPath = message.wakewordVadModelPath;
    }
    if (message.sessionConfig !== undefined) {
      obj.sessionConfig = VoiceSessionConfig.toJSON(message.sessionConfig);
    }
    if (message.audioPipelineConfig !== undefined) {
      obj.audioPipelineConfig = AudioPipelineConfig.toJSON(message.audioPipelineConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VoiceAgentComposeConfig>, I>>(base?: I): VoiceAgentComposeConfig {
    return VoiceAgentComposeConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VoiceAgentComposeConfig>, I>>(object: I): VoiceAgentComposeConfig {
    const message = createBaseVoiceAgentComposeConfig();
    message.sttModelPath = object.sttModelPath ?? undefined;
    message.sttModelId = object.sttModelId ?? undefined;
    message.sttModelName = object.sttModelName ?? undefined;
    message.llmModelPath = object.llmModelPath ?? undefined;
    message.llmModelId = object.llmModelId ?? undefined;
    message.llmModelName = object.llmModelName ?? undefined;
    message.ttsVoicePath = object.ttsVoicePath ?? undefined;
    message.ttsVoiceId = object.ttsVoiceId ?? undefined;
    message.ttsVoiceName = object.ttsVoiceName ?? undefined;
    message.vadSampleRate = object.vadSampleRate ?? 0;
    message.vadFrameLength = object.vadFrameLength ?? 0;
    message.vadEnergyThreshold = object.vadEnergyThreshold ?? 0;
    message.wakewordEnabled = object.wakewordEnabled ?? false;
    message.wakewordModelPath = object.wakewordModelPath ?? undefined;
    message.wakewordModelId = object.wakewordModelId ?? undefined;
    message.wakewordPhrase = object.wakewordPhrase ?? undefined;
    message.wakewordThreshold = object.wakewordThreshold ?? 0;
    message.wakewordEmbeddingModelPath = object.wakewordEmbeddingModelPath ?? undefined;
    message.wakewordVadModelPath = object.wakewordVadModelPath ?? undefined;
    message.sessionConfig = (object.sessionConfig !== undefined && object.sessionConfig !== null)
      ? VoiceSessionConfig.fromPartial(object.sessionConfig)
      : undefined;
    message.audioPipelineConfig = (object.audioPipelineConfig !== undefined && object.audioPipelineConfig !== null)
      ? AudioPipelineConfig.fromPartial(object.audioPipelineConfig)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
