# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hardware_profile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from __future__ import annotations
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hardware_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from runanywhere._proto import storage_types_pb2 as storage__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16hardware_profile.proto\x12\x0erunanywhere.v1\x1a\x13storage_types.proto\"\xae\x01\n\rNpuCapability\x12\x11\n\tsoc_model\x18\x01 \x01(\t\x12\x13\n\x06soc_id\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x31\n\x0chexagon_arch\x18\x03 \x01(\x0e\x32\x1b.runanywhere.v1.HexagonArch\x12\x11\n\tsupported\x18\x04 \x01(\x08\x12$\n\x03npu\x18\x05 \x01(\x0e\x32\x17.runanywhere.v1.NPUChipB\t\n\x07_soc_id*\xc6\x01\n\x16\x41\x63\x63\x65lerationPreference\x12\'\n#ACCELERATION_PREFERENCE_UNSPECIFIED\x10\x00\x12 \n\x1c\x41\x43\x43\x45LERATION_PREFERENCE_AUTO\x10\x01\x12\x1f\n\x1b\x41\x43\x43\x45LERATION_PREFERENCE_CPU\x10\x02\x12\x1f\n\x1b\x41\x43\x43\x45LERATION_PREFERENCE_GPU\x10\x03\x12\x1f\n\x1b\x41\x43\x43\x45LERATION_PREFERENCE_NPU\x10\x04*\xab\x01\n\x0bHexagonArch\x12\x18\n\x14HEXAGON_ARCH_UNKNOWN\x10\x00\x12\x14\n\x10HEXAGON_ARCH_V68\x10\x44\x12\x14\n\x10HEXAGON_ARCH_V69\x10\x45\x12\x14\n\x10HEXAGON_ARCH_V73\x10I\x12\x14\n\x10HEXAGON_ARCH_V75\x10K\x12\x14\n\x10HEXAGON_ARCH_V79\x10O\x12\x14\n\x10HEXAGON_ARCH_V81\x10QB\x8f\x01\n\x17\x61i.runanywhere.proto.v1B\x14HardwareProfileProtoP\x01Z<github.com/runanywhere/runanywhere-sdks/idl/v1;runanywherev1\xf8\x01\x01\xa2\x02\x04RAV1\xaa\x02\x0eRunanywhere.V1\xba\x02\x02RAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hardware_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027ai.runanywhere.proto.v1B\024HardwareProfileProtoP\001Z<github.com/runanywhere/runanywhere-sdks/idl/v1;runanywherev1\370\001\001\242\002\004RAV1\252\002\016Runanywhere.V1\272\002\002RA'
  _globals['_ACCELERATIONPREFERENCE']._serialized_start=241
  _globals['_ACCELERATIONPREFERENCE']._serialized_end=439
  _globals['_HEXAGONARCH']._serialized_start=442
  _globals['_HEXAGONARCH']._serialized_end=613
  _globals['_NPUCAPABILITY']._serialized_start=64
  _globals['_NPUCAPABILITY']._serialized_end=238
# @@protoc_insertion_point(module_scope)
