# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sdk_init.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from __future__ import annotations
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sdk_init.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from runanywhere._proto import errors_pb2 as errors__pb2
from runanywhere._proto import model_types_pb2 as model__types__pb2
from runanywhere._proto import rac_options_pb2 as rac__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esdk_init.proto\x12\x0erunanywhere.v1\x1a\x0c\x65rrors.proto\x1a\x11model_types.proto\x1a\x11rac_options.proto\"\x9b\x02\n\x14SdkInitPhase1Request\x12\x33\n\x0b\x65nvironment\x18\x01 \x01(\x0e\x32\x1e.runanywhere.v1.SDKEnvironment\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t\x12\x10\n\x08\x62\x61se_url\x18\x03 \x01(\t\x12\x11\n\tdevice_id\x18\x04 \x01(\t\x12\x10\n\x08platform\x18\x05 \x01(\t\x12\x13\n\x0bsdk_version\x18\x06 \x01(\t\x12&\n\x12request_timeout_ms\x18\x07 \x01(\x05\x42\x05\xa0\xb5\x18\xe8\x07H\x00\x88\x01\x01\x12\"\n\x0bmax_retries\x18\x08 \x01(\x05\x42\x08\xa0\xb5\x18\x00\xa8\xb5\x18\nH\x01\x88\x01\x01\x42\x15\n\x13_request_timeout_msB\x0e\n\x0c_max_retries\"+\n\x14SdkInitPhase2Request\x12\x13\n\x0b\x62uild_token\x18\x01 \x01(\t\"\xa1\x01\n\rSdkInitResult\x12\'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.runanywhere.v1.SDKError\x12\x1b\n\x13linked_models_count\x18\x02 \x01(\r\x12\x0f\n\x07warning\x18\x03 \x01(\t\x12 \n\x18has_completed_http_setup\x18\x04 \x01(\x08\x12\x17\n\x0fhttp_applicable\x18\x05 \x01(\x08\x42\x87\x01\n\x17\x61i.runanywhere.proto.v1B\x0cSdkInitProtoP\x01Z<github.com/runanywhere/runanywhere-sdks/idl/v1;runanywherev1\xf8\x01\x01\xa2\x02\x04RAV1\xaa\x02\x0eRunanywhere.V1\xba\x02\x02RAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk_init_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027ai.runanywhere.proto.v1B\014SdkInitProtoP\001Z<github.com/runanywhere/runanywhere-sdks/idl/v1;runanywherev1\370\001\001\242\002\004RAV1\252\002\016Runanywhere.V1\272\002\002RA'
  _globals['_SDKINITPHASE1REQUEST'].fields_by_name['request_timeout_ms']._loaded_options = None
  _globals['_SDKINITPHASE1REQUEST'].fields_by_name['request_timeout_ms']._serialized_options = b'\240\265\030\350\007'
  _globals['_SDKINITPHASE1REQUEST'].fields_by_name['max_retries']._loaded_options = None
  _globals['_SDKINITPHASE1REQUEST'].fields_by_name['max_retries']._serialized_options = b'\240\265\030\000\250\265\030\n'
  _globals['_SDKINITPHASE1REQUEST']._serialized_start=87
  _globals['_SDKINITPHASE1REQUEST']._serialized_end=370
  _globals['_SDKINITPHASE2REQUEST']._serialized_start=372
  _globals['_SDKINITPHASE2REQUEST']._serialized_end=415
  _globals['_SDKINITRESULT']._serialized_start=418
  _globals['_SDKINITRESULT']._serialized_end=579
# @@protoc_insertion_point(module_scope)
