# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: thinking_tag_pattern.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from __future__ import annotations
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'thinking_tag_pattern.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1athinking_tag_pattern.proto\x12\x0erunanywhere.v1\"9\n\x12ThinkingTagPattern\x12\x10\n\x08open_tag\x18\x01 \x01(\t\x12\x11\n\tclose_tag\x18\x02 \x01(\t\"\xa0\x01\n\x10ReasoningOptions\x12+\n\x04mode\x18\x01 \x01(\x0e\x32\x1d.runanywhere.v1.ReasoningMode\x12\x19\n\x11include_in_output\x18\x02 \x01(\x08\x12\x38\n\x07pattern\x18\x03 \x01(\x0b\x32\".runanywhere.v1.ThinkingTagPatternH\x00\x88\x01\x01\x42\n\n\x08_pattern*^\n\rReasoningMode\x12\x1e\n\x1aREASONING_MODE_UNSPECIFIED\x10\x00\x12\x16\n\x12REASONING_MODE_OFF\x10\x01\x12\x15\n\x11REASONING_MODE_ON\x10\x02\x42\x92\x01\n\x17\x61i.runanywhere.proto.v1B\x17ThinkingTagPatternProtoP\x01Z<github.com/runanywhere/runanywhere-sdks/idl/v1;runanywherev1\xf8\x01\x01\xa2\x02\x04RAV1\xaa\x02\x0eRunanywhere.V1\xba\x02\x02RAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thinking_tag_pattern_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027ai.runanywhere.proto.v1B\027ThinkingTagPatternProtoP\001Z<github.com/runanywhere/runanywhere-sdks/idl/v1;runanywherev1\370\001\001\242\002\004RAV1\252\002\016Runanywhere.V1\272\002\002RA'
  _globals['_REASONINGMODE']._serialized_start=268
  _globals['_REASONINGMODE']._serialized_end=362
  _globals['_THINKINGTAGPATTERN']._serialized_start=46
  _globals['_THINKINGTAGPATTERN']._serialized_end=103
  _globals['_REASONINGOPTIONS']._serialized_start=106
  _globals['_REASONINGOPTIONS']._serialized_end=266
# @@protoc_insertion_point(module_scope)
