// SPDX-License-Identifier: Apache-2.0
//
// GENERATED FILE — DO NOT EDIT.
// Regenerate with: idl/codegen/generate_cpp_defaults.py
//
// Every macro here comes from a `(runanywhere.v1.rac_default)` annotation in
// idl/. Change the value in the .proto, not here: the SDKs generate their own
// defaults from the same annotations, so editing this file only desynchronizes
// C++ from the five platform SDKs.

#ifndef RAC_DEFAULTS_GENERATED_H
#define RAC_DEFAULTS_GENERATED_H

#include "rac/core/rac_types.h"  // RAC_TRUE / RAC_FALSE

// ToolCallingOptions (tool_calling.proto)
#define RAC_DEFAULT_TOOL_CALLING_OPTIONS_MAX_TOOL_CALLS 5

// StructuredOutputOptions (structured_output.proto)
#define RAC_DEFAULT_STRUCTURED_OUTPUT_OPTIONS_INCLUDE_SCHEMA_IN_PROMPT RAC_TRUE

// LLMGenerationOptions (llm_options.proto)
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_MAX_OUTPUT_TOKENS 512
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_TEMPERATURE       0.7f
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_TOP_P             1.0f
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_TOP_K             40
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_REPEAT_PENALTY    1.1f
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_SEED              0LL
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_FREQUENCY_PENALTY 0.0f
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_PRESENCE_PENALTY  0.0f
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_REPEAT_LAST_N     0
#define RAC_DEFAULT_LLM_GENERATION_OPTIONS_MIN_P             0.05f

// LLMConfiguration (llm_options.proto)
#define RAC_DEFAULT_LLM_CONFIGURATION_CONTEXT_LENGTH 2048

// DiarizationOptions (diarization.proto)
#define RAC_DEFAULT_DIARIZATION_OPTIONS_SAMPLE_RATE 16000
#define RAC_DEFAULT_DIARIZATION_OPTIONS_CHANNELS    1
#define RAC_DEFAULT_DIARIZATION_OPTIONS_THRESHOLD   0.5f

// DiffusionGenerationOptions (diffusion_options.proto)
#define RAC_DEFAULT_DIFFUSION_GENERATION_OPTIONS_WIDTH          0
#define RAC_DEFAULT_DIFFUSION_GENERATION_OPTIONS_HEIGHT         0
#define RAC_DEFAULT_DIFFUSION_GENERATION_OPTIONS_STEPS          0
#define RAC_DEFAULT_DIFFUSION_GENERATION_OPTIONS_GUIDANCE_SCALE 0.0f
#define RAC_DEFAULT_DIFFUSION_GENERATION_OPTIONS_STRENGTH       0.75f
#define RAC_DEFAULT_DIFFUSION_GENERATION_OPTIONS_N              1

// EmbeddingsOptions (embeddings_options.proto)
#define RAC_DEFAULT_EMBEDDINGS_OPTIONS_NORMALIZE RAC_TRUE
#define RAC_DEFAULT_EMBEDDINGS_OPTIONS_N_THREADS 0

// BatteryFilter (hybrid_router.proto)
#define RAC_DEFAULT_BATTERY_FILTER_MIN_BATTERY_PERCENT 20

// ConfidenceCascade (hybrid_router.proto)
#define RAC_DEFAULT_CONFIDENCE_CASCADE_THRESHOLD 0.5f

// HybridRoutingPolicy (hybrid_router.proto)
#define RAC_DEFAULT_HYBRID_ROUTING_POLICY_ATTEMPT_TIMEOUT_MS 0

// LoggingConfiguration (logging.proto)
#define RAC_DEFAULT_LOGGING_CONFIGURATION_ENABLE_LOCAL_LOGGING RAC_TRUE

// LoraAdapterConfig (lora_options.proto)
#define RAC_DEFAULT_LORA_ADAPTER_CONFIG_SCALE 1.0f

// LoraAdapterCatalogEntry (lora_options.proto)
#define RAC_DEFAULT_LORA_ADAPTER_CATALOG_ENTRY_DEFAULT_SCALE 1.0f

// RAGConfiguration (rag.proto)
#define RAC_DEFAULT_RAG_CONFIGURATION_TOP_K           5
#define RAC_DEFAULT_RAG_CONFIGURATION_SCORE_THRESHOLD 0.0f
#define RAC_DEFAULT_RAG_CONFIGURATION_CHUNK_SIZE      512
#define RAC_DEFAULT_RAG_CONFIGURATION_CHUNK_OVERLAP   64

// RAGRetrievalOptions (rag.proto)
#define RAC_DEFAULT_RAG_RETRIEVAL_OPTIONS_MULTI_QUERY_COUNT 3

// RerankOptions (rerank.proto)
#define RAC_DEFAULT_RERANK_OPTIONS_TOP_N              0
#define RAC_DEFAULT_RERANK_OPTIONS_MAX_TOKENS_PER_DOC 0

// NetworkDefaults (sdk_defaults.proto)
#define RAC_DEFAULT_NETWORK_REQUEST_TIMEOUT_MS    60000
#define RAC_DEFAULT_NETWORK_RESOURCE_TIMEOUT_MS   600000
#define RAC_DEFAULT_NETWORK_STREAMING_TIMEOUT_MS  86400000
#define RAC_DEFAULT_NETWORK_ADAPTER_TIMEOUT_MS    30000
#define RAC_DEFAULT_NETWORK_CONNECT_TIMEOUT_MS    30000
#define RAC_DEFAULT_NETWORK_STREAM_CHUNK_BYTES    262144
#define RAC_DEFAULT_NETWORK_MAX_RETRIES           3
#define RAC_DEFAULT_NETWORK_RETRY_BACKOFF_BASE_MS 100

// ConnectDefaults (sdk_defaults.proto)
#define RAC_DEFAULT_CONNECT_CONNECT_TIMEOUT_MS         5000
#define RAC_DEFAULT_CONNECT_GENERATION_READ_TIMEOUT_MS 120000

// AudioCaptureDefaults (sdk_defaults.proto)
#define RAC_DEFAULT_AUDIO_CAPTURE_MIC_SAMPLE_RATE_HZ   16000
#define RAC_DEFAULT_AUDIO_CAPTURE_MIC_CHANNELS         1
#define RAC_DEFAULT_AUDIO_CAPTURE_MIC_CHANNEL_CAPACITY 128
#define RAC_DEFAULT_AUDIO_CAPTURE_TTS_SAMPLE_RATE_HZ   22050

// VoiceAgentDefaults (sdk_defaults.proto)
#define RAC_DEFAULT_VOICE_AGENT_MAX_TOKENS              96
#define RAC_DEFAULT_VOICE_AGENT_TEMPERATURE             0.0f
#define RAC_DEFAULT_VOICE_AGENT_DEFAULT_VAD_MODEL_ID    "silero-vad"
#define RAC_DEFAULT_VOICE_AGENT_SPEECH_RMS_THRESHOLD    0.015f
#define RAC_DEFAULT_VOICE_AGENT_SPEECH_FLOOR_MULTIPLIER 2.0f

// WorkerDefaults (sdk_defaults.proto)
#define RAC_DEFAULT_WORKER_HANDSHAKE_TIMEOUT_MS    10000
#define RAC_DEFAULT_WORKER_BACKEND_INIT_TIMEOUT_MS 120000

// FFIDefaults (sdk_defaults.proto)
#define RAC_DEFAULT_FFI_PATH_BUFFER_BYTES 1024

// EnvironmentDefaults (sdk_defaults.proto)
#define RAC_DEFAULT_ENVIRONMENT_PRODUCTION_BASE_URL         "https://api.runanywhere.ai"
#define RAC_DEFAULT_ENVIRONMENT_DEVELOPMENT_BASE_URL        "https://dev-api.runanywhere.ai"
#define RAC_DEFAULT_ENVIRONMENT_DEVELOPMENT_PLACEHOLDER_URL "https://dev.runanywhere.local"

// StructuredOutputDefaults (sdk_defaults.proto)
#define RAC_DEFAULT_STRUCTURED_OUTPUT_MAX_TOKENS  512
#define RAC_DEFAULT_STRUCTURED_OUTPUT_TEMPERATURE 0.0f

// StorageDefaults (sdk_defaults.proto)
#define RAC_DEFAULT_STORAGE_CONTEXT_LENGTH 2048

// VADConfiguration (vad_options.proto)
#define RAC_DEFAULT_VAD_CONFIGURATION_SAMPLE_RATE            16000
#define RAC_DEFAULT_VAD_CONFIGURATION_FRAME_LENGTH_MS        100
#define RAC_DEFAULT_VAD_CONFIGURATION_ACTIVATION_THRESHOLD   0.5f
#define RAC_DEFAULT_VAD_CONFIGURATION_CALIBRATION_MULTIPLIER 2.0f

// VADOptions (vad_options.proto)
#define RAC_DEFAULT_VAD_OPTIONS_ACTIVATION_THRESHOLD    0.5f
#define RAC_DEFAULT_VAD_OPTIONS_MIN_SPEECH_DURATION_MS  250
#define RAC_DEFAULT_VAD_OPTIONS_MIN_SILENCE_DURATION_MS 500
#define RAC_DEFAULT_VAD_OPTIONS_PREFIX_PADDING_MS       300
#define RAC_DEFAULT_VAD_OPTIONS_SAMPLE_RATE             16000

// STTConfiguration (stt_options.proto)
#define RAC_DEFAULT_STT_CONFIGURATION_SAMPLE_RATE            16000
#define RAC_DEFAULT_STT_CONFIGURATION_ENABLE_PUNCTUATION     RAC_TRUE
#define RAC_DEFAULT_STT_CONFIGURATION_ENABLE_WORD_TIMESTAMPS RAC_TRUE

// STTOptions (stt_options.proto)
#define RAC_DEFAULT_STT_OPTIONS_ENABLE_PUNCTUATION     RAC_TRUE
#define RAC_DEFAULT_STT_OPTIONS_ENABLE_WORD_TIMESTAMPS RAC_TRUE
#define RAC_DEFAULT_STT_OPTIONS_SILENCE_DURATION_MS    0

// TTSOptions (tts_options.proto)
#define RAC_DEFAULT_TTS_OPTIONS_LANGUAGE_CODE "en-US"
#define RAC_DEFAULT_TTS_OPTIONS_SPEED         1.0f
#define RAC_DEFAULT_TTS_OPTIONS_PITCH         1.0f
#define RAC_DEFAULT_TTS_OPTIONS_VOLUME        1.0f
#define RAC_DEFAULT_TTS_OPTIONS_SAMPLE_RATE   0

// 85 defaults across 30 messages.
#endif  // RAC_DEFAULTS_GENERATED_H
