"""Error enums generated from idl/errors.proto.

GENERATED FILE — DO NOT EDIT.
Regenerate with: idl/codegen/generate_python_errors.py

Values are the positive canonical numbers from the IDL. The C ABI returns
them negated as rac_result_t; negate once at the boundary rather than
maintaining a second table.
"""

from __future__ import annotations

from enum import IntEnum


class ErrorCode(IntEnum):
    """Generated from the ErrorCode enum in idl/errors.proto."""

    UNSPECIFIED = 0
    NOT_INITIALIZED = 100
    ALREADY_INITIALIZED = 101
    INITIALIZATION_FAILED = 102
    INVALID_CONFIGURATION = 103
    INVALID_API_KEY = 104
    ENVIRONMENT_MISMATCH = 105
    INVALID_PARAMETER = 106
    MODEL_NOT_FOUND = 110
    MODEL_LOAD_FAILED = 111
    MODEL_VALIDATION_FAILED = 112
    MODEL_INCOMPATIBLE = 113
    INVALID_MODEL_FORMAT = 114
    MODEL_STORAGE_CORRUPTED = 115
    MODEL_NOT_LOADED = 116
    GENERATION_FAILED = 130
    GENERATION_TIMEOUT = 131
    CONTEXT_TOO_LONG = 132
    TOKEN_LIMIT_EXCEEDED = 133
    COST_LIMIT_EXCEEDED = 134
    INFERENCE_FAILED = 135
    GENERATION_CANCELLED = 136
    NETWORK_UNAVAILABLE = 150
    NETWORK_ERROR = 151
    REQUEST_FAILED = 152
    DOWNLOAD_FAILED = 153
    SERVER_ERROR = 154
    TIMEOUT = 155
    INVALID_RESPONSE = 156
    HTTP_ERROR = 157
    CONNECTION_LOST = 158
    PARTIAL_DOWNLOAD = 159
    HTTP_REQUEST_FAILED = 160
    HTTP_NOT_SUPPORTED = 161
    INSUFFICIENT_STORAGE = 180
    STORAGE_FULL = 181
    STORAGE_ERROR = 182
    FILE_NOT_FOUND = 183
    FILE_READ_FAILED = 184
    FILE_WRITE_FAILED = 185
    PERMISSION_DENIED = 186
    DELETE_FAILED = 187
    MOVE_FAILED = 188
    DIRECTORY_CREATION_FAILED = 189
    DIRECTORY_NOT_FOUND = 190
    INVALID_PATH = 191
    INVALID_FILE_NAME = 192
    TEMP_FILE_CREATION_FAILED = 193
    HARDWARE_UNSUPPORTED = 220
    INSUFFICIENT_MEMORY = 221
    COMPONENT_NOT_READY = 230
    INVALID_STATE = 231
    SERVICE_NOT_AVAILABLE = 232
    SERVICE_BUSY = 233
    PROCESSING_FAILED = 234
    START_FAILED = 235
    NOT_SUPPORTED = 236
    VALIDATION_FAILED = 250
    INVALID_INPUT = 251
    INVALID_FORMAT = 252
    EMPTY_INPUT = 253
    TEXT_TOO_LONG = 254
    INVALID_SSML = 255
    INVALID_SPEAKING_RATE = 256
    INVALID_PITCH = 257
    INVALID_VOLUME = 258
    INVALID_ARGUMENT = 259
    NULL_POINTER = 260
    BUFFER_TOO_SMALL = 261
    OUTPUT_TRUNCATED = 262
    AUDIO_FORMAT_NOT_SUPPORTED = 280
    AUDIO_SESSION_FAILED = 281
    MICROPHONE_PERMISSION_DENIED = 282
    INSUFFICIENT_AUDIO_DATA = 283
    EMPTY_AUDIO_BUFFER = 284
    AUDIO_SESSION_ACTIVATION_FAILED = 285
    LANGUAGE_NOT_SUPPORTED = 300
    VOICE_NOT_AVAILABLE = 301
    STREAMING_NOT_SUPPORTED = 302
    STREAM_CANCELLED = 303
    AUTHENTICATION_FAILED = 320
    UNAUTHORIZED = 321
    FORBIDDEN = 322
    KEYCHAIN_ERROR = 330
    ENCODING_ERROR = 331
    DECODING_ERROR = 332
    SECURE_STORAGE_FAILED = 333
    EXTRACTION_FAILED = 350
    CHECKSUM_MISMATCH = 351
    UNSUPPORTED_ARCHIVE = 352
    CALIBRATION_FAILED = 370
    CALIBRATION_TIMEOUT = 371
    CANCELLED = 380
    MODULE_NOT_FOUND = 400
    MODULE_ALREADY_REGISTERED = 401
    MODULE_LOAD_FAILED = 402
    SERVICE_NOT_FOUND = 410
    SERVICE_ALREADY_REGISTERED = 411
    SERVICE_CREATE_FAILED = 412
    CAPABILITY_NOT_FOUND = 420
    PROVIDER_NOT_FOUND = 421
    NO_CAPABLE_PROVIDER = 422
    NOT_FOUND = 423
    ADAPTER_NOT_SET = 500
    BACKEND_NOT_FOUND = 600
    BACKEND_NOT_READY = 601
    BACKEND_INIT_FAILED = 602
    BACKEND_BUSY = 603
    BACKEND_UNAVAILABLE = 604
    RUNTIME_UNAVAILABLE = 605
    BACKEND_ERROR = 606
    INVALID_HANDLE = 610
    EVENT_INVALID_CATEGORY = 700
    EVENT_SUBSCRIPTION_FAILED = 701
    EVENT_PUBLISH_FAILED = 702
    NOT_IMPLEMENTED = 800
    FEATURE_NOT_AVAILABLE = 801
    FRAMEWORK_NOT_AVAILABLE = 802
    UNSUPPORTED_MODALITY = 803
    UNKNOWN = 804
    INTERNAL = 805
    ABI_VERSION_MISMATCH = 810
    CAPABILITY_UNSUPPORTED = 811
    PLUGIN_DUPLICATE = 812
    PLUGIN_LOAD_FAILED = 820
    PLUGIN_BUSY = 821
    WASM_LOAD_FAILED = 900
    WASM_NOT_LOADED = 901
    WASM_CALLBACK_ERROR = 902
    WASM_MEMORY_ERROR = 903


class ErrorCategory(IntEnum):
    """Generated from the ErrorCategory enum in idl/errors.proto."""

    UNSPECIFIED = 0
    NETWORK = 1
    VALIDATION = 2
    MODEL = 3
    COMPONENT = 4
    IO = 5
    AUTH = 6
    INTERNAL = 7
    CONFIGURATION = 8


__all__ = ["ErrorCode", "ErrorCategory"]
